### ISSUE TITLE
[FR]: [Crashlytics] Add flag to skip stack trace capture for errors

### ISSUE THREAD

**Issue by anton-plebanovich** [firebase/firebase-ios-sdk#11454]
### Description

I don't need stack trace for my errors and so I want to reduce performance impact by skipping stack trace capture at all. I log errors in the background thread in the special logger class and so the stack trace is always the same for all errors. Moreover, since it impacts the error title on the Crashlytics report page it looks messy.
<img width="1204" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/10807812/db19a396-ae8c-4f76-98c6-9a3dfac53d04">

If possible, I want to also control the error title. At least I want to return it to the previous times when it was set from the error domain.

### API Proposal

Not sure if it impacts API somehow. If stack trace is a required parameter it may require some changes to properly process it when it is a `nil` value.

### Firebase Product(s)

Crashlytics

**Comment by paulz** [comment]
we have a similar issue: https://github.com/firebase/firebase-ios-sdk/issues/11474

we have many errors with the same title, but would like to keep stack traces, just trimmed to the actual error

**Comment by rizafran** [comment]
Hi @anton-plebanovich, it seems that your issue is caused by the recent changes on how [Crashlytics groups the issues](https://firebase.google.com/docs/crashlytics/troubleshooting?platform=ios#two-different-issue-formats). I've found a similar request internally, but we can't share any details or timeline as to when this could be materialized. I'll keep this issue open and we will let you know of any updates regarding this. Thanks!

**Comment by anton-plebanovich** [comment]
Thanks @rizafran for the reply 👍

**Comment by wardehuang** [comment]
Is there any update? The infomation at crashlytics is hardly readable. We got more than 100 events in one variant, all I can do is clicking the left right arrow to check every single event, that is realy annoying.

![image](https://github.com/firebase/firebase-ios-sdk/assets/1259296/a2d3888a-4b0d-4ea9-8b2d-b5e2f10ff6d9)

**Comment by anton-plebanovich** [comment]
In my case, the issue was solved `Firebase/Crashlytics (10.19.0)`

**Comment by wardehuang** [comment]
> In my case, the issue was solved `Firebase/Crashlytics (10.19.0)`

I am using bom, I will try to  specify that version manually, thanks.
![image](https://github.com/firebase/firebase-ios-sdk/assets/1259296/56c7d220-ddeb-422b-ad8a-7e6c8dd89b20)

**Comment by anton-plebanovich** [comment]
And I'm on the iOS platform, so I am not sure about the Android

**Comment by wardehuang** [comment]
I've just check that I was using the latest version (18.6.0) of Crashlytics Android. The problem is still exists :(

**Comment by paulb777** [comment]
Since the issue is solved on iOS, I'll close. For Android, please follow or open an issue at https://github.com/firebase/firebase-android-sdk/issues

**Comment by paulb777** [comment]
Thanks for the clarification. I'll leave it open for the Crashlytics team to assess.

**Comment by alexsinger** [comment]
@anton-plebanovich thanks for the request. We don't have plans to exclude stack traces from reports since that logging use case falls outside of Crashlytics. If you're mainly looking to log the number of event occurrences, using Google Analytic Events is maybe a better option. I am interested in looking at improvements we can make to the issue titles. Are you able to send me your Firebase project ID to alexsinger@google.com?

**Comment by anton-plebanovich** [comment]
Hi @alexsinger there is no issue with the titles anymore. It was fixed already. There are two concerns regarding stack trace capture for error reports:
- It slowdowns execution
- It does not provide any useful info in my use case since I always log errors from the same place

I also checked existing logic and there is a `recordExceptionModel` method for `FIRCrashlytics` which allows the submission of a custom stack trace that might be empty so I thought it would be possible to implement a similar thing for error reports.

Is error capture so fundamentally different from exception capture that we can't have an empty stack trace there? Or, is it possible to submit a dummy/constant stack trace at least?
