### ISSUE TITLE
Cannot disable automated tracking of view_screen

### ISSUE THREAD

**Issue by DancingWind** [firebase/firebase-ios-sdk#12188]
### Description

It seems Firebase sdk is still logging automatically screen_views even though it is disabled in info.plist with `FirebaseAutomaticScreenReportingEnabled` key set to 
`NO`
We then track all needed sceen_view events manually.

But all unneeded screens still appear in our analytics:

And we clearly see in debug log that screen view events are happeneing:
`App screen changed. Screen entry: Pigu_lt.TextCarouselTopBannerPage.`

BannerCarouselPage is as it sounds a page from banner carosuel that gets tagged everytime (ever 5-8s) new banner is presented

View stack is fancy but inherently there is nothing special TabVC -> NavController as tab -> HomeVC with collectionView -> cell with UIPageController (UIPageController is childVC of HomeVC, UIPageController.view is subview of cell) -> BannerCarouselPage is the page of UIPageController

What is funny if I enable `FirebaseAutomaticScreenReportingEnabled` then debug start to complain:
`10.19.0 - [FirebaseAnalytics][I-ACS031006] View controller already tracked. Class, ID: BannerCarouselPage, -1371341363661211033`

Another weirdness probably not related is:
`10.19.0 - [FirebasePerformance][I-PRF100009] Logging trace metric - _st_TextCarouselTopBannerPage 5000.6940ms. In a minute, visit the Firebase console to view your data: https://console.firebase.google.com/project/pigult-2022/performance/app/ios:lt.pigu.pigu/troubleshooting/trace/SCREEN_TRACE/_st_TextCarouselTopBannerPage?utm_source=perf-ios-sdk&utm_medium=ios-ide`
except banners run fine 5000ms is 5s for the timer to display next page

### Firebase SDK Version

10.19.0

### Xcode Version

15.1

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
With automatic loging Enabled:

App screen changed. Screen entry: Pigu_lt.UspCarouselPage.
10.19.0 - [FirebaseAnalytics][I-ACS031006] View controller already tracked. Class, ID: BannerCarouselPage, -1371341363661211033
10.19.0 - [FirebasePerformance][I-PRF100009] Logging trace metric - _st_UspCarouselPage 3048.9650ms. In a minute, visit the Firebase console to view your data: https://console.firebase.google.com/project/pigult-2022/performance/app/ios:lt.pigu.pigu/troubleshooting/trace/SCREEN_TRACE/_st_UspCarouselPage?utm_source=perf-ios-sdk&utm_medium=ios-ide
10.19.0 - [FirebaseInstallations][I-FIS002000] -[FIRInstallationsIDController createGetInstallationItemPromise], appName: __FIRAPP_DEFAULT
10.19.0 - [FirebaseInstallations][I-FIS002001] -[FIRInstallationsIDController installationWithValidAuthTokenForcingRefresh:0], appName: __FIRAPP_DEFAULT
10.19.0 - [FirebaseAnalytics][I-ACS031006] View controller already tracked. Class, ID: BannerCarouselPage, -1371341363661211033
App screen changed. Screen entry: Pigu_lt.TextCarouselTopBannerPage.
10.19.0 - [FirebaseAnalytics][I-ACS031006] View controller already tracked. Class, ID: BannerCarouselPage, -1371341363661211033
10.19.0 - [FirebaseAnalytics][I-ACS031006] View controller already tracked. Class, ID: BannerCarouselPage, -1371341363661211033
10.19.0 - [FirebasePerformance][I-PRF100009] Logging trace metric - _st_TextCarouselTopBannerPage 4996.6340ms. In a minute, visit the Firebase console to view your data: https://console.firebase.google.com/project/pigult-2022/performance/app/ios:lt.pigu.pigu/troubleshooting/trace/SCREEN_TRACE/_st_TextCarouselTopBannerPage?utm_source=perf-ios-sdk&utm_medium=ios-ide
10.19.0 - [FirebaseInstallations][I-FIS002000] -[FIRInstallationsIDController createGetInstallationItemPromise], appName: __FIRAPP_DEFAULT
10.19.0 - [FirebaseInstallations][I-FIS002001] -[FIRInstallationsIDController installationWithValidAuthTokenForcingRefresh:0], appName: __FIRAPP_DEFAULT
App screen changed. Screen entry: Pigu_lt.UspCarouselPage.
10.19.0 - [FirebaseAnalytics][I-ACS031006] View controller already tracked. Class, ID: BannerCarouselPage, -1371341363661211033
10.19.0 - [FirebaseAnalytics][I-ACS031006] View controller already tracked. Class, ID: BannerCarouselPage, -1371341363661211033
10.19.0 - [FirebasePerformance][I-PRF100009] Logging trace metric - _st_UspCarouselPage 3020.5030ms. In a minute, visit the Firebase console to view your data: https://console.firebase.google.com/project/pigult-2022/performance/app/ios:lt.pigu.pigu/troubleshooting/trace/SCREEN_TRACE/_st_UspCarouselPage?utm_source=perf-ios-sdk&utm_medium=ios-ide
10.19.0 - [FirebaseInstallations][I-FIS002000] -[FIRInstallationsIDController createGetInstallationItemPromise], appName: __FIRAPP_DEFAULT
10.19.0 - [FirebaseInstallations][I-FIS002001] -[FIRInstallationsIDController installationWithValidAuthTokenForcingRefresh:0], appName: __FIRAPP_DEFAULT
App screen changed. Screen entry: Pigu_lt.TextCarouselTopBannerPage.
10.19.0 - [FirebaseAnalytics][I-ACS031006] View controller already tracked. Class, ID: BannerCarouselPage, -1371341363661211033
10.19.0 - [FirebaseAnalytics][I-ACS031006] View controller already tracked. Class, ID: BannerCarouselPage, -1371341363661211033
10.19.0 - [FirebasePerformance][I-PRF100009] Logging trace metric - _st_TextCarouselTopBannerPage 5000.6940ms. In a minute, visit the Firebase console to view your data: https://console.firebase.google.com/project/pigult-2022/performance/app/ios:lt.pigu.pigu/troubleshooting/trace/SCREEN_TRACE/_st_TextCarouselTopBannerPage?utm_source=perf-ios-sdk&utm_medium=ios-ide
10.19.0 - [FirebaseInstallations][I-FIS002000] -[FIRInstallationsIDController createGetInstallationItemPromise], appName: __FIRAPP_DEFAULT
10.19.0 - [FirebaseInstallations][I-FIS002001] -[FIRInstallationsIDController installationWithValidAuthTokenForcingRefresh:0], appName: __FIRAPP_DEFAULT

With Logging disabled:
App screen changed. Screen entry: Pigu_lt.NavigationController.
App screen changed. Screen entry: Pigu_lt.HomeViewController.
App screen changed. Screen entry: UIPageViewController.
App screen changed. Screen entry: Pigu_lt.BannerCarouselPage.
App screen changed. Screen entry: UIPageViewController.
App screen changed. Screen entry: UIPageViewController.
App screen changed. Screen entry: Pigu_lt.UspCarouselPage.
App screen changed. Screen entry: Pigu_lt.UspCarouselPage.
App screen changed. Screen entry: Pigu_lt.TextCarouselTopBannerPage.
App screen changed. Screen entry: Pigu_lt.UspCarouselPage.
App screen changed. Screen entry: Pigu_lt.BannerCarouselPage.
App screen changed. Screen entry: Pigu_lt.UspCarouselPage.
App screen changed. Screen entry: Pigu_lt.TextCarouselTopBannerPage.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

PODS:
  - "!ProtoCompiler (3.21.5)":
    - Protobuf (~> 3.0)
  - "!ProtoCompiler-gRPCPlugin (1.49.0)":
    - "!ProtoCompiler (= 3.21.5)"
    - gRPC-ProtoRPC (= 1.49.0)
  - abseil/algorithm/algorithm (1.20220623.0):
    - abseil/base/config
  - abseil/algorithm/container (1.20220623.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/base/atomic_hook (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/base (1.20220623.0):
    - abseil/base/atomic_hook
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/log_severity
    - abseil/base/raw_logging_internal
    - abseil/base/spinlock_wait
    - abseil/meta/type_traits
  - abseil/base/base_internal (1.20220623.0):
    - abseil/base/config
    - abseil/meta/type_traits
  - abseil/base/config (1.20220623.0)
  - abseil/base/core_headers (1.20220623.0):
    - abseil/base/config
  - abseil/base/dynamic_annotations (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/endian (1.20220623.0):
    - abseil/base/base
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/errno_saver (1.20220623.0):
    - abseil/base/config
  - abseil/base/fast_type_id (1.20220623.0):
    - abseil/base/config
  - abseil/base/log_severity (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/malloc_internal (1.20220623.0):
    - abseil/base/base
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/raw_logging_internal
  - abseil/base/prefetch (1.20220623.0):
    - abseil/base/config
  - abseil/base/raw_logging_internal (1.20220623.0):
    - abseil/base/atomic_hook
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/errno_saver
    - abseil/base/log_severity
  - abseil/base/spinlock_wait (1.20220623.0):
    - abseil/base/base_internal
    - abseil/base/core_headers
    - abseil/base/errno_saver
  - abseil/base/strerror (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/errno_saver
  - abseil/base/throw_delegate (1.20220623.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/container/common (1.20220623.0):
    - abseil/meta/type_traits
    - abseil/types/optional
  - abseil/container/compressed_tuple (1.20220623.0):
    - abseil/utility/utility
  - abseil/container/container_memory (1.20220623.0):
    - abseil/base/config
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/utility/utility
  - abseil/container/fixed_array (1.20220623.0):
    - abseil/algorithm/algorithm
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/throw_delegate
    - abseil/container/compressed_tuple
    - abseil/memory/memory
  - abseil/container/flat_hash_map (1.20220623.0):
    - abseil/algorithm/container
    - abseil/base/core_headers
    - abseil/container/container_memory
    - abseil/container/hash_function_defaults
    - abseil/container/raw_hash_map
    - abseil/memory/memory
  - abseil/container/flat_hash_set (1.20220623.0):
    - abseil/algorithm/container
    - abseil/base/core_headers
    - abseil/container/container_memory
    - abseil/container/hash_function_defaults
    - abseil/container/raw_hash_set
    - abseil/memory/memory
  - abseil/container/hash_function_defaults (1.20220623.0):
    - abseil/base/config
    - abseil/hash/hash
    - abseil/strings/cord
    - abseil/strings/strings
  - abseil/container/hash_policy_traits (1.20220623.0):
    - abseil/meta/type_traits
  - abseil/container/hashtable_debug_hooks (1.20220623.0):
    - abseil/base/config
  - abseil/container/hashtablez_sampler (1.20220623.0):
    - abseil/base/base
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/debugging/stacktrace
    - abseil/memory/memory
    - abseil/profiling/exponential_biased
    - abseil/profiling/sample_recorder
    - abseil/synchronization/synchronization
    - abseil/utility/utility
  - abseil/container/inlined_vector (1.20220623.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/base/throw_delegate
    - abseil/container/inlined_vector_internal
    - abseil/memory/memory
  - abseil/container/inlined_vector_internal (1.20220623.0):
    - abseil/base/core_headers
    - abseil/container/compressed_tuple
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/types/span
  - abseil/container/layout (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/strings/strings
    - abseil/types/span
    - abseil/utility/utility
  - abseil/container/raw_hash_map (1.20220623.0):
    - abseil/base/throw_delegate
    - abseil/container/container_memory
    - abseil/container/raw_hash_set
  - abseil/container/raw_hash_set (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/base/prefetch
    - abseil/container/common
    - abseil/container/compressed_tuple
    - abseil/container/container_memory
    - abseil/container/hash_policy_traits
    - abseil/container/hashtable_debug_hooks
    - abseil/container/hashtablez_sampler
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/numeric/bits
    - abseil/utility/utility
  - abseil/debugging/debugging_internal (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/errno_saver
    - abseil/base/raw_logging_internal
  - abseil/debugging/demangle_internal (1.20220623.0):
    - abseil/base/base
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/debugging/stacktrace (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/debugging/debugging_internal
  - abseil/debugging/symbolize (1.20220623.0):
    - abseil/base/base
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/malloc_internal
    - abseil/base/raw_logging_internal
    - abseil/debugging/debugging_internal
    - abseil/debugging/demangle_internal
    - abseil/strings/strings
  - abseil/functional/any_invocable (1.20220623.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/utility/utility
  - abseil/functional/bind_front (1.20220623.0):
    - abseil/base/base_internal
    - abseil/container/compressed_tuple
    - abseil/meta/type_traits
    - abseil/utility/utility
  - abseil/functional/function_ref (1.20220623.0):
    - abseil/base/base_internal
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/hash/city (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
  - abseil/hash/hash (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/container/fixed_array
    - abseil/functional/function_ref
    - abseil/hash/city
    - abseil/hash/low_level_hash
    - abseil/meta/type_traits
    - abseil/numeric/int128
    - abseil/strings/strings
    - abseil/types/optional
    - abseil/types/variant
    - abseil/utility/utility
  - abseil/hash/low_level_hash (1.20220623.0):
    - abseil/base/config
    - abseil/base/endian
    - abseil/numeric/bits
    - abseil/numeric/int128
  - abseil/memory/memory (1.20220623.0):
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/meta/type_traits (1.20220623.0):
    - abseil/base/config
  - abseil/numeric/bits (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/numeric/int128 (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/numeric/bits
  - abseil/numeric/representation (1.20220623.0):
    - abseil/base/config
  - abseil/profiling/exponential_biased (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/profiling/sample_recorder (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/synchronization/synchronization
    - abseil/time/time
  - abseil/random/distributions (1.20220623.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/numeric/bits
    - abseil/random/internal/distribution_caller
    - abseil/random/internal/fast_uniform_bits
    - abseil/random/internal/fastmath
    - abseil/random/internal/generate_real
    - abseil/random/internal/iostream_state_saver
    - abseil/random/internal/traits
    - abseil/random/internal/uniform_helper
    - abseil/random/internal/wide_multiply
    - abseil/strings/strings
  - abseil/random/internal/distribution_caller (1.20220623.0):
    - abseil/base/config
    - abseil/base/fast_type_id
    - abseil/utility/utility
  - abseil/random/internal/fast_uniform_bits (1.20220623.0):
    - abseil/base/config
    - abseil/meta/type_traits
    - abseil/random/internal/traits
  - abseil/random/internal/fastmath (1.20220623.0):
    - abseil/numeric/bits
  - abseil/random/internal/generate_real (1.20220623.0):
    - abseil/meta/type_traits
    - abseil/numeric/bits
    - abseil/random/internal/fastmath
    - abseil/random/internal/traits
  - abseil/random/internal/iostream_state_saver (1.20220623.0):
    - abseil/meta/type_traits
    - abseil/numeric/int128
  - abseil/random/internal/nonsecure_base (1.20220623.0):
    - abseil/base/core_headers
    - abseil/container/inlined_vector
    - abseil/meta/type_traits
    - abseil/random/internal/pool_urbg
    - abseil/random/internal/salted_seed_seq
    - abseil/random/internal/seed_material
    - abseil/types/span
  - abseil/random/internal/pcg_engine (1.20220623.0):
    - abseil/base/config
    - abseil/meta/type_traits
    - abseil/numeric/bits
    - abseil/numeric/int128
    - abseil/random/internal/fastmath
    - abseil/random/internal/iostream_state_saver
  - abseil/random/internal/platform (1.20220623.0):
    - abseil/base/config
  - abseil/random/internal/pool_urbg (1.20220623.0):
    - abseil/base/base
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/base/raw_logging_internal
    - abseil/random/internal/randen
    - abseil/random/internal/seed_material
    - abseil/random/internal/traits
    - abseil/random/seed_gen_exception
    - abseil/types/span
  - abseil/random/internal/randen (1.20220623.0):
    - abseil/base/raw_logging_internal
    - abseil/random/internal/platform
    - abseil/random/internal/randen_hwaes
    - abseil/random/internal/randen_slow
  - abseil/random/internal/randen_engine (1.20220623.0):
    - abseil/base/endian
    - abseil/meta/type_traits
    - abseil/random/internal/iostream_state_saver
    - abseil/random/internal/randen
  - abseil/random/internal/randen_hwaes (1.20220623.0):
    - abseil/base/config
    - abseil/random/internal/platform
    - abseil/random/internal/randen_hwaes_impl
  - abseil/random/internal/randen_hwaes_impl (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/numeric/int128
    - abseil/random/internal/platform
  - abseil/random/internal/randen_slow (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/numeric/int128
    - abseil/random/internal/platform
  - abseil/random/internal/salted_seed_seq (1.20220623.0):
    - abseil/container/inlined_vector
    - abseil/meta/type_traits
    - abseil/random/internal/seed_material
    - abseil/types/optional
    - abseil/types/span
  - abseil/random/internal/seed_material (1.20220623.0):
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/raw_logging_internal
    - abseil/random/internal/fast_uniform_bits
    - abseil/strings/strings
    - abseil/types/optional
    - abseil/types/span
  - abseil/random/internal/traits (1.20220623.0):
    - abseil/base/config
    - abseil/numeric/bits
    - abseil/numeric/int128
  - abseil/random/internal/uniform_helper (1.20220623.0):
    - abseil/base/config
    - abseil/meta/type_traits
    - abseil/numeric/int128
    - abseil/random/internal/traits
  - abseil/random/internal/wide_multiply (1.20220623.0):
    - abseil/base/config
    - abseil/numeric/bits
    - abseil/numeric/int128
    - abseil/random/internal/traits
  - abseil/random/random (1.20220623.0):
    - abseil/random/distributions
    - abseil/random/internal/nonsecure_base
    - abseil/random/internal/pcg_engine
    - abseil/random/internal/pool_urbg
    - abseil/random/internal/randen_engine
    - abseil/random/seed_sequences
  - abseil/random/seed_gen_exception (1.20220623.0):
    - abseil/base/config
  - abseil/random/seed_sequences (1.20220623.0):
    - abseil/base/config
    - abseil/random/internal/pool_urbg
    - abseil/random/internal/salted_seed_seq
    - abseil/random/internal/seed_material
    - abseil/random/seed_gen_exception
    - abseil/types/span
  - abseil/status/status (1.20220623.0):
    - abseil/base/atomic_hook
    - abseil/base/core_headers
    - abseil/base/raw_logging_internal
    - abseil/base/strerror
    - abseil/container/inlined_vector
    - abseil/debugging/stacktrace
    - abseil/debugging/symbolize
    - abseil/functional/function_ref
    - abseil/strings/cord
    - abseil/strings/str_format
    - abseil/strings/strings
    - abseil/types/optional
  - abseil/status/statusor (1.20220623.0):
    - abseil/base/base
    - abseil/base/core_headers
    - abseil/base/raw_logging_internal
    - abseil/meta/type_traits
    - abseil/status/status
    - abseil/strings/strings
    - abseil/types/variant
    - abseil/utility/utility
  - abseil/strings/cord (1.20220623.0):
    - abseil/base/base
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/base/raw_logging_internal
    - abseil/container/fixed_array
    - abseil/container/inlined_vector
    - abseil/functional/function_ref
    - abseil/meta/type_traits
    - abseil/numeric/bits
    - abseil/strings/cord_internal
    - abseil/strings/cordz_functions
    - abseil/strings/cordz_info
    - abseil/strings/cordz_statistics
    - abseil/strings/cordz_update_scope
    - abseil/strings/cordz_update_tracker
    - abseil/strings/internal
    - abseil/strings/str_format
    - abseil/strings/strings
    - abseil/types/optional
    - abseil/types/span
  - abseil/strings/cord_internal (1.20220623.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/base/raw_logging_internal
    - abseil/base/throw_delegate
    - abseil/container/compressed_tuple
    - abseil/container/inlined_vector
    - abseil/container/layout
    - abseil/functional/function_ref
    - abseil/meta/type_traits
    - abseil/strings/strings
    - abseil/types/span
  - abseil/strings/cordz_functions (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/raw_logging_internal
    - abseil/profiling/exponential_biased
  - abseil/strings/cordz_handle (1.20220623.0):
    - abseil/base/base
    - abseil/base/config
    - abseil/base/raw_logging_internal
    - abseil/synchronization/synchronization
  - abseil/strings/cordz_info (1.20220623.0):
    - abseil/base/base
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/raw_logging_internal
    - abseil/container/inlined_vector
    - abseil/debugging/stacktrace
    - abseil/strings/cord_internal
    - abseil/strings/cordz_functions
    - abseil/strings/cordz_handle
    - abseil/strings/cordz_statistics
    - abseil/strings/cordz_update_tracker
    - abseil/synchronization/synchronization
    - abseil/types/span
  - abseil/strings/cordz_statistics (1.20220623.0):
    - abseil/base/config
    - abseil/strings/cordz_update_tracker
  - abseil/strings/cordz_update_scope (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/strings/cord_internal
    - abseil/strings/cordz_info
    - abseil/strings/cordz_update_tracker
  - abseil/strings/cordz_update_tracker (1.20220623.0):
    - abseil/base/config
  - abseil/strings/internal (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/base/raw_logging_internal
    - abseil/meta/type_traits
  - abseil/strings/str_format (1.20220623.0):
    - abseil/strings/str_format_internal
  - abseil/strings/str_format_internal (1.20220623.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/functional/function_ref
    - abseil/meta/type_traits
    - abseil/numeric/bits
    - abseil/numeric/int128
    - abseil/numeric/representation
    - abseil/strings/strings
    - abseil/types/optional
    - abseil/types/span
    - abseil/utility/utility
  - abseil/strings/strings (1.20220623.0):
    - abseil/base/base
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/base/raw_logging_internal
    - abseil/base/throw_delegate
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/numeric/bits
    - abseil/numeric/int128
    - abseil/strings/internal
  - abseil/synchronization/graphcycles_internal (1.20220623.0):
    - abseil/base/base
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/malloc_internal
    - abseil/base/raw_logging_internal
  - abseil/synchronization/kernel_timeout_internal (1.20220623.0):
    - abseil/base/core_headers
    - abseil/base/raw_logging_internal
    - abseil/time/time
  - abseil/synchronization/synchronization (1.20220623.0):
    - abseil/base/atomic_hook
    - abseil/base/base
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/malloc_internal
    - abseil/base/raw_logging_internal
    - abseil/debugging/stacktrace
    - abseil/debugging/symbolize
    - abseil/synchronization/graphcycles_internal
    - abseil/synchronization/kernel_timeout_internal
    - abseil/time/time
  - abseil/time/internal/cctz/civil_time (1.20220623.0):
    - abseil/base/config
  - abseil/time/internal/cctz/time_zone (1.20220623.0):
    - abseil/base/config
    - abseil/time/internal/cctz/civil_time
  - abseil/time/time (1.20220623.0):
    - abseil/base/base
    - abseil/base/core_headers
    - abseil/base/raw_logging_internal
    - abseil/numeric/int128
    - abseil/strings/strings
    - abseil/time/internal/cctz/civil_time
    - abseil/time/internal/cctz/time_zone
  - abseil/types/bad_optional_access (1.20220623.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/types/bad_variant_access (1.20220623.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/types/optional (1.20220623.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/types/bad_optional_access
    - abseil/utility/utility
  - abseil/types/span (1.20220623.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/base/throw_delegate
    - abseil/meta/type_traits
  - abseil/types/variant (1.20220623.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/types/bad_variant_access
    - abseil/utility/utility
  - abseil/utility/utility (1.20220623.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/meta/type_traits
  - Alamofire (4.9.1)
  - AlignedCollectionViewFlowLayout (1.1.2)
  - BlueCryptor (1.0.32)
  - BlueECC (1.2.5)
  - BlueRSA (1.0.200)
  - BoringSSL-GRPC (0.0.24):
    - BoringSSL-GRPC/Implementation (= 0.0.24)
    - BoringSSL-GRPC/Interface (= 0.0.24)
  - BoringSSL-GRPC/Implementation (0.0.24):
    - BoringSSL-GRPC/Interface (= 0.0.24)
  - BoringSSL-GRPC/Interface (0.0.24)
  - CocoaLumberjack/Core (3.8.2)
  - CocoaLumberjack/Swift (3.8.2):
    - CocoaLumberjack/Core
  - DZNEmptyDataSet (1.8.1)
  - Evergage (1.4.0)
  - FBAEMKit (16.3.1):
    - FBSDKCoreKit_Basics (= 16.3.1)
  - FBSDKCoreKit (16.3.1):
    - FBAEMKit (= 16.3.1)
    - FBSDKCoreKit_Basics (= 16.3.1)
  - FBSDKCoreKit_Basics (16.3.1)
  - FBSDKLoginKit (16.3.1):
    - FBSDKCoreKit (= 16.3.1)
  - Firebase/Core (10.19.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.19.0)
  - Firebase/CoreOnly (10.19.0):
    - FirebaseCore (= 10.19.0)
  - Firebase/Crashlytics (10.19.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.19.0)
  - Firebase/DynamicLinks (10.19.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 10.19.0)
  - Firebase/Performance (10.19.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 10.19.0)
  - Firebase/RemoteConfig (10.19.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 10.19.0)
  - FirebaseABTesting (10.19.0):
    - FirebaseCore (~> 10.0)
  - FirebaseAnalytics (10.19.0):
    - FirebaseAnalytics/AdIdSupport (= 10.19.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.19.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.19.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.19.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreExtension (10.19.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.19.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.19.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseDynamicLinks (10.19.0):
    - FirebaseCore (~> 10.0)
  - FirebaseInstallations (10.19.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebasePerformance (10.19.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseRemoteConfig (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/ISASwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseRemoteConfig (10.19.0):
    - FirebaseABTesting (~> 10.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - FirebaseSharedSwift (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseSessions (10.19.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.10)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - FirebaseSharedSwift (10.19.0)
  - GoogleAnalytics (3.21.0)
  - googleapis (0.0.1):
    - "!ProtoCompiler-gRPCPlugin (~> 1.0)"
    - googleapis/Messages (= 0.0.1)
    - googleapis/Services (= 0.0.1)
  - googleapis/Messages (0.0.1):
    - "!ProtoCompiler-gRPCPlugin (~> 1.0)"
    - Protobuf
  - googleapis/Services (0.0.1):
    - "!ProtoCompiler-gRPCPlugin (~> 1.0)"
    - googleapis/Messages
    - gRPC-ProtoRPC
  - GoogleAppMeasurement (10.19.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.19.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.19.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.19.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.19.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleDataTransport (9.3.0):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleTagManager (7.4.3):
    - FirebaseAnalytics (< 11.0, >= 9.0)
    - GoogleAnalytics (~> 3.21)
  - GoogleUtilities/AppDelegateSwizzler (7.12.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.12.0):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/ISASwizzler (7.12.0)
  - GoogleUtilities/Logger (7.12.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.12.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.12.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.12.0)"
  - GoogleUtilities/Reachability (7.12.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.12.0):
    - GoogleUtilities/Logger
  - gRPC-Core (1.49.0):
    - gRPC-Core/Implementation (= 1.49.0)
    - gRPC-Core/Interface (= 1.49.0)
  - gRPC-Core/Implementation (1.49.0):
    - abseil/base/base (= 1.20220623.0)
    - abseil/base/core_headers (= 1.20220623.0)
    - abseil/container/flat_hash_map (= 1.20220623.0)
    - abseil/container/flat_hash_set (= 1.20220623.0)
    - abseil/container/inlined_vector (= 1.20220623.0)
    - abseil/functional/any_invocable (= 1.20220623.0)
    - abseil/functional/bind_front (= 1.20220623.0)
    - abseil/functional/function_ref (= 1.20220623.0)
    - abseil/hash/hash (= 1.20220623.0)
    - abseil/memory/memory (= 1.20220623.0)
    - abseil/meta/type_traits (= 1.20220623.0)
    - abseil/random/random (= 1.20220623.0)
    - abseil/status/status (= 1.20220623.0)
    - abseil/status/statusor (= 1.20220623.0)
    - abseil/strings/cord (= 1.20220623.0)
    - abseil/strings/str_format (= 1.20220623.0)
    - abseil/strings/strings (= 1.20220623.0)
    - abseil/synchronization/synchronization (= 1.20220623.0)
    - abseil/time/time (= 1.20220623.0)
    - abseil/types/optional (= 1.20220623.0)
    - abseil/types/span (= 1.20220623.0)
    - abseil/types/variant (= 1.20220623.0)
    - abseil/utility/utility (= 1.20220623.0)
    - BoringSSL-GRPC (= 0.0.24)
    - gRPC-Core/Interface (= 1.49.0)
  - gRPC-Core/Interface (1.49.0)
  - gRPC-ProtoRPC (1.49.0):
    - gRPC-ProtoRPC/Legacy (= 1.49.0)
    - gRPC-ProtoRPC/Legacy-Header (= 1.49.0)
    - gRPC-ProtoRPC/Main (= 1.49.0)
  - gRPC-ProtoRPC/Legacy (1.49.0):
    - gRPC-ProtoRPC/Legacy-Header (= 1.49.0)
    - gRPC-ProtoRPC/Main (= 1.49.0)
    - gRPC-RxLibrary (= 1.49.0)
    - gRPC/GRPCCore (= 1.49.0)
    - Protobuf (~> 3.0)
  - gRPC-ProtoRPC/Legacy-Header (1.49.0)
  - gRPC-ProtoRPC/Main (1.49.0):
    - gRPC-ProtoRPC/Legacy-Header (= 1.49.0)
    - gRPC/Interface (= 1.49.0)
    - Protobuf (~> 3.0)
  - gRPC-RxLibrary (1.49.0):
    - gRPC-RxLibrary/Implementation (= 1.49.0)
    - gRPC-RxLibrary/Interface (= 1.49.0)
  - gRPC-RxLibrary/Implementation (1.49.0):
    - gRPC-RxLibrary/Interface
  - gRPC-RxLibrary/Interface (1.49.0)
  - gRPC/GRPCCore (1.49.0):
    - gRPC-Core (= 1.49.0)
    - gRPC-RxLibrary (= 1.49.0)
    - gRPC/Interface (= 1.49.0)
    - gRPC/Interface-Legacy (= 1.49.0)
  - gRPC/Interface (1.49.0):
    - gRPC/Interface-Legacy (= 1.49.0)
  - gRPC/Interface-Legacy (1.49.0):
    - gRPC-RxLibrary/Interface (= 1.49.0)
  - KituraContracts (1.2.1):
    - LoggerAPI (~> 1.7)
  - LoggerAPI (1.9.200):
    - Logging (~> 1.1)
  - Logging (1.4.0)
  - MBProgressHUD (1.2.0)
  - nanopb (2.30909.1):
    - nanopb/decode (= 2.30909.1)
    - nanopb/encode (= 2.30909.1)
  - nanopb/decode (2.30909.1)
  - nanopb/encode (2.30909.1)
  - pop (1.0.12)
  - PromiseKit (6.18.1):
    - PromiseKit/CorePromise (= 6.18.1)
    - PromiseKit/Foundation (= 6.18.1)
    - PromiseKit/UIKit (= 6.18.1)
  - PromiseKit/Alamofire (6.18.1):
    - Alamofire (~> 4.0)
    - PromiseKit/CorePromise
  - PromiseKit/CorePromise (6.18.1)
  - PromiseKit/Foundation (6.18.1):
    - PromiseKit/CorePromise
  - PromiseKit/UIKit (6.18.1):
    - PromiseKit/CorePromise
  - PromisesObjC (2.3.1)
  - PromisesSwift (2.3.1):
    - PromisesObjC (= 2.3.1)
  - Protobuf (3.25.1)
  - R.swift (6.1.0):
    - R.swift.Library (~> 5.3.0)
  - R.swift.Library (5.3.0)
  - SDWebImage (5.13.5):
    - SDWebImage/Core (= 5.13.5)
  - SDWebImage/Core (5.13.5)
  - Shimmer (1.0.2)
  - SwiftJWT (3.6.200):
    - BlueCryptor (~> 1.0)
    - BlueECC (~> 1.1)
    - BlueRSA (~> 1.0)
    - KituraContracts (~> 1.2)
    - LoggerAPI (~> 1.7)
  - SwiftLint (0.54.0)
  - SwiftRichString (3.7.2)
  - youtube-ios-player-helper (1.0.4)

DEPENDENCIES:
  - Alamofire
  - AlignedCollectionViewFlowLayout
  - CocoaLumberjack/Swift
  - DZNEmptyDataSet
  - Evergage
  - FBSDKCoreKit
  - FBSDKLoginKit
  - Firebase/Core
  - Firebase/Crashlytics
  - Firebase/DynamicLinks
  - Firebase/Performance
  - Firebase/RemoteConfig
  - googleapis (from `.`)
  - GoogleTagManager
  - MBProgressHUD
  - pop
  - PromiseKit
  - PromiseKit/Alamofire
  - R.swift (~> 6.1.0)
  - SDWebImage (~> 5.13.5)
  - Shimmer
  - SwiftJWT
  - SwiftLint
  - SwiftRichString
  - youtube-ios-player-helper (~> 1.0.4)

SPEC REPOS:
  trunk:
    - "!ProtoCompiler"
    - "!ProtoCompiler-gRPCPlugin"
    - abseil
    - Alamofire
    - AlignedCollectionViewFlowLayout
    - BlueCryptor
    - BlueECC
    - BlueRSA
    - BoringSSL-GRPC
    - CocoaLumberjack
    - DZNEmptyDataSet
    - Evergage
    - FBAEMKit
    - FBSDKCoreKit
    - FBSDKCoreKit_Basics
    - FBSDKLoginKit
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseDynamicLinks
    - FirebaseInstallations
    - FirebasePerformance
    - FirebaseRemoteConfig
    - FirebaseSessions
    - FirebaseSharedSwift
    - GoogleAnalytics
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleTagManager
    - GoogleUtilities
    - gRPC
    - gRPC-Core
    - gRPC-ProtoRPC
    - gRPC-RxLibrary
    - KituraContracts
    - LoggerAPI
    - Logging
    - MBProgressHUD
    - nanopb
    - pop
    - PromiseKit
    - PromisesObjC
    - PromisesSwift
    - Protobuf
    - R.swift
    - R.swift.Library
    - SDWebImage
    - Shimmer
    - SwiftJWT
    - SwiftLint
    - SwiftRichString
    - youtube-ios-player-helper

EXTERNAL SOURCES:
  googleapis:
    :path: "."

SPEC CHECKSUMS:
  "!ProtoCompiler": e9c09244955a8565817aa59a4787b6bb849a63c6
  "!ProtoCompiler-gRPCPlugin": 755f0ee414a0d5f0028e0dcfe98c23bdbc3e6fa3
  abseil: 926fb7a82dc6d2b8e1f2ed7f3a718bce691d1e46
  Alamofire: 85e8a02c69d6020a0d734f6054870d7ecb75cf18
  AlignedCollectionViewFlowLayout: ee2ef451e741ec08f8e0967d828001e2f051c20a
  BlueCryptor: b0aee3d9b8f367b49b30de11cda90e1735571c24
  BlueECC: 0d18e93347d3ec6d41416de21c1ffa4d4cd3c2cc
  BlueRSA: dfeef51db96bcc4edec654956c1581adbda4e6a3
  BoringSSL-GRPC: 3175b25143e648463a56daeaaa499c6cb86dad33
  CocoaLumberjack: f8d89a516e7710fdb2e9b8f1560b16ec6040eef0
  DZNEmptyDataSet: 9525833b9e68ac21c30253e1d3d7076cc828eaa7
  Evergage: cfc0243b769c07fce5ccc4562505ae5f299c8749
  FBAEMKit: 6c7b5eb77c96861bb59e040842c6e55bf39512ce
  FBSDKCoreKit: 5e4dd478947ab1bcc887e8cfadeae0727af1a942
  FBSDKCoreKit_Basics: cd7b5f5d1e8868c26706917919d058999ca672c3
  FBSDKLoginKit: 572cca0bc6c90067ef197187697cb3b584310c52
  Firebase: 63ce8ece0d43743dc28eacac0c6867a2d7fd5a9d
  FirebaseABTesting: bfa3b384b68cee10a89183649c64cd7998a37a12
  FirebaseAnalytics: 87513010b13b7c8610164d3602ea10571f76afc1
  FirebaseCore: dc5c7badf99d47613c52b2e3a57a64cd187f8554
  FirebaseCoreExtension: c08d14c7b22e07994e876d837e6f58642f340087
  FirebaseCoreInternal: b444828ea7cfd594fca83046b95db98a2be4f290
  FirebaseCrashlytics: a4d2ad12f5c07ec8ee0ebc89133a45498a293ba6
  FirebaseDynamicLinks: bd0455c62de367bb46605692af35e423fd7b3b69
  FirebaseInstallations: 033d199474164db20c8350736842a94fe717b960
  FirebasePerformance: 634a9b06effc436c991273d90053a2086dd2d427
  FirebaseRemoteConfig: a7fcc7a5941faa7e09248e91c8797340aa4c85f6
  FirebaseSessions: e5f4caa188dc8bc6142abc974355be75b042215e
  FirebaseSharedSwift: f34eeb7d3ea87a34497629b6ca41657beadef76a
  GoogleAnalytics: abbea91ce20faea66c5b2305aa040d3f9992f66a
  googleapis: aca6318130c96d3f627ec57af5eb3c9f1dbcf963
  GoogleAppMeasurement: 68afe759316673c6554dac35a0c7ae8f5d6cb4ed
  GoogleDataTransport: 57c22343ab29bc686febbf7cbb13bad167c2d8fe
  GoogleTagManager: 3ac8bb08455a95f446c8006a562c58a132c202f5
  GoogleUtilities: 0759d1a57ebb953965c2dfe0ba4c82e95ccc2e34
  gRPC: 64f36d689b2ecd99c4351f74e6f91347cdc65d9f
  gRPC-Core: 3a9fdb5967d42211e875826f3f6fc163ea02c2a1
  gRPC-ProtoRPC: 1c223e0f1732bb8d0b9e9e0ea60cc0fe995b8e2d
  gRPC-RxLibrary: 92327f150e11cf3b1c0f52e083944fd9f5cb5d1e
  KituraContracts: e845e60dc8627ad0a76fa55ef20a45451d8f830b
  LoggerAPI: ad9c4a6f1e32f518fdb43a1347ac14d765ab5e3d
  Logging: beeb016c9c80cf77042d62e83495816847ef108b
  MBProgressHUD: 3ee5efcc380f6a79a7cc9b363dd669c5e1ae7406
  nanopb: d4d75c12cd1316f4a64e3c6963f879ecd4b5e0d5
  pop: d582054913807fd11fd50bfe6a539d91c7e1a55a
  PromiseKit: 49d70c53d5d20e346beaea4b276b5dd2ab446bb4
  PromisesObjC: c50d2056b5253dadbd6c2bea79b0674bd5a52fa4
  PromisesSwift: 28dca69a9c40779916ac2d6985a0192a5cb4a265
  Protobuf: d94761c33f1239c0a43a0817ca1a5f7f7c900241
  R.swift: ec98ff71c4ab2f6fd01dd077e5afd15e63a4834c
  R.swift.Library: 0fc583cb55a99e28901299cc451614cad1161962
  SDWebImage: 23d714cd599354ee7906dbae26dff89b421c4370
  Shimmer: c5374be1c2b0c9e292fb05b339a513cf291cac86
  SwiftJWT: 88c412708f58c169d431d344c87bc79a87c830ae
  SwiftLint: c1de071d9d08c8aba837545f6254315bc900e211
  SwiftRichString: d61b807db1f8834c26fee92b6dd3e1be2dc5af03
  youtube-ios-player-helper: e9b97535e816db3152179d84d999bc1807ecd689

PODFILE CHECKSUM: 1f15bd6baf371eeb346557a40c88ecb03eb60068

COCOAPODS: 1.14.3


```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @DancingWind. I tried to reproduce the issue by setting the `FirebaseAutomaticScreenReportingEnabled` flag to `NO`, but the automated screen_views were not showing in my logs. May I know if the issue is reproducible on your end when you tried not calling your event that manually logs your screen_view?

**Comment by rizafran** [comment]
@DancingWind, I also tried to disable calling the event that manually logs my screen_view, but the screen_view was not showing in my logs when `FirebaseAutomaticScreenReportingEnabled` is set to `NO`. Could you confirm if the issue only occurs in your banner? It would also be great if you could share a minimal reproducible app.

**Comment by DancingWind** [comment]
"App screen changed. Screen entry: xxx" logs appears for all VCs that we use. 
and then we do screen_view events manually for only those we care fore. there is a bunch of VC that we use for utility - no tracking code in them. But analytics statistics all VC appear with constantly spinning carousel banners being the top.

**Comment by morganchen12** [comment]
@DancingWind can you share the full app debug logs printed to console?

**Comment by DancingWind** [comment]
Hello,
Sorry - had a little christmas break.
Here is a slightly sanitized log with full analytics logging enabled
[appLog(full analytics debug).txt](https://github.com/firebase/firebase-ios-sdk/files/13829233/appLog.full.analytics.debug.txt)

**Comment by tsunghung** [comment]
The automatic screen reporting is disabled.
```
 - <AppMeasurement>[I-ACS036001] Analytics screen reporting is disabled. UIViewController transitions will not be logged.
```

Could you please help to do some tests? Please remove all
`Analytics.logEvent(AnalyticsEventScreenView, parameters: allParams)`
to see if there are any screen view events. Then add back the AnalyticsEventScreenView events incrementally to see which one results in unexpected screen view events.

**Comment by tsunghung** [comment]
```
App screen changed. Screen entry: Pigu_lt.TextCarouselTopBannerPage.
App screen changed. Screen entry: Pigu_lt.UspCarouselPage.
```
These log messages are not from Analytics SDK.

**Comment by marchy** [comment]
We're experiencing the same issue.

Not sure if it's related, but we use dynamic plist files per environment, so we have `GoogleService-Info-DEV`/`GoogleService-Info-STAGING'/`GoogleService-Info-PRODUCTION' etc.

We've tried setting both `FirebaseAutomaticScreenReportingEnabled` and `FIREBASE_AUTOMATIC_SCREEN_REPORTING_ENABLED` to `NO` in the respective plist file:
<img width="570" alt="Screenshot 2024-01-22 at 6 58 24 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/1369360/bbdee39b-2ac4-4532-a5e0-c794cf342008">
FEEDBACK: It is SUPER confusing and inconsistent that all the other settings use SCREAMING_CAPS while the screen reporting uses UpperCamel. You guys should fix this.

but still getting the following message in the logs:
`[FirebaseAnalytics][I-ACS023220] Analytics screen reporting is enabled. Call Analytics.logEvent(AnalyticsEventScreenView, parameters: [...]) to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist`

**Comment by kylemay-gridstone** [comment]
Any update on this?? I can still see:
```
11.3.0 - [FirebaseAnalytics][I-ACS023220] Analytics screen reporting is enabled. Call Analytics.logEvent(AnalyticsEventScreenView, parameters: [...]) to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
```
Despite having `FirebaseAutomaticScreenReportingEnabled` => `NO` in my `Info.plist`

**Comment by AzarouAmine** [comment]
Any updates on this? I'm also seeing events logged even tho `FirebaseAutomaticScreenReportingEnabled ` is set to `NO`.

**Comment by DancingWind** [comment]
Hi,
Not sure about entries in analytics backend but in app console I think these logs are from Facebook SDK :)

**Comment by rizafran** [comment]
Hi, I tried to set the `FirebaseAutomaticScreenReportingEnabled` to `NO` (using v11.3.0), but I'm not able to reproduce the issue. I'm wondering if you have tried to debug as mentioned in https://github.com/firebase/firebase-ios-sdk/issues/12188#issuecomment-1879345734?

**Comment by htcgh** [comment]
This Salesforce Stack Exchange [post](https://salesforce.stackexchange.com/questions/371029/marketing-cloud-push-sdk-ios-keychain-crash) led me to confirm that the `App screen changed. Screen entry` log messages are coming from the SFMCSDK (Salesforce Marketing Cloud SDK). I downloaded the SFMCSDK.xcframework from their GitHub and verified with the `strings` and `grep` commands that the message is indeed coming from the SFMCSDK binary.

**Comment by DanielZanchi** [comment]
Any update on this? We can't disable automatic tracking and this is flooding our BigQuery tables.

**Comment by htcgh** [comment]
Hi all. We're still not able to reproduce this issue. For those still encountering this, please try printing out the value with key "FirebaseAutomaticScreenReportingEnabled" from `Bundle.main.infoDictionary`, which would indicate that the value was added to the intended plist file. If the print statement gets skipped, then that could indicate that the value was added to the wrong plist file or the target's build settings (under Packaging > Info.plist File) aren't pointing to that same plist file.

```
if let screenReportingEnabled = Bundle.main.infoDictionary?["FirebaseAutomaticScreenReportingEnabled"] as? Bool {
  print("screenReportingEnabled is \(screenReportingEnabled)")
}
```
