### ISSUE TITLE
I am getting the nanopb related crashes on version 10.27.0.

### ISSUE THREAD

**Issue by Vikrant2411** [firebase/firebase-ios-sdk#13080]
### Description

Hi,
I am getting the nanopb related crashes on version 10.27.0.
Have anyone found any solution for this?
Please let me know because there are several crashes reported related nanopb.

Logs from Crashlytics:-

Crashed: com.apple.main-thread
0  nanopb                         0x6194 encode_field + 244
1  nanopb                         0x6074 pb_encode + 172
2  FirebaseSessions               0x413c FIRSESEncodeProto + 64
3  FirebaseSessions               0xf04c $s16FirebaseSessions17SessionStartEventC14transportBytes10Foundation4DataVyF + 232
4  FirebaseSessions               0xf2d4 $s16FirebaseSessions17SessionStartEventC14transportBytes10Foundation4DataVyFTo + 28
5  GoogleDataTransport            0x9e78 -[GDTCOREvent setDataObject:] + 68
6  FirebaseSessions               0x5e48 $s16FirebaseSessions14EventGDTLoggerC03logC05event10completionyAA012SessionStartC0C_ys6ResultOyyts5Error_pGctF + 104
7  FirebaseSessions               0x5f44 $s16FirebaseSessions14EventGDTLoggerCAA0cD8ProtocolA2aDP03logC05event10completionyAA012SessionStartC0C_ys6ResultOyyts5Error_pGctFTW + 20
8  FirebaseSessions               0xd1c4 $s16FirebaseSessions18SessionCoordinatorC014attemptLoggingC5Start5event8callbackyAA0cG5EventC_ys6ResultOyytAA0aB5ErrorOGctFyAMcfU_ + 176
9  FirebaseSessions               0xd3c4 $s16FirebaseSessions18SessionCoordinatorC10fillInFIID33_A99E81F187A7BA47A5374F4DC053A423LL5event8callbackyAA0C10StartEventC_ys6ResultOyytAA0aB5ErrorOGctFyAKySSs0V0_pGcfU_ + 180
10 FirebaseSessions               0xabe4 $sSo16FIRInstallationsC16FirebaseSessionsE14installationID10completionyys6ResultOySSs5Error_pGc_tFySSSg_sAH_pSgtcfU_TA + 48
11 FirebaseSessions               0xaaa8 $sSSSgs5Error_pSgIeggg_So8NSStringCSgSo7NSErrorCSgIeyByy_TR + 96
12 FirebaseInstallations          0x49bc __49-[FIRInstallations installationIDWithCompletion:]_block_invoke + 56
13 FBLPromises                    0x5130 __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.18 + 52
14 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
15 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
16 libdispatch.dylib              0x125ec _dispatch_main_queue_drain + 1060
17 libdispatch.dylib              0x121b8 _dispatch_main_queue_callback_4CF + 44
18 CoreFoundation                 0x3751c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
19 CoreFoundation                 0x34218 __CFRunLoopRun + 1996
20 CoreFoundation                 0x33968 CFRunLoopRunSpecific + 608
21 GraphicsServices               0x34e0 GSEventRunModal + 164
22 UIKitCore                      0x22aedc -[UIApplication _run] + 888
23 UIKitCore                      0x22a518 UIApplicationMain + 340
24 Al Ain Water                   0xde240 main + 25 (AppDelegate.swift:25)
25 ???                            0x1b23b6d84 (Missing)

### Reproducing the issue

On opening the app when FirebaseApp.configure() called. We are getting this crash.

So, basically when we download app from AppStore or TestFlight and if we have app installed on our device and is in terminating state. When we are opening app, it is crashing immediately. 

### Firebase SDK Version

10.27.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, DynamicLinks, Messaging

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Crashed: com.apple.main-thread
0  nanopb                         0x6194 encode_field + 244
1  nanopb                         0x6074 pb_encode + 172
2  FirebaseSessions               0x413c FIRSESEncodeProto + 64
3  FirebaseSessions               0xf04c $s16FirebaseSessions17SessionStartEventC14transportBytes10Foundation4DataVyF + 232
4  FirebaseSessions               0xf2d4 $s16FirebaseSessions17SessionStartEventC14transportBytes10Foundation4DataVyFTo + 28
5  GoogleDataTransport            0x9e78 -[GDTCOREvent setDataObject:] + 68
6  FirebaseSessions               0x5e48 $s16FirebaseSessions14EventGDTLoggerC03logC05event10completionyAA012SessionStartC0C_ys6ResultOyyts5Error_pGctF + 104
7  FirebaseSessions               0x5f44 $s16FirebaseSessions14EventGDTLoggerCAA0cD8ProtocolA2aDP03logC05event10completionyAA012SessionStartC0C_ys6ResultOyyts5Error_pGctFTW + 20
8  FirebaseSessions               0xd1c4 $s16FirebaseSessions18SessionCoordinatorC014attemptLoggingC5Start5event8callbackyAA0cG5EventC_ys6ResultOyytAA0aB5ErrorOGctFyAMcfU_ + 176
9  FirebaseSessions               0xd3c4 $s16FirebaseSessions18SessionCoordinatorC10fillInFIID33_A99E81F187A7BA47A5374F4DC053A423LL5event8callbackyAA0C10StartEventC_ys6ResultOyytAA0aB5ErrorOGctFyAKySSs0V0_pGcfU_ + 180
10 FirebaseSessions               0xabe4 $sSo16FIRInstallationsC16FirebaseSessionsE14installationID10completionyys6ResultOySSs5Error_pGc_tFySSSg_sAH_pSgtcfU_TA + 48
11 FirebaseSessions               0xaaa8 $sSSSgs5Error_pSgIeggg_So8NSStringCSgSo7NSErrorCSgIeyByy_TR + 96
12 FirebaseInstallations          0x49bc __49-[FIRInstallations installationIDWithCompletion:]_block_invoke + 56
13 FBLPromises                    0x5130 __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.18 + 52
14 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
15 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
16 libdispatch.dylib              0x125ec _dispatch_main_queue_drain + 1060
17 libdispatch.dylib              0x121b8 _dispatch_main_queue_callback_4CF + 44
18 CoreFoundation                 0x3751c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
19 CoreFoundation                 0x34218 __CFRunLoopRun + 1996
20 CoreFoundation                 0x33968 CFRunLoopRunSpecific + 608
21 GraphicsServices               0x34e0 GSEventRunModal + 164
22 UIKitCore                      0x22aedc -[UIApplication _run] + 888
23 UIKitCore                      0x22a518 UIApplicationMain + 340
24 Al Ain Water                   0xde240 main + 25 (AppDelegate.swift:25)
25 ???                            0x1b23b6d84 (Missing)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

PODS:
  - Adjust (4.38.3):
    - Adjust/Core (= 4.38.3)
  - Adjust/Core (4.38.3)
  - Alamofire (4.9.1)
  - cybersource-ios-sdk (1.0.3)
  - FBAEMKit (17.0.1):
    - FBSDKCoreKit_Basics (= 17.0.1)
  - FBSDKCoreKit (17.0.1):
    - FBAEMKit (= 17.0.1)
    - FBSDKCoreKit_Basics (= 17.0.1)
  - FBSDKCoreKit_Basics (17.0.1)
  - FBSDKLoginKit (17.0.1):
    - FBSDKCoreKit (= 17.0.1)
  - FBSDKShareKit (17.0.1):
    - FBSDKCoreKit (= 17.0.1)
  - Firebase/Analytics (10.25.0):
    - Firebase/Core
  - Firebase/Core (10.25.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.25.0)
  - Firebase/CoreOnly (10.25.0):
    - FirebaseCore (= 10.25.0)
  - Firebase/Crashlytics (10.25.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.25.0)
  - Firebase/DynamicLinks (10.25.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 10.25.0)
  - Firebase/Messaging (10.25.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 10.25.0)
  - FirebaseAnalytics (10.25.0):
    - FirebaseAnalytics/AdIdSupport (= 10.25.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.25.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.25.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseCore (10.25.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreExtension (10.25.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.25.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.25.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseRemoteConfigInterop (~> 10.23)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseDynamicLinks (10.25.0):
    - FirebaseCore (~> 10.0)
  - FirebaseInstallations (10.25.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (10.25.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Reachability (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseRemoteConfigInterop (10.25.0)
  - FirebaseSessions (10.25.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.13)
    - GoogleUtilities/UserDefaults (~> 7.13)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - FSCalendar (2.8.4)
  - Google-Maps-iOS-Utils (4.2.2):
    - Google-Maps-iOS-Utils/Clustering (= 4.2.2)
    - Google-Maps-iOS-Utils/Geometry (= 4.2.2)
    - Google-Maps-iOS-Utils/GeometryUtils (= 4.2.2)
    - Google-Maps-iOS-Utils/Heatmap (= 4.2.2)
    - Google-Maps-iOS-Utils/QuadTree (= 4.2.2)
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/Clustering (4.2.2):
    - Google-Maps-iOS-Utils/QuadTree
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/Geometry (4.2.2):
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/GeometryUtils (4.2.2):
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/Heatmap (4.2.2):
    - Google-Maps-iOS-Utils/QuadTree
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/QuadTree (4.2.2):
    - GoogleMaps (~> 7.3)
  - GoogleAnalytics (3.23.0):
    - GoogleUtilities/UserDefaults (~> 7.11)
  - GoogleAppMeasurement (10.25.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.25.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.25.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.25.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.25.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleDataTransport (9.4.1):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleMaps (7.4.0):
    - GoogleMaps/Maps (= 7.4.0)
  - GoogleMaps/Base (7.4.0)
  - GoogleMaps/Maps (7.4.0):
    - GoogleMaps/Base
  - GooglePlaces (7.4.0)
  - GoogleTagManager (7.4.6):
    - FirebaseAnalytics (< 12.0, >= 10.0)
    - GoogleAnalytics (~> 3.23)
  - GoogleUtilities/AppDelegateSwizzler (7.13.3):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (7.13.3):
    - GoogleUtilities/Privacy
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.13.3):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/MethodSwizzler (7.13.3):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (7.13.3):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.13.3)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (7.13.3)
  - GoogleUtilities/Reachability (7.13.3):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/UserDefaults (7.13.3):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - IQKeyboardManagerSwift (7.0.3)
  - JVFloatLabeledTextField (1.2.2)
  - KAPinField (5.0.3)
  - KWVerificationCodeView (0.5.0)
  - MMPlayerView (5.1.3)
  - mss-ios-gems (1.6):
    - Alamofire (~> 4.9.1)
    - IQKeyboardManagerSwift
  - nanopb (2.30910.0):
    - nanopb/decode (= 2.30910.0)
    - nanopb/encode (= 2.30910.0)
  - nanopb/decode (2.30910.0)
  - nanopb/encode (2.30910.0)
  - NISdk (5.1.7)
  - PayFortSDK (3.2.0)
  - PromisesObjC (2.4.0)
  - PromisesSwift (2.4.0):
    - PromisesObjC (= 2.4.0)
  - SDWebImage (5.19.2):
    - SDWebImage/Core (= 5.19.2)
  - SDWebImage/Core (5.19.2)
  - Siren (6.1.3)
  - surveymonkey-ios-sdk (2.1.1)
  - SwiftMessages (6.0.2):
    - SwiftMessages/App (= 6.0.2)
  - SwiftMessages/App (6.0.2)
  - TKFormTextField (0.3.1)

DEPENDENCIES:
  - Adjust
  - cybersource-ios-sdk
  - FBSDKCoreKit
  - FBSDKLoginKit
  - FBSDKShareKit
  - Firebase/Analytics
  - Firebase/Crashlytics
  - Firebase/DynamicLinks
  - Firebase/Messaging
  - FSCalendar
  - Google-Maps-iOS-Utils
  - GoogleMaps
  - GooglePlaces
  - GoogleTagManager
  - JVFloatLabeledTextField
  - KAPinField
  - KWVerificationCodeView
  - MMPlayerView (= 5.1.3)
  - mss-ios-gems (from `http://125.20.90.241/kashishverma/mss-ios-gems.git`, tag `1.14`)
  - NISdk
  - PayFortSDK
  - SDWebImage
  - Siren
  - surveymonkey-ios-sdk
  - SwiftMessages (= 6.0.2)
  - TKFormTextField

SPEC REPOS:
  trunk:
    - Adjust
    - Alamofire
    - cybersource-ios-sdk
    - FBAEMKit
    - FBSDKCoreKit
    - FBSDKCoreKit_Basics
    - FBSDKLoginKit
    - FBSDKShareKit
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseDynamicLinks
    - FirebaseInstallations
    - FirebaseMessaging
    - FirebaseRemoteConfigInterop
    - FirebaseSessions
    - FSCalendar
    - Google-Maps-iOS-Utils
    - GoogleAnalytics
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleMaps
    - GooglePlaces
    - GoogleTagManager
    - GoogleUtilities
    - IQKeyboardManagerSwift
    - JVFloatLabeledTextField
    - KAPinField
    - KWVerificationCodeView
    - MMPlayerView
    - nanopb
    - NISdk
    - PayFortSDK
    - PromisesObjC
    - PromisesSwift
    - SDWebImage
    - Siren
    - surveymonkey-ios-sdk
    - SwiftMessages
    - TKFormTextField

EXTERNAL SOURCES:
  mss-ios-gems:
    :git: http://125.20.90.241/kashishverma/mss-ios-gems.git
    :tag: '1.14'

CHECKOUT OPTIONS:
  mss-ios-gems:
    :git: http://125.20.90.241/kashishverma/mss-ios-gems.git
    :tag: '1.14'

SPEC CHECKSUMS:
  Adjust: f446e1a51f7f07ef1c2d0267e079d5a83aed21bb
  Alamofire: 85e8a02c69d6020a0d734f6054870d7ecb75cf18
  cybersource-ios-sdk: 4ce002abfe52d7d6ff126f9edcf0d585aa261b29
  FBAEMKit: 97eaf41451b49691447df831f7f425229ae64b66
  FBSDKCoreKit: e34084567d11cfdd4787ace2b1a0255bedf34ade
  FBSDKCoreKit_Basics: 3d78e5fe00504e5c1aed1c48de0654c3a1565d15
  FBSDKLoginKit: 9a581053879a1e6fc3fab8ead341c78c6a318255
  FBSDKShareKit: c3b14e2aa947fc6dc8d3ccdd52bfe5ddc88049cf
  Firebase: 0312a2352584f782ea56f66d91606891d4607f06
  FirebaseAnalytics: ec00fe8b93b41dc6fe4a28784b8e51da0647a248
  FirebaseCore: 7ec4d0484817f12c3373955bc87762d96842d483
  FirebaseCoreExtension: 8a47811d0b155501559ef05d089518152a0a1677
  FirebaseCoreInternal: 910a81992c33715fec9263ca7381d59ab3a750b7
  FirebaseCrashlytics: 4b96efb0ce73b38b2a85e8b8bd1bd8f63f09d015
  FirebaseDynamicLinks: 12c9f5b643943e0565ed28080373f89cbcb914a3
  FirebaseInstallations: 91950fe859846fff0fbd296180909dd273103b09
  FirebaseMessaging: 88950ba9485052891ebe26f6c43a52bb62248952
  FirebaseRemoteConfigInterop: b25018791b204c0d78a90e394d6c62d9b1f22da8
  FirebaseSessions: c0939656253a1fa0e94ecc266ccf770cc8b33732
  FSCalendar: 2d1d0d9398f12d439f55c1fe0f01525b151b8260
  Google-Maps-iOS-Utils: f77eab4c4326d7e6a277f8e23a0232402731913a
  GoogleAnalytics: 9e360c5cfffa536ff64dc383bc468577b7ba5c5d
  GoogleAppMeasurement: 9abf64b682732fed36da827aa2a68f0221fd2356
  GoogleDataTransport: 6c09b596d841063d76d4288cc2d2f42cc36e1e2a
  GoogleMaps: 032f676450ba0779bd8ce16840690915f84e57ac
  GooglePlaces: 544e908d94860bf6f8fc1865b80d2c7eb6b5f937
  GoogleTagManager: 9ef072dc46718db4b2ef5b801a32a6946efbaafb
  GoogleUtilities: ea963c370a38a8069cc5f7ba4ca849a60b6d7d15
  IQKeyboardManagerSwift: f9c5dc36cba16ddd2e51fa7d51c34a2e083029b5
  JVFloatLabeledTextField: df48598472ee015701d509f43e59492a0d4ca208
  KAPinField: 7a57b50c49263e74d295b1819cda1d869205e212
  KWVerificationCodeView: 19ea2579877cc4937f5ee16d0e205d487bdb247d
  MMPlayerView: b5ff60e0f70b73866eb20fda3098e525f5f25793
  mss-ios-gems: 1fdcbed24733c72c3ffd10adab980cab68dd09ff
  nanopb: 438bc412db1928dac798aa6fd75726007be04262
  NISdk: b0ca021999cc777257f9381f2f897f12ad16fb16
  PayFortSDK: 92d7df56734bd520241250ebc9b93987782b33b9
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47
  PromisesSwift: 9d77319bbe72ebf6d872900551f7eeba9bce2851
  SDWebImage: dfe95b2466a9823cf9f0c6d01217c06550d7b29a
  Siren: c0f6012f61196b73455202db07730f6454a4beb0
  surveymonkey-ios-sdk: 1a718943e27b4a8f34834063f5697c0774afc4ce
  SwiftMessages: 8b3cc68dba2f1c91aac1a74c90b10287aac35371
  TKFormTextField: def6294d3d3bd944d864ee48d5cc6e36863d6ade

PODFILE CHECKSUM: 7bea22af9dd47652a25c2fa363446b9a2cdf18ea

COCOAPODS: 1.15.2

**Comment by paulb777** [comment]
Since this issue was addressed in 10.22.0, your report indicates 10.27.0 and the Podfile.lock indicates 10.25.0 - there is likely a configuration problem.

We'll likely need a fully reproducible example to help.

**Comment by Vikrant2411** [comment]
Sorry I have updated the Podfile.lock after that which I think installed 10.25.0. 
Below I have attached the Podfile.lock which gave me the crashes and logs them in Firebase Crashlytics.

`PODS:
  - Adjust (4.38.3):
    - Adjust/Core (= 4.38.3)
  - Adjust/Core (4.38.3)
  - Alamofire (4.9.1)
  - cybersource-ios-sdk (1.0.3)
  - FBAEMKit (17.0.2):
    - FBSDKCoreKit_Basics (= 17.0.2)
  - FBSDKCoreKit (17.0.2):
    - FBAEMKit (= 17.0.2)
    - FBSDKCoreKit_Basics (= 17.0.2)
  - FBSDKCoreKit_Basics (17.0.2)
  - FBSDKLoginKit (17.0.2):
    - FBSDKCoreKit (= 17.0.2)
  - FBSDKShareKit (17.0.2):
    - FBSDKCoreKit (= 17.0.2)
  - Firebase/Analytics (10.27.0):
    - Firebase/Core
  - Firebase/Core (10.27.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.27.0)
  - Firebase/CoreOnly (10.27.0):
    - FirebaseCore (= 10.27.0)
  - Firebase/Crashlytics (10.27.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.27.0)
  - Firebase/DynamicLinks (10.27.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 10.27.0)
  - Firebase/Messaging (10.27.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 10.27.0)
  - FirebaseAnalytics (10.27.0):
    - FirebaseAnalytics/AdIdSupport (= 10.27.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.27.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.27.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseCore (10.27.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreExtension (10.27.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.27.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.27.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseRemoteConfigInterop (~> 10.23)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseDynamicLinks (10.27.0):
    - FirebaseCore (~> 10.0)
  - FirebaseInstallations (10.27.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (10.27.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Reachability (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseRemoteConfigInterop (10.27.0)
  - FirebaseSessions (10.27.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.13)
    - GoogleUtilities/UserDefaults (~> 7.13)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - FSCalendar (2.8.4)
  - Google-Maps-iOS-Utils (4.2.2):
    - Google-Maps-iOS-Utils/Clustering (= 4.2.2)
    - Google-Maps-iOS-Utils/Geometry (= 4.2.2)
    - Google-Maps-iOS-Utils/GeometryUtils (= 4.2.2)
    - Google-Maps-iOS-Utils/Heatmap (= 4.2.2)
    - Google-Maps-iOS-Utils/QuadTree (= 4.2.2)
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/Clustering (4.2.2):
    - Google-Maps-iOS-Utils/QuadTree
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/Geometry (4.2.2):
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/GeometryUtils (4.2.2):
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/Heatmap (4.2.2):
    - Google-Maps-iOS-Utils/QuadTree
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/QuadTree (4.2.2):
    - GoogleMaps (~> 7.3)
  - GoogleAnalytics (3.23.0):
    - GoogleUtilities/UserDefaults (~> 7.11)
  - GoogleAppMeasurement (10.27.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.27.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.27.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.27.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.27.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleDataTransport (9.4.1):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleMaps (7.4.0):
    - GoogleMaps/Maps (= 7.4.0)
  - GoogleMaps/Base (7.4.0)
  - GoogleMaps/Maps (7.4.0):
    - GoogleMaps/Base
  - GooglePlaces (7.4.0)
  - GoogleTagManager (7.4.6):
    - FirebaseAnalytics (< 12.0, >= 10.0)
    - GoogleAnalytics (~> 3.23)
  - GoogleUtilities/AppDelegateSwizzler (7.13.3):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (7.13.3):
    - GoogleUtilities/Privacy
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.13.3):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/MethodSwizzler (7.13.3):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (7.13.3):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.13.3)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (7.13.3)
  - GoogleUtilities/Reachability (7.13.3):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/UserDefaults (7.13.3):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - IQKeyboardManagerSwift (7.0.3)
  - JVFloatLabeledTextField (1.2.2)
  - KAPinField (5.0.3)
  - KWVerificationCodeView (0.5.0)
  - MMPlayerView (5.1.3)
  - mss-ios-gems (1.6):
    - Alamofire (~> 4.9.1)
    - IQKeyboardManagerSwift
  - nanopb (2.30910.0):
    - nanopb/decode (= 2.30910.0)
    - nanopb/encode (= 2.30910.0)
  - nanopb/decode (2.30910.0)
  - nanopb/encode (2.30910.0)
  - NISdk (5.1.7)
  - PayFortSDK (3.2.0)
  - PromisesObjC (2.4.0)
  - PromisesSwift (2.4.0):
    - PromisesObjC (= 2.4.0)
  - SDWebImage (5.19.2):
    - SDWebImage/Core (= 5.19.2)
  - SDWebImage/Core (5.19.2)
  - Siren (6.1.3)
  - surveymonkey-ios-sdk (2.1.1)
  - SwiftMessages (6.0.2):
    - SwiftMessages/App (= 6.0.2)
  - SwiftMessages/App (6.0.2)
  - TKFormTextField (0.3.1)

DEPENDENCIES:
  - Adjust
  - cybersource-ios-sdk
  - FBSDKCoreKit
  - FBSDKLoginKit
  - FBSDKShareKit
  - Firebase/Analytics
  - Firebase/Crashlytics
  - Firebase/DynamicLinks
  - Firebase/Messaging
  - FSCalendar
  - Google-Maps-iOS-Utils
  - GoogleMaps
  - GooglePlaces
  - GoogleTagManager
  - JVFloatLabeledTextField
  - KAPinField
  - KWVerificationCodeView
  - MMPlayerView (= 5.1.3)
  - mss-ios-gems (from `http://125.20.90.241/kashishverma/mss-ios-gems.git`, tag `1.14`)
  - NISdk
  - PayFortSDK
  - SDWebImage
  - Siren
  - surveymonkey-ios-sdk
  - SwiftMessages (= 6.0.2)
  - TKFormTextField

SPEC REPOS:
  trunk:
    - Adjust
    - Alamofire
    - cybersource-ios-sdk
    - FBAEMKit
    - FBSDKCoreKit
    - FBSDKCoreKit_Basics
    - FBSDKLoginKit
    - FBSDKShareKit
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseDynamicLinks
    - FirebaseInstallations
    - FirebaseMessaging
    - FirebaseRemoteConfigInterop
    - FirebaseSessions
    - FSCalendar
    - Google-Maps-iOS-Utils
    - GoogleAnalytics
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleMaps
    - GooglePlaces
    - GoogleTagManager
    - GoogleUtilities
    - IQKeyboardManagerSwift
    - JVFloatLabeledTextField
    - KAPinField
    - KWVerificationCodeView
    - MMPlayerView
    - nanopb
    - NISdk
    - PayFortSDK
    - PromisesObjC
    - PromisesSwift
    - SDWebImage
    - Siren
    - surveymonkey-ios-sdk
    - SwiftMessages
    - TKFormTextField

EXTERNAL SOURCES:
  mss-ios-gems:
    :git: http://125.20.90.241/kashishverma/mss-ios-gems.git
    :tag: '1.14'

CHECKOUT OPTIONS:
  mss-ios-gems:
    :git: http://125.20.90.241/kashishverma/mss-ios-gems.git
    :tag: '1.14'

SPEC CHECKSUMS:
  Adjust: f446e1a51f7f07ef1c2d0267e079d5a83aed21bb
  Alamofire: 85e8a02c69d6020a0d734f6054870d7ecb75cf18
  cybersource-ios-sdk: 4ce002abfe52d7d6ff126f9edcf0d585aa261b29
  FBAEMKit: 619f96ea65427e8afca240d5b0f4703738dfdf5c
  FBSDKCoreKit: a5f384db2e9ee84e98494fed8f983d2bd79accff
  FBSDKCoreKit_Basics: d35c775aaf243a2d731dfae7be3a74b1987285ab
  FBSDKLoginKit: f8ca5f7ab7c4e5b93e729d94975b0db7fcc511ed
  FBSDKShareKit: e7ec3bed8e82dabc04e56f3cf44ef99a1864309e
  Firebase: 26b040b20866a55f55eb3611b9fcf3ae64816b86
  FirebaseAnalytics: f9211b719db260cc91aebee8bb539cb367d0dfd1
  FirebaseCore: a2b95ae4ce7c83ceecfbbbe3b6f1cddc7415a808
  FirebaseCoreExtension: 4ec89dd0c6de93d6becde32122d68b7c35f6bf5d
  FirebaseCoreInternal: 4b297a2d56063dbea2c1d0d04222d44a8d058862
  FirebaseCrashlytics: 81ea6ec96519388687f6061beb838a8eec482293
  FirebaseDynamicLinks: 087bf18ffabe8b6abe0c80301fd16ba2225ce373
  FirebaseInstallations: 766dabca09fd94aef922538aaf144cc4a6fb6869
  FirebaseMessaging: 585984d0a1df120617eb10b44cad8968b859815e
  FirebaseRemoteConfigInterop: c55a739f5ab121792776e191d9fd437dc624a541
  FirebaseSessions: 2fdf949f9e58295a57703ae8f2efc44f9fa3aa16
  FSCalendar: 2d1d0d9398f12d439f55c1fe0f01525b151b8260
  Google-Maps-iOS-Utils: f77eab4c4326d7e6a277f8e23a0232402731913a
  GoogleAnalytics: 9e360c5cfffa536ff64dc383bc468577b7ba5c5d
  GoogleAppMeasurement: f65fc137531af9ad647f1c0a42f3b6a4d3a98049
  GoogleDataTransport: 6c09b596d841063d76d4288cc2d2f42cc36e1e2a
  GoogleMaps: 032f676450ba0779bd8ce16840690915f84e57ac
  GooglePlaces: 544e908d94860bf6f8fc1865b80d2c7eb6b5f937
  GoogleTagManager: 9ef072dc46718db4b2ef5b801a32a6946efbaafb
  GoogleUtilities: ea963c370a38a8069cc5f7ba4ca849a60b6d7d15
  IQKeyboardManagerSwift: f9c5dc36cba16ddd2e51fa7d51c34a2e083029b5
  JVFloatLabeledTextField: df48598472ee015701d509f43e59492a0d4ca208
  KAPinField: 7a57b50c49263e74d295b1819cda1d869205e212
  KWVerificationCodeView: 19ea2579877cc4937f5ee16d0e205d487bdb247d
  MMPlayerView: b5ff60e0f70b73866eb20fda3098e525f5f25793
  mss-ios-gems: 1fdcbed24733c72c3ffd10adab980cab68dd09ff
  nanopb: 438bc412db1928dac798aa6fd75726007be04262
  NISdk: b0ca021999cc777257f9381f2f897f12ad16fb16
  PayFortSDK: 92d7df56734bd520241250ebc9b93987782b33b9
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47
  PromisesSwift: 9d77319bbe72ebf6d872900551f7eeba9bce2851
  SDWebImage: dfe95b2466a9823cf9f0c6d01217c06550d7b29a
  Siren: c0f6012f61196b73455202db07730f6454a4beb0
  surveymonkey-ios-sdk: 1a718943e27b4a8f34834063f5697c0774afc4ce
  SwiftMessages: 8b3cc68dba2f1c91aac1a74c90b10287aac35371
  TKFormTextField: def6294d3d3bd944d864ee48d5cc6e36863d6ade

PODFILE CHECKSUM: 7bea22af9dd47652a25c2fa363446b9a2cdf18ea

COCOAPODS: 1.15.2
`

**Comment by paulb777** [comment]
Does building for the Debug configuration instead of the Release configuration make a difference?

**Comment by fousa** [comment]
We are having the exact same issue with `10.27.0`. We can't reproduce the issue in Debug at this moment. We are integrating Firebase through SPM.

[trace.txt](https://github.com/user-attachments/files/15806369/trace.txt)

**Comment by Vikrant2411** [comment]
Hi Paul,
After removing Firebase and adding it again through Cocoapods, now there are no crashes. But i am confirming here after adding pods again installed 10.25.0 in which it is working fine now.
But i think 10.27.0 still have these issues.  

Thanks for your help.

**Comment by paulb777** [comment]
Closing. Please open a new issue with the template completed if it re-occurs
