### ISSUE TITLE
Occasionally crashes when starting the app

### ISSUE THREAD

**Issue by zhangbokika** [firebase/firebase-ios-sdk#13843]
### Description

# Occasionally crashes when starting the app

### Firebase SDK Version

17.6.1 18.0

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
# Crashlytics - Stack trace
# Application: xxx
# Platform: apple
# Version: 4.9.3
# Issue: 13e07f0782e5a707fe366c8d3d96727b
# Session: e40b2b89f70c49f48f2f93ae71b15fea_DNE_0_v2
# Date: Tue Oct 08 2024 07:30:03 GMT+0800

Fatal Exception: NSGenericException
0  CoreFoundation                 0x83f20 __exceptionPreprocess
1  libobjc.A.dylib                0x172b8 objc_exception_throw
2  CFNetwork                      0xc7e48 CFHostCreateWithName
3  FirebasePerformance            0x18050 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke + 312 (FPRNSURLSessionInstrument.m:312)
4  FirebasePerformance            0x18050 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke + 312 (FPRNSURLSessionInstrument.m:312)
5 our app                               0x159ca7c NotificationService.sendNotification(urlString:key:attempt:)
6  our app                           0x159e548 closure #1 in NotificationService.sendStoredTpats()
7  our app                            0x15c6034 closure #1 in Persistence.readStoredTpats(callback:)
8  our app                             0x2d0308 thunk for @escaping @callee_guaranteed @Sendable () -> ()
9  libdispatch.dylib              0x213c _dispatch_call_block_and_release
10 libdispatch.dylib              0x3dd4 _dispatch_client_callout
11 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain
12 libdispatch.dylib              0xbf30 _dispatch_lane_invoke
13 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh
14 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread
15 libsystem_pthread.dylib        0x4934 _pthread_wqthread
16 libsystem_pthread.dylib        0x10cc start_wqthread
```

### If using CocoaPods, the project's Podfile.lock

- FirebaseAnalytics/AdIdSupport (10.29.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.29.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseAnalyticsOnDeviceConversion (9.6.0):
    - GoogleAppMeasurementOnDeviceConversion (= 9.6.0)
  - FirebaseAppCheckInterop (10.29.0)
  - FirebaseAuth (10.29.0):
    - FirebaseAppCheckInterop (~> 10.17)
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GTMSessionFetcher/Core (< 4.0, >= 2.1)
    - RecaptchaInterop (~> 100.0)
  - FirebaseCore (10.29.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreExtension (10.29.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.29.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.29.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseRemoteConfigInterop (~> 10.23)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseDatabase (10.29.0):
    - FirebaseAppCheckInterop (~> 10.17)
    - FirebaseCore (~> 10.0)
    - FirebaseSharedSwift (~> 10.0)
    - GoogleUtilities/UserDefaults (~> 7.13)
    - leveldb-library (~> 1.22)
  - FirebaseInstallations (10.29.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (10.29.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Reachability (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebasePerformance (10.29.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseRemoteConfig (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.13)
    - GoogleUtilities/ISASwizzler (~> 7.13)
    - GoogleUtilities/MethodSwizzler (~> 7.13)
    - GoogleUtilities/UserDefaults (~> 7.13)
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseRemoteConfig (10.29.0):
    - FirebaseABTesting (~> 10.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - FirebaseRemoteConfigInterop (~> 10.23)
    - FirebaseSharedSwift (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseRemoteConfigInterop (10.29.0)
  - FirebaseSessions (10.29.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.13)
    - GoogleUtilities/UserDefaults (~> 7.13)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - FirebaseSharedSwift (10.29.0)

**Comment by aybarska** [comment]
```
          Fatal Exception: NSGenericException
0  CoreFoundation                 0x83f20 __exceptionPreprocess
1  libobjc.A.dylib                0x172b8 objc_exception_throw
2  CFNetwork                      0xc7e48 CFHostCreateWithName
3  FirebasePerformance            0x1bfb0 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke + 311 (FPRNSURLSessionInstrument.m:311)
4  FirebasePerformance            0x1bfb0 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke + 311 (FPRNSURLSessionInstrument.m:311)
5  Mynet                          0x177b680 NotificationService.sendNotification(urlString:key:attempt:)
6  Mynet                          0x177d14c closure #1 in NotificationService.sendStoredTpats()
7  Mynet                          0x17a0c24 closure #1 in Persistence.readStoredTpats(callback:)
8  Mynet                          0x1c2af4 thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
9  libdispatch.dylib              0x213c _dispatch_call_block_and_release
10 libdispatch.dylib              0x3dd4 _dispatch_client_callout
11 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain
12 libdispatch.dylib              0xbf30 _dispatch_lane_invoke
13 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh
14 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread
15 libsystem_pthread.dylib        0x4934 _pthread_wqthread
16 libsystem_pthread.dylib        0x10cc start_wqthread
        
```

I have the same on xcode 16

**Comment by rizafran** [comment]
Hi @zhangbokika, could you provide the full stack trace of your crash?

**Comment by aybarska** [comment]
I have the same crash, archived with xcode 16. 
Attaching the stacktrace
[comxx.xx_issue_13e07f0782e5a707fe366c8d3d96727b_crash_session_c7c826dc36734419a5a410de501da15b_DNE_0_v2_stacktrace copy.txt](https://github.com/user-attachments/files/17307592/comxx.xx_issue_13e07f0782e5a707fe366c8d3d96727b_crash_session_c7c826dc36734419a5a410de501da15b_DNE_0_v2_stacktrace.copy.txt)

**Comment by zhangbokika** [comment]
@rizafran Thank you very much for your reply,  # Crashlytics - Stack trace
# Application: xxx
# Platform: apple
# Version: 4.9.3 (302071959)
# Issue: 13e07f0782e5a707fe366c8d3d96727b
# Session: e40b2b89f70c49f48f2f93ae71b15fea_DNE_0_v2
# Date: Tue Oct 08 2024 07:30:03 GMT+0800

Fatal Exception: NSGenericException
0  CoreFoundation                 0x83f20 __exceptionPreprocess
1  libobjc.A.dylib                0x172b8 objc_exception_throw
2  CFNetwork                      0xc7e48 CFHostCreateWithName
3  FirebasePerformance            0x18050 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke + 312 (FPRNSURLSessionInstrument.m:312)
4  FirebasePerformance            0x18050 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke + 312 (FPRNSURLSessionInstrument.m:312)
5  xx                           0x159ca7c NotificationService.sendNotification(urlString:key:attempt:)
6  xx                           0x159e548 closure #1 in NotificationService.sendStoredTpats()
7  xx                           0x15c6034 closure #1 in Persistence.readStoredTpats(callback:)
8  xx                           0x2d0308 thunk for @escaping @callee_guaranteed @Sendable () -> ()
9  libdispatch.dylib              0x213c _dispatch_call_block_and_release
10 libdispatch.dylib              0x3dd4 _dispatch_client_callout
11 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain
12 libdispatch.dylib              0xbf30 _dispatch_lane_invoke
13 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh
14 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread
15 libsystem_pthread.dylib        0x4934 _pthread_wqthread
16 libsystem_pthread.dylib        0x10cc start_wqthread

ConfigurationStorage.sync.queue
0  libobjc.A.dylib                0x3c1c objc_msgSend + 28
1  Foundation                     0x35aa4 -[NSString _stringRepresentation] + 400
2  CoreFoundation                 0x48db8 -[NSDictionary descriptionWithLocale:indent:] + 1096
3  CoreFoundation                 0x486bc -[NSArray descriptionWithLocale:indent:] + 436
4  CoreFoundation                 0x48de0 -[NSDictionary descriptionWithLocale:indent:] + 1136
5  Foundation                     0x119508 protocol witness for CustomStringConvertible.description.getter in conformance NSObject + 32
6  libswiftCore.dylib             0xd903c _debugPrint_unlocked<A, B>(_:_:) + 352
7  libswiftCore.dylib             0x19ff6c specialized _debugPrint<A>(_:separator:terminator:to:) + 180
8  libswiftCore.dylib             0xbfdd8 Dictionary.description.getter + 1100
9  libswiftCore.dylib             0xd869c _print_unlocked<A, B>(_:_:) + 1104
10 xx                           0x1184200 specialized closure #2 in Loggable.getDescription(for:at:) + 4347642368
11 xx                           0x1183b20 specialized Loggable.getDescription(for:at:) + 4347640608
12 xx                           0x1184994 protocol witness for Loggable.logDescription.getter in conformance LegacySDKConfig + 4347644308
13 libswiftCore.dylib             0xd8750 _print_unlocked<A, B>(_:_:) + 1284
14 xx                           0x1219a80 SDKConfigurationFileStorage.loadLocalConfig() + 4348254848
15 xx                           0x121c668 protocol witness for UnityAdsConfigurationProvider.config.getter in conformance SDKConfigurationFileStorage + 4348266088
16 xx                           0x121d164 closure #1 in SDKConfigurationInMemoryStorage.config.getter + 4348268900
17 xx                           0x1221218 partial apply for closure #1 in SDKConfigurationInMemoryStorage.config.getter + 4348285464
18 libswiftDispatch.dylib         0x328c partial apply for thunk for @callee_guaranteed () -> (@out A, @error @owned Error) + 28
19 libswiftDispatch.dylib         0x3268 thunk for @callee_guaranteed () -> (@out A, @error @owned Error)partial apply + 16
20 libswiftDispatch.dylib         0x31a8 closure #1 in closure #1 in OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 192
21 libswiftDispatch.dylib         0x30cc partial apply for thunk for @callee_guaranteed () -> () + 28
22 libswiftDispatch.dylib         0x30a4 thunk for @escaping @callee_guaranteed () -> () + 28
23 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
24 libdispatch.dylib              0x132c4 _dispatch_lane_barrier_sync_invoke_and_complete + 56
25 libswiftDispatch.dylib         0x496c implicit closure #2 in implicit closure #1 in OS_dispatch_queue.asyncAndWait<A>(execute:) + 192
26 libswiftDispatch.dylib         0x48a4 partial apply for implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 76
27 libswiftDispatch.dylib         0x4724 OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 404
28 libswiftDispatch.dylib         0x4560 OS_dispatch_queue.asyncAndWait<A>(execute:) + 140
29 libswiftDispatch.dylib         0x44cc OS_dispatch_queue.sync<A>(execute:) + 64
30 xx                           0x121e7ec protocol witness for UnityAdsConfigurationProvider.config.getter in conformance SDKConfigurationInMemoryStorage + 4348274668
31 xx                           0x1227d08 SDKStateStorage.webViewConfig.getter + 4348312840
32 xx                           0x12286fc protocol witness for WebViewConfigurationProvider.webViewConfig.getter in conformance SDKStateStorage + 4348315388
33 xx                           0x1261400 UnityAdsNetworkServicesFactory.unityAdsDownloader.getter + 4348548096
34 xx                           0x12610c0 UnityAdsNetworkServicesFactory.webViewDownloaderBuilder.getter + 4348547264
35 xx                           0x11c005c InitMainTaskProviderBase.initTaskFactory.getter + 4347887708
36 xx                           0x11bfd88 InitMainTaskProviderBase.task(with:) + 4347886984
37 xx                           0x11c07b0 protocol witness for InitMainTaskProvider.task(with:) in conformance InitMainTaskProviderBase + 4347889584
38 xx                           0x12233bc SDKInitializerBase.changeStatusAndStartTheTask(config:) + 4348294076
39 xx                           0x1222b74 SDKInitializerBase.startInitialization(with:completion:) + 4348291956
40 xx                           0x12238f8 partial apply for closure #1 in SDKInitializerBase.initialize(with:completion:) + 4348295416
41 xx                           0x112cb20 thunk for @callee_guaranteed () -> () + 4347284256
42 xx                           0x112cb40 thunk for @escaping @callee_guaranteed () -> () + 4347284288
43 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
44 libdispatch.dylib              0x132c4 _dispatch_lane_barrier_sync_invoke_and_complete + 56
45 xx                           0x1222904 SDKInitializerBase.initialize(with:completion:) + 4348291332
46 xx                           0x122306c protocol witness for SDKInitializer.initialize(with:completion:) in conformance SDKInitializerBase + 4348293228
47 xx                           0x1227190 SDKInitializerWithMetrics.initialize(with:completion:) + 4348309904
48 xx                           0x1227240 protocol witness for SDKInitializer.initialize(with:completion:) in conformance SDKInitializerWithMetrics + 4348310080
49 xx                           0x122660c @objc SDKInitializerOBJBridge.initialize(gameID:testMode:completion:error:) + 4348306956
50 CoreFoundation                 0x20814 __invoking___ + 148
51 CoreFoundation                 0x1f860 -[NSInvocation invoke] + 428
52 xx                           0x10c44bc +[NSInvocation(Category) uads_invokeUsingMethod:classType:target:args:] + 4346856636
53 xx                           0x10f22cc -[UADSProxyReflection callInstanceMethod:args:] + 4347044556
54 xx                           0x10f3a78 -[UADSSDKInitializerProxy initializeWithGameID:testMode:completion:error:] + 4347050616
55 xx                           0x1128500 +[UnityServices legacyPath:testMode:delegate:] + 4347266304
56 xx                           0x1128394 +[UnityServices initialize:testMode:initializationDelegate:] + 4347265940
57 xx                           0x12507ac @objc static UnityAds.initialize(_:testMode:initializationDelegate:) + 4348479404
58 xx                           0x3706cc -[ALUnityAdsMediationAdapter initializeWithParameters:completionHandler:] + 4332881612
59 AppLovinSDK                    0x178f54 __93-[ALMediationAdapterWrapper initializeWithAdapterInitializationParameters:completionHandler:]_block_invoke + 144
60 AppLovinSDK                    0x17be68 __67-[ALMediationAdapterWrapper runOperationWithTag:forAdFormat:block:]_block_invoke + 152
61 Foundation                     0x1c8c0 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
62 Foundation                     0x1c780 -[NSBlockOperation main] + 104
63 Foundation                     0x1c580 __NSOPERATION_IS_INVOKING_MAIN__ + 16
64 Foundation                     0x1a820 -[NSOperation start] + 648
65 Foundation                     0x9f268 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 16
66 Foundation                     0x9eeb4 __NSOQSchedule_f + 172
67 libdispatch.dylib              0x12e5c _dispatch_block_async_invoke2 + 148
68 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
69 libdispatch.dylib              0x125a4 _dispatch_main_queue_drain + 988
70 libdispatch.dylib              0x121b8 _dispatch_main_queue_callback_4CF + 44
71 CoreFoundation                 0x56710 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
72 CoreFoundation                 0x53914 __CFRunLoopRun + 1996
73 CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
74 GraphicsServices               0x11a8 GSEventRunModal + 164
75 UIKitCore                      0x40aae8 -[UIApplication _run] + 888
76 UIKitCore                      0x4bed98 UIApplicationMain + 340
77 xx                           0x25f50c main + 15 (main.m:15)
78 ???                            0x1b947f154 (Missing)

Crashed: com.google.firebase.crashlytics.ios.exception
0  FirebaseCrashlytics            0x21bac FIRCLSProcessRecordAllThreads + 392 (FIRCLSProcess.c:392)
1  FirebaseCrashlytics            0x21f8c FIRCLSProcessRecordAllThreads + 423 (FIRCLSProcess.c:423)
2  FirebaseCrashlytics            0x18e1c FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  FirebaseCrashlytics            0x13a20 __FIRCLSExceptionRecord_block_invoke + 240 (FIRCLSException.mm:240)
4  libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
5  libdispatch.dylib              0x132c4 _dispatch_lane_barrier_sync_invoke_and_complete + 56
6  FirebaseCrashlytics            0x129c8 FIRCLSExceptionRecord + 242 (FIRCLSException.mm:242)
7  FirebaseCrashlytics            0x134e4 FIRCLSExceptionRecordNSException + 126 (FIRCLSException.mm:126)
8  FirebaseCrashlytics            0x125d0 FIRCLSTerminateHandler() + 407 (FIRCLSException.mm:407)
9  libc++abi.dylib                0x14068 std::__terminate(void (*)()) + 16
10 libc++abi.dylib                0x1400c std::terminate() + 108
11 libobjc.A.dylib                0x3f81c objc::DenseMapBase<objc::DenseMap<objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >, objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >::FatalCorruptHashTables(objc::detail::DenseMapPair<objc_class*, PendingInitialize*> const*, unsigned int) const + 14
12 libdispatch.dylib              0x3de8 _dispatch_client_callout + 40
13 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
14 libdispatch.dylib              0xbf30 _dispatch_lane_invoke + 380
15 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
16 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
17 libsystem_pthread.dylib        0x4934 _pthread_wqthread + 288
18 libsystem_pthread.dylib        0x10cc start_wqthread + 8

startSDK
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7b5c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7a30 -[NSRunLoop(NSRunLoop) run] + 64
9  xxx                           0x1053374 __25-[MTGLogQueue setupTimer]_block_invoke + 4346393460
10 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
12 libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke + 928
13 libdispatch.dylib              0x15894 _dispatch_root_queue_drain + 392
14 libdispatch.dylib              0x1609c _dispatch_worker_thread2 + 156
15 libsystem_pthread.dylib        0x48f8 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.apple.root.default-qos
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7b5c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7a30 -[NSRunLoop(NSRunLoop) run] + 64
9  xx                           0x1053374 __25-[MTGLogQueue setupTimer]_block_invoke + 4346393460
10 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
12 libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke + 928
13 libdispatch.dylib              0x15894 _dispatch_root_queue_drain + 392
14 libdispatch.dylib              0x1609c _dispatch_worker_thread2 + 156
15 libsystem_pthread.dylib        0x48f8 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.google.GDTCORFlatFileStorage
0  libsystem_kernel.dylib          0x713c __getattrlist + 8
1  libsystem_kernel.dylib          0x713c getattrlist + 8
2  libsystem_coreservices.dylib    0x1714 ministatfs + 160
3  libsystem_coreservices.dylib    0x142c _dirhelper_relative_internal + 348
4  Foundation                      0x126840 -[NSFileManager _URLForReplacingItemAtURL:error:] + 152
5  Foundation                      0x1f038 _NSCreateTemporaryFile_Protected + 168
6  Foundation                      0x20758 _NSWriteDataToFileWithExtendedAttributes + 436
7  GoogleDataTransport             0x10d0c __71-[GDTCORFlatFileStorage libraryDataForKey:onFetchComplete:setNewValue:]_block_invoke + 331 (GDTCORFlatFileStorage.m:331)
8  libdispatch.dylib               0x213c _dispatch_call_block_and_release + 32
9  libdispatch.dylib               0x3dd4 _dispatch_client_callout + 20
10 libdispatch.dylib               0xb400 _dispatch_lane_serial_drain + 748
11 libdispatch.dylib               0xbf30 _dispatch_lane_invoke + 380
12 libdispatch.dylib               0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
13 libdispatch.dylib               0x16528 _dispatch_workloop_worker_thread + 404
14 libsystem_pthread.dylib         0x4934 _pthread_wqthread + 288
15 libsystem_pthread.dylib         0x10cc start_wqthread + 8

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7b5c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc79ac -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x41e81c -[UIEventFetcher threadMain] + 420
10 Foundation                     0xde428 __NSThread__start__ + 732
11 libsystem_pthread.dylib        0x606c _pthread_start + 136
12 libsystem_pthread.dylib        0x10d8 thread_start + 8

com.apple.root.default-qos
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7b5c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7a30 -[NSRunLoop(NSRunLoop) run] + 64
9  xx                           0x1053374 __25-[MTGLogQueue setupTimer]_block_invoke + 4346393460
10 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
12 libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke + 928
13 libdispatch.dylib              0x15894 _dispatch_root_queue_drain + 392
14 libdispatch.dylib              0x1609c _dispatch_worker_thread2 + 156
15 libsystem_pthread.dylib        0x48f8 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1450 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1450 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1450 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.apple.root.default-qos
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7b5c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7a30 -[NSRunLoop(NSRunLoop) run] + 64
9  xx                           0xf0c1b4 __40-[MTGLogQueueManager startTimerIfNeeded]_block_invoke + 4345053620
10 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
12 libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke + 928
13 libdispatch.dylib              0x15894 _dispatch_root_queue_drain + 392
14 libdispatch.dylib              0x1609c _dispatch_worker_thread2 + 156
15 libsystem_pthread.dylib        0x48f8 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0x10c4 start_wqthread + 8362545346

com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  FirebaseCrashlytics            0x1b564 FIRCLSMachExceptionServer + 192 (FIRCLSMachException.c:192)
5  libsystem_pthread.dylib        0x606c _pthread_start + 136
6  libsystem_pthread.dylib        0x10d8 thread_start + 8

com.apple.root.default-qos
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  Foundation                     0xbeedc -[NSOperation waitUntilFinished] + 508
3  CoreFoundation                 0x4fbf8 _CFXNotificationPost + 792
4  Foundation                     0x31254 -[NSNotificationCenter postNotificationName:object:userInfo:] + 92
5  xx                           0x817c94 __40-[ATVungleBaseManager initSDKWithAppID:]_block_invoke_2 + 4337761428
6  xx                           0x151e830 closure #2 in static VungleAds.initWithAppId(_:completion:) + 4351420464
7  xx                           0x15647fc closure #1 in closure #1 in DeviceInfo.updateWebViewUserAgent(completion:) + 4351707132
8  xx                           0x2d0308 thunk for @escaping @callee_guaranteed @Sendable () -> () + 4332225288
9  libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
10 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
11 libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke + 928
12 libdispatch.dylib              0x15894 _dispatch_root_queue_drain + 392
13 libdispatch.dylib              0x1609c _dispatch_worker_thread2 + 156
14 libsystem_pthread.dylib        0x48f8 _pthread_wqthread + 228
15 libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  CFNetwork                      0xfdc7c _CFHostIsDomainTopLevel + 108176
8  Foundation                     0xde428 __NSThread__start__ + 732
9  libsystem_pthread.dylib        0x606c _pthread_start + 136
10 libsystem_pthread.dylib        0x10d8 thread_start + 8

JavaScriptCore libpas scavenger
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  JavaScriptCore                 0x15671e0 scavenger_thread_main + 1316
3  libsystem_pthread.dylib        0x606c _pthread_start + 136
4  libsystem_pthread.dylib        0x10d8 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1450 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

extension-process-background-queue
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  libdispatch.dylib              0x1eb18 _dispatch_mach_send_and_wait_for_reply + 544
5  libdispatch.dylib              0x1eeb8 dispatch_mach_send_with_result_and_wait_for_reply + 60
6  libxpc.dylib                   0x10ac8 xpc_connection_send_message_with_reply_sync + 264
7  Foundation                     0x666a8 __NSXPCCONNECTION_IS_WAITING_FOR_A_SYNCHRONOUS_REPLY__ + 16
8  Foundation                     0x62d14 -[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:] + 2160
9  Foundation                     0xdaf1c -[NSXPCConnection _sendSelector:withProxy:arg1:] + 116
10 Foundation                     0xdab90 _NSXPCDistantObjectSimpleMessageSend1 + 60
11 CoreServices                   0x2daf8 __75+[LSBundleRecord _bundleRecordForAuditToken:checkNSBundleMainBundle:error:]_block_invoke_3 + 264
12 CoreServices                   0x2d1d4 _LSRetryForConnectionInterrupted + 56
13 CoreServices                   0x382ac +[LSBundleRecord _bundleRecordForAuditToken:checkNSBundleMainBundle:error:] + 648
14 CoreServices                   0x37dc0 +[LSBundleRecord bundleRecordForAuditToken:error:] + 40
15 ExtensionFoundation            0x16420 -[_EXDefaults defaultSandboxProfileName] + 2800
16 ExtensionFoundation            0x13848 -[_EXExtensionIdentity _init] + 732
17 ExtensionFoundation            0x101c8 -[EXConcreteExtension _plugIn] + 10820
18 ExtensionFoundation            0xfbf0 -[EXConcreteExtension _plugIn] + 9324
19 ExtensionFoundation            0xf460 -[EXConcreteExtension _plugIn] + 7388
20 ExtensionFoundation            0xf2b8 -[EXConcreteExtension _plugIn] + 6964
21 ExtensionFoundation            0xf260 -[EXConcreteExtension _plugIn] + 6876
22 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
23 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
24 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
25 libdispatch.dylib              0xbf30 _dispatch_lane_invoke + 380
26 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
27 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
28 libsystem_pthread.dylib        0x4934 _pthread_wqthread + 288
29 libsystem_pthread.dylib        0x10cc start_wqthread + 8

APAPIThread
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x3710 _pthread_cond_wait + 1272
2  Foundation                     0x7428c -[NSCondition waitUntilDate:] + 132
3  Foundation                     0x702dc -[NSConditionLock lockWhenCondition:beforeDate:] + 80
4  Singular                       0x1276c -[Queue newPullWithTimeout:] + 76
5  Singular                       0x29984 -[APAPIThread main] + 660
6  Foundation                     0xde428 __NSThread__start__ + 732
7  libsystem_pthread.dylib        0x606c _pthread_start + 136
8  libsystem_pthread.dylib        0x10d8 thread_start + 8

APEventThread
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x3710 _pthread_cond_wait + 1272
2  Foundation                     0x7428c -[NSCondition waitUntilDate:] + 132
3  Foundation                     0x702dc -[NSConditionLock lockWhenCondition:beforeDate:] + 80
4  Singular                       0x1276c -[Queue newPullWithTimeout:] + 76
5  Singular                       0x2849c -[APEventThread nextEvent:] + 112
6  Singular                       0x286b0 -[APEventThread waitForEvents] + 80
7  Singular                       0x2818c -[APEventThread main] + 104
8  Foundation                     0xde428 __NSThread__start__ + 732
9  libsystem_pthread.dylib        0x606c _pthread_start + 136
10 libsystem_pthread.dylib        0x10d8 thread_start + 8

trust
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  libdispatch.dylib              0x1eb18 _dispatch_mach_send_and_wait_for_reply + 544
5  libdispatch.dylib              0x1eeb8 dispatch_mach_send_with_result_and_wait_for_reply + 60
6  libxpc.dylib                   0x10ac8 xpc_connection_send_message_with_reply_sync + 264
7  Security                       0x20bf4 security_fw_send_message_with_reply_sync_inner + 92
8  Security                       0x20578 securityd_send_sync_and_do + 88
9  Security                       0x22f98 __SecTrustEvaluateIfNecessary_block_invoke_3 + 512
10 Security                       0x1e634 SecOSStatusWith + 56
11 Security                       0x32aac __SecTrustEvaluateIfNecessary_block_invoke_2 + 116
12 libsystem_trace.dylib          0x194c _os_activity_initiate_impl + 64
13 Security                       0x32f48 __SecTrustEvaluateIfNecessary_block_invoke + 292
14 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
15 libdispatch.dylib              0x132c4 _dispatch_lane_barrier_sync_invoke_and_complete + 56
16 Security                       0x11a0c SecTrustEvaluateIfNecessary + 236
17 Security                       0x2d4e4 SecTrustCopyCertificateChain + 60
18 CFNetwork                      0x95824 CFHostGetInfo + 56384
19 CFNetwork                      0x94dbc CFHostGetInfo + 53720
20 CFNetwork                      0x9391c CFHostGetInfo + 48440
21 CFNetwork                      0x19a6c _CFURLResponseCreateFromArchiveList + 36308
22 CFNetwork                      0xd39b8 CFHostCreateWithName + 154572
23 CFNetwork                      0xd05f0 CFHostCreateWithName + 141316
24 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
25 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
26 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
27 libdispatch.dylib              0xbf64 _dispatch_lane_invoke + 432
28 libdispatch.dylib              0xd284 _dispatch_workloop_invoke + 1756
29 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
30 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
31 libsystem_pthread.dylib        0x4934 _pthread_wqthread + 288
32 libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.apple.root.default-qos
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7b5c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7a30 -[NSRunLoop(NSRunLoop) run] + 64
9  xx                           0xf0c1b4 __40-[MTGLogQueueManager startTimerIfNeeded]_block_invoke + 4345053620
10 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
12 libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke + 928
13 libdispatch.dylib              0x15894 _dispatch_root_queue_drain + 392
14 libdispatch.dylib              0x1609c _dispatch_worker_thread2 + 156
15 libsystem_pthread.dylib        0x48f8 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1450 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.apple.root.default-qos
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7b5c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7a30 -[NSRunLoop(NSRunLoop) run] + 64
9  xx                           0x1053374 __25-[MTGLogQueue setupTimer]_block_invoke + 4346393460
10 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
12 libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke + 928
13 libdispatch.dylib              0x15894 _dispatch_root_queue_drain + 392
14 libdispatch.dylib              0x1609c _dispatch_worker_thread2 + 156
15 libsystem_pthread.dylib        0x48f8 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0x10c4 start_wqthread + 8362545346

Thread
0  libsystem_kernel.dylib         0x1450 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  CoreFoundation                 0xc0f04 CFRunLoopRun + 64
8  CoreMotion                     0xfe3c (Missing UUID 5d6e7429116638b3807bdfad246f9132)
9  libsystem_pthread.dylib        0x606c _pthread_start + 136
10 libsystem_pthread.dylib        0x10d8 thread_start + 8

**Comment by zhangbokika** [comment]
> I have the same crash, archived with xcode 16. Attaching the stacktrace [comxx.xx_issue_13e07f0782e5a707fe366c8d3d96727b_crash_session_c7c826dc36734419a5a410de501da15b_DNE_0_v2_stacktrace copy.txt](https://github.com/user-attachments/files/17307592/comxx.xx_issue_13e07f0782e5a707fe366c8d3d96727b_crash_session_c7c826dc36734419a5a410de501da15b_DNE_0_v2_stacktrace.copy.txt)
> 
> Podfile lock
> 
> ```
>   - Firebase/Core (11.3.0):
>     - Firebase/CoreOnly
>     - FirebaseAnalytics (~> 11.3.0)
>   - Firebase/CoreOnly (11.3.0):
>     - FirebaseCore (= 11.3.0)
>   - Firebase/Crashlytics (11.3.0):
>     - Firebase/CoreOnly
>     - FirebaseCrashlytics (~> 11.3.0)
>   - Firebase/InAppMessaging (11.3.0):
>     - Firebase/CoreOnly
>     - FirebaseInAppMessaging (~> 11.3.0-beta)
>   - Firebase/Messaging (11.3.0):
>     - Firebase/CoreOnly
>     - FirebaseMessaging (~> 11.3.0)
>   - Firebase/Performance (11.3.0):
>     - Firebase/CoreOnly
>     - FirebasePerformance (~> 11.3.0)
>   - Firebase/RemoteConfig (11.3.0):
>     - Firebase/CoreOnly
>     - FirebaseRemoteConfig (~> 11.3.0)
>   - FirebaseABTesting (11.3.0):
>     - FirebaseCore (~> 11.0)
>   - FirebaseAnalytics (11.3.0):
>     - FirebaseAnalytics/AdIdSupport (= 11.3.0)
>     - FirebaseCore (~> 11.0)
>     - FirebaseInstallations (~> 11.0)
>     - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
>     - GoogleUtilities/MethodSwizzler (~> 8.0)
>     - GoogleUtilities/Network (~> 8.0)
>     - "GoogleUtilities/NSData+zlib (~> 8.0)"
>     - nanopb (~> 3.30910.0)
>   - FirebaseAnalytics/AdIdSupport (11.3.0):
>     - FirebaseCore (~> 11.0)
>     - FirebaseInstallations (~> 11.0)
>     - GoogleAppMeasurement (= 11.3.0)
>     - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
>     - GoogleUtilities/MethodSwizzler (~> 8.0)
>     - GoogleUtilities/Network (~> 8.0)
>     - "GoogleUtilities/NSData+zlib (~> 8.0)"
>     - nanopb (~> 3.30910.0)
>   - FirebaseCore (11.3.0):
>     - FirebaseCoreInternal (~> 11.0)
>     - GoogleUtilities/Environment (~> 8.0)
>     - GoogleUtilities/Logger (~> 8.0)
>   - FirebaseCoreExtension (11.3.0):
>     - FirebaseCore (~> 11.0)
>   - FirebaseCoreInternal (11.3.0):
>     - "GoogleUtilities/NSData+zlib (~> 8.0)"
>   - FirebaseCrashlytics (11.3.0):
>     - FirebaseCore (~> 11.0)
>     - FirebaseInstallations (~> 11.0)
>     - FirebaseRemoteConfigInterop (~> 11.0)
>     - FirebaseSessions (~> 11.0)
>     - GoogleDataTransport (~> 10.0)
>     - GoogleUtilities/Environment (~> 8.0)
>     - nanopb (~> 3.30910.0)
>     - PromisesObjC (~> 2.4)
>   - FirebaseInAppMessaging (11.3.0-beta):
>     - FirebaseABTesting (~> 11.0)
>     - FirebaseCore (~> 11.0)
>     - FirebaseInstallations (~> 11.0)
>     - GoogleUtilities/Environment (~> 8.0)
>     - GoogleUtilities/UserDefaults (~> 8.0)
>     - nanopb (~> 3.30910.0)
>   - FirebaseInstallations (11.3.0):
>     - FirebaseCore (~> 11.0)
>     - GoogleUtilities/Environment (~> 8.0)
>     - GoogleUtilities/UserDefaults (~> 8.0)
>     - PromisesObjC (~> 2.4)
>   - FirebaseMessaging (11.3.0):
>     - FirebaseCore (~> 11.0)
>     - FirebaseInstallations (~> 11.0)
>     - GoogleDataTransport (~> 10.0)
>     - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
>     - GoogleUtilities/Environment (~> 8.0)
>     - GoogleUtilities/Reachability (~> 8.0)
>     - GoogleUtilities/UserDefaults (~> 8.0)
>     - nanopb (~> 3.30910.0)
>   - FirebasePerformance (11.3.0):
>     - FirebaseCore (~> 11.0)
>     - FirebaseInstallations (~> 11.0)
>     - FirebaseRemoteConfig (~> 11.0)
>     - FirebaseSessions (~> 11.0)
>     - GoogleDataTransport (~> 10.0)
>     - GoogleUtilities/Environment (~> 8.0)
>     - GoogleUtilities/MethodSwizzler (~> 8.0)
>     - GoogleUtilities/UserDefaults (~> 8.0)
>     - nanopb (~> 3.30910.0)
>   - FirebaseRemoteConfig (11.3.0):
>     - FirebaseABTesting (~> 11.0)
>     - FirebaseCore (~> 11.0)
>     - FirebaseInstallations (~> 11.0)
>     - FirebaseRemoteConfigInterop (~> 11.0)
>     - FirebaseSharedSwift (~> 11.0)
>     - GoogleUtilities/Environment (~> 8.0)
>     - "GoogleUtilities/NSData+zlib (~> 8.0)"
>   - FirebaseRemoteConfigInterop (11.3.0)
>   - FirebaseSessions (11.3.0):
>     - FirebaseCore (~> 11.0)
>     - FirebaseCoreExtension (~> 11.0)
>     - FirebaseInstallations (~> 11.0)
>     - GoogleDataTransport (~> 10.0)
>     - GoogleUtilities/Environment (~> 8.0)
>     - GoogleUtilities/UserDefaults (~> 8.0)
>     - nanopb (~> 3.30910.0)
>     - PromisesSwift (~> 2.1)
> ```

Have you solved the problem

**Comment by HyunjoonKo** [comment]
I have the same problem. Below is the stack trace of my app:
```
Fatal Exception: NSGenericException
Task created in a session that has been invalidated

0  CoreFoundation                 0xecb28 __exceptionPreprocess
1  libobjc.A.dylib                0x2af78 objc_exception_throw
2  CFNetwork                      0xf040 _CFNetworkSetHSTSStoragePath
3  Mubeat                         0x2d0ab90 NotificationService.sendNotification(urlString:key:attempt:)
4  Mubeat                         0x2d0c65c closure #1 in NotificationService.sendStoredTpats()
5  Mubeat                         0x2d34024 closure #1 in Persistence.readStoredTpats(callback:)
6  Mubeat                         0x13c5c14 thunk for @escaping @callee_guaranteed @Sendable () -> () (<compiler-generated>)
7  libdispatch.dylib              0x213c _dispatch_call_block_and_release
8  libdispatch.dylib              0x3dd4 _dispatch_client_callout
9  libdispatch.dylib              0xb400 _dispatch_lane_serial_drain
10 libdispatch.dylib              0xbf30 _dispatch_lane_invoke
11 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh
12 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread
13 libsystem_pthread.dylib        0x1f20 _pthread_wqthread
14 libsystem_pthread.dylib        0x1fc0 start_wqthread
```

```
          Crashed: com.google.firebase.crashlytics.ios.exception
0  FirebaseCrashlytics            0x361bc FIRCLSProcessGetThreadState + 308
1  FirebaseCrashlytics            0x35514 FIRCLSProcessRecordThread + 400
2  FirebaseCrashlytics            0x352a4 FIRCLSProcessRecordAllThreads + 172
3  FirebaseCrashlytics            0x25d90 FIRCLSHandler + 64
4  FirebaseCrashlytics            0x1c8f0 __FIRCLSExceptionRecord_block_invoke + 180
5  libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
6  libdispatch.dylib              0x132c4 _dispatch_lane_barrier_sync_invoke_and_complete + 56
7  FirebaseCrashlytics            0x1ab84 FIRCLSExceptionRecord + 360
8  FirebaseCrashlytics            0x1bf80 FIRCLSExceptionRecordNSException + 788
9  FirebaseCrashlytics            0x1cc50 FIRCLSCatchAndRecordActiveException(std::type_info*) + 208
10 FirebaseCrashlytics            0x1a6c8 FIRCLSTerminateHandler() + 320
11 libc++abi.dylib                0x14090 std::__terminate(void (*)()) + 16
12 libc++abi.dylib                0x14034 std::terminate() + 108
13 libobjc.A.dylib                0x3c88c objc_terminate + 16
14 libdispatch.dylib              0x3de8 _dispatch_client_callout + 40
15 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
16 libdispatch.dylib              0xbf30 _dispatch_lane_invoke + 380
17 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
18 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
19 libsystem_pthread.dylib        0x1f20 _pthread_wqthread + 288
20 libsystem_pthread.dylib        0x1fc0 start_wqthread + 8
```

**Comment by qinfendezhou** [comment]
I'm having the same problem with my project and don't know what to do about it

**Comment by zhangbokika** [comment]
![Uploading 截屏2024-10-15 15.58.51.png…]()
I caught a crash

**Comment by qinfendezhou** [comment]
### My crash log is as follows
# Application: our app
# Platform: apple
# Version: 1.2.4 (1.2.4.1)
# Issue: 13e07f0782e5a707fe366c8d3d96727b
# Session: 52c6e529f4a745f6b2c5d19ae2a62e03_DNE_0_v2
# Date: Wed Oct 16 2024 22:49:50 GMT+0800 (中国标准时间)

Fatal Exception: NSGenericException
0  CoreFoundation                 0x940c __exceptionPreprocess
1  libobjc.A.dylib                0x15c28 objc_exception_throw
2  CFNetwork                      0x23f98 CFURLRequestSetRequestPriority
3  our app        0x1029290 NotificationService.sendNotification(urlString:key:attempt:)
4  our app        0x102ad5c closure #1 in NotificationService.sendStoredTpats()
5  our app        0x1053c84 closure #1 in Persistence.readStoredTpats(callback:)
6  our app        0x246f58 thunk for @escaping @callee_guaranteed @Sendable () -> () (<compiler-generated>)
7  libdispatch.dylib              0x637a8 _dispatch_call_block_and_release
8  libdispatch.dylib              0x64780 _dispatch_client_callout
9  libdispatch.dylib              0x3f6fc _dispatch_lane_serial_drain$VARIANT$armv81
10 libdispatch.dylib              0x401b0 _dispatch_lane_invoke$VARIANT$armv81
11 libdispatch.dylib              0x49f14 _dispatch_workloop_worker_thread
12 libsystem_pthread.dylib        0x1bd0 _pthread_wqthread
13 libsystem_pthread.dylib        0x1720 start_wqthread

**Comment by C0lumbo** [comment]
We have had crashes in our app with callstacks similar to HyunjoonKo and qinfendezhou (i.e. without the two FirebasePerformance 0x18050 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke lines that are present in the OP's callstack).

We tracked it down to the Liftoff/Vungle ad network. We have been informed that updating our AdMob mediation adapter 7.4.1 to 7.4.2 should fix it (https://developers.google.com/admob/ios/mediation/liftoff-monetize). We haven't rolled out that fix so we don't know for sure that will fix it. 

I suspect that this is not the explanation for everyone's crashes, but may be useful information for some.

**Comment by jorgefrazaocosta** [comment]
+1

**Comment by ybrikeeg** [comment]
+1

**Comment by MichaelVerdon** [comment]
Is anyone still experiencing this issue without Vungle SDK being involved in their project?

**Comment by cocoapodsHUM** [comment]
We are also experiencing this issue. Currently, we are using Firebase 11.5.0, and the crash rate is 50%.

          Fatal Exception: NSGenericException
0  CoreFoundation                 0x83f20 __exceptionPreprocess
1  libobjc.A.dylib                0x172b8 objc_exception_throw
2  CFNetwork                      0xc7e48 CFHostCreateWithName
3  Plane Legends                  0xf11ca4 NotificationService.sendNotification(urlString:key:attempt:)
4  Plane Legends                  0xf13770 closure #1 in NotificationService.sendStoredTpats()
5  Plane Legends                  0xf3b290 closure #1 in Persistence.readStoredTpats(callback:)
6  Plane Legends                  0x3640f4 thunk for @escaping @callee_guaranteed @Sendable () -> ()
7  libdispatch.dylib              0x213c _dispatch_call_block_and_release
8  libdispatch.dylib              0x3dd4 _dispatch_client_callout
9  libdispatch.dylib              0xb400 _dispatch_lane_serial_drain
10 libdispatch.dylib              0xbf30 _dispatch_lane_invoke
11 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh
12 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread
13 libsystem_pthread.dylib        0x4934 _pthread_wqthread
14 libsystem_pthread.dylib        0x10cc start_wqthread

**Comment by kseniyastar** [comment]
I believe the crash we are experiencing is also related to this, here is the stack trace:

```          Crashed: com.apple.NSURLSession-delegate
0  libswiftCore.dylib             0x43b8e4 swift_isUniquelyReferenced_nonNull_native + 38
1  Hireup                         0xab090 specialized Telemetry.error(metric:log:buildTags:) + 177 (Telemetry.swift:177)
2  Hireup                         0x3d86c Analytics.reportInternalError(_:fatal:) + 76 (Errors.swift:76)
3  Hireup                         0x950c4 specialized HTTPClient.handleResponse(data:response:error:url:completion:) + 101 (HTTPClient.swift:101)
4  Hireup                         0x93720 closure #1 in HTTPClient.startBatchUpload(writeKey:batch:completion:) + 240
5  Hireup                         0x954ac partial apply for closure #1 in HTTPClient.startBatchUpload(writeKey:batch:completion:) + 112
6  Hireup                         0x95850 thunk for @escaping @callee_guaranteed @Sendable (@guaranteed Data?, @guaranteed NSURLResponse?, @guaranteed Error?) -> () + 148 (<compiler-generated>:148)
7  Hireup                         0x1ac6a8 __InstrumentUploadTaskWithRequestFromFileCompletionHandler_block_invoke_2 + 379 (FPRNSURLSessionInstrument.m:379)
8  Hireup                         0x1ac6a8 __InstrumentUploadTaskWithRequestFromFileCompletionHandler_block_invoke_2 + 379 (FPRNSURLSessionInstrument.m:379)
9  CFNetwork                      0xad214 __51-[__NSURLSessionLocal _uploadTaskWithTaskForClass:]_block_invoke + 508
10 CFNetwork                      0xacfdc __48-[__NSCFLocalUploadTask _private_issueDidFinish]_block_invoke + 160
11 libdispatch.dylib              0x2370 _dispatch_call_block_and_release + 32
12 libdispatch.dylib              0x40d0 _dispatch_client_callout + 20
13 libdispatch.dylib              0xb6d8 _dispatch_lane_serial_drain + 744
14 libdispatch.dylib              0xc214 _dispatch_lane_invoke + 432
15 libdispatch.dylib              0x17258 _dispatch_root_queue_drain_deferred_wlh + 288
16 libdispatch.dylib              0x16aa4 _dispatch_workloop_worker_thread + 540
17 libsystem_pthread.dylib        0x4c7c _pthread_wqthread + 288
18 libsystem_pthread.dylib        0x1488 start_wqthread + 8```

**Comment by KeiroMidori** [comment]
Same as @kseniyastar I see the same stack trace using 11.5.0. Anyone know if this is fixed in 11.6.0?

**Comment by MichaelVerdon** [comment]
I am wondering if it is related to configuration issues, I would recommend trying to update dependencies and especially Firebase if it is not on the latest version seeing it solved the issue for some others. If not, I would like to ask for a minimal reproducible example.

**Comment by aghiad-90** [comment]
Hi, 

I am getting exactly same issue on my app, 

and here is some info 

**Firebase SDK Version**
10.29.0

**Xcode Version**
15.2

**Installation Method**
CocoaPods

this is the logs from console: 

**'NSGenericException', reason: 'Task created in a session that has been invalidated’** 


![Image](https://github.com/user-attachments/assets/7894cba8-6e3d-482d-a38b-bdea81a690bb)



Please any help for that? 
thanks,
