### ISSUE TITLE
[Crashlytics] Xcode16 missing dSYM in Firebase in Debug Builds

### ISSUE THREAD

**Issue by dustin2023** [firebase/firebase-ios-sdk#14054]
## Issue Description
This is related to issues #13543 and #13764.

The problem is that when building the application with Debug mode on Xcode 16.1, the dSYM files fail to upload to Crashlytics. 
It worked in latest Xcode 15 version.

The workaround is to disable `Debug Dylib Support` in the target's Build Settings. However, this causes SwiftUI previews to stop working.

### Reproducing the issue

1. Set `ENABLE_DEBUG_DYLIB=YES` for build options
2. Build the application in Xcode 16.1

### Firebase SDK Version

11.4.0

### Xcode Version

16.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
11.4.0 - [FirebaseCrashlytics][I-CLS000000] [Firebase/Crashlytics] Packaged report with id '67cba1a19d7b4800a514f208856ed765' for submission
11.4.0 - [FirebaseCrashlytics][I-CLS000000] Submitting report async
11.4.0 - [FirebaseCrashlytics][I-CLS000000] [Crashlytics:Crash:Reports:Event] Sending app_exception event to Firebase Analytics for crash-free statistics
11.4.0 - [FirebaseCrashlytics][I-CLS000000] Completed report submission with id: 67cba1a19d7b4800a514f208856ed765
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by jclardy** [comment]
I'm also experiencing this issue on the same setup, Xcode 16.1, Firebase 11.4.0. For now I have a separate previews target for development.

**Comment by MichaelVerdon** [comment]
Does this issue come up when using the latest version 11.5.0?

**Comment by dustin2023** [comment]
> Does this issue come up when using the latest version 11.5.0?

Sadly, yes. I get the some error and also I figured out that I also get this Warning:
`warning: (arm64) /Users/dustin/Library/Developer/Xcode/DerivedData/MyAppName-cicejndcecececfe/Build/Products/Debug-iphonesimulator/MyAppName.app/ MyAppName empty dSYM file detected, dSYM was created with an executable with no debug info.
`

**Comment by rizafran** [comment]
Thanks for reporting. I tried setting the `ENABLE_DEBUG_DYLIB` to `YES`, but I was able to upload the dSYMs in the Crashlytics dashboard, and I'm using Xcode 16.1 to reproduce the issue. May I know if you're encountering any error when uploading the dSYMs?

**Comment by MichaelVerdon** [comment]
I have reliably been able to reproduce this error achieving the same warning and have been investigating it. Using XCode 16.1 and the current version. No errors come up but the exact same warning comes up after running a test app.

**Comment by themiswang** [comment]
The warning seems like is from XCode/lldb compiler rather Crashlytics (https://lldb.llvm.org/cpp_reference/SymbolFileDWARF_8cpp_source.html line655). This is probably something on Apple side, Crashlytics only consumes dSYM which is generated from Xcode.

**Comment by dustin2023** [comment]
> The warning seems like is from XCode/lldb compiler rather than Crashlytics (https://lldb.llvm.org/cpp_reference/SymbolFileDWARF_8cpp_source.html line655). This is probably something on Apple side, Crashlytics only consumes dSYM which is generated from Xcode. Related conversation on Apple side: https://developer.apple.com/forums/thread/761589?answerId=806733022#806733022

I opened a new post for this: https://developer.apple.com/forums/thread/768802
Maybe they have a solution. I will share it here as well.

**Comment by Harikarthyk** [comment]
+1

**Comment by CtrlJone** [comment]
+1

**Comment by grantespo** [comment]
+1

**Comment by alexanderkhitev** [comment]
Hello! Any news/updates?

**Comment by girishw** [comment]
+1 Maybe related to this ? https://developer.apple.com/forums/thread/761589?answerId=806733022#806733022

**Comment by BartoszCichecki** [comment]
+1

**Comment by themiswang** [comment]
One thing I realized after update to xcode 16.1 my test app build setting for `Debug information format` debug mode is changed to `DWARF` instead of `DWARF with dSYM file`. Can you double check the build setting and try it again? So far I cannot reproduce the issue using latest version of Firebase SDK. I also gonna send an issue to Feedback Assistance this week regarding with the warning.

**Comment by BartoszCichecki** [comment]
For me, it's a brand new project created with Xcode 16.1. I checked project file in text editor to make sure `DWARF with dSYM file` is selected. All other settings in Firebase guide [here](https://firebase.google.com/docs/crashlytics/get-started?platform=ios) are correct. Yet, I get both the warning about empty dSYM is there, AND most importantly, dsyms are not uplaoded - console warns about missing dSYM.

**Comment by BartoszCichecki** [comment]
I tried setting "Enable Debug Dylib Support" to "No", and I confirm - upload start working, but it breaks SwiftUI previews. What is more dSYMs that where uploaded to Firebase are missing version number. 

<img width="274" alt="Screenshot 2024-11-27 at 22 44 05" src="https://github.com/user-attachments/assets/3eb64d27-9838-46b0-930d-c82791142c07">

I dont know what is happening here, but it's time to take this more seriously and start being more active here guys.

**Comment by theoks** [comment]
We encounter the same issue with version 11.5.0. Any indication when this will be fixed?

**Comment by gokhanBozkrt** [comment]
+1

**Comment by kadirfayzi** [comment]
Same issue with version 11.6.0

**Comment by morozbogdn** [comment]
11.6.0 - same issue

**Comment by BartoszCichecki** [comment]
Don't worry guys, it's only a "minor" issue stretching several versions of Firebase with over 20 comments confirming it and no response from the team in over a week. We'll get there...

**Comment by theoks** [comment]
@themiswang this issue is retagged with the `needs-info` tag. Is there something in particular that any of the users that have commented in this thread can provide, eg like project configuration or logs?

As more and more projects transition to Xcode 16 this is becoming a real issue. Furthermore, manually uploading the dSYMs from the archives, doesn't change anything in the console.

Can someone in the team provide some guidance, workaround or estimate for a fix please?

**Comment by BartoszCichecki** [comment]
I did some investigations and while I don't hope for the Firebase team to take this seriously anymore here are the findings which are the likely cause of the issue.

When you build the app with `Enable Debug dylib support`, the structure of the dSYM is different compared to having this setting off or build on Xcode 15 and lower.

First of all, the message we see in logs:  

```
empty dSYM file detected, dSYM was created with an executable with no debug info.
```

while confusing is **NOT** a bug. Let me explain.

When you build with `Enable Debug dylib support` enabled this is the contents of the dSYM for your app:

![Screenshot 2024-12-04 at 21 53 56](https://github.com/user-attachments/assets/62711083-5743-495c-9edb-681553d876f9)

Notice that DWARF folder now has two files. The first one with no extension is only 8KB and, yes, it **IS** empty. It does not have any code, because what this option does is it effectively puts all of your code into a dynamic lib - this is the second file that in the picture above is 15,9MB.

Now the fun part: both files should be used for symbolication. When we try to look at UUIDs they have:

```
UUID: F6E59681-35B6-3E7B-AF46-2CFBD9557194 (arm64) /Users/bartosz/Library/Developer/Xcode/DerivedData/SampleApp-aoqqqukvbpngbebzelwfyxfsiekw/Build/Products/Debug-iphoneos/SampleApp.app.dSYM/Contents/Resources/DWARF/SampleApp
UUID: BF97E804-5141-3AD4-BA65-F7BB3B13A503 (arm64) /Users/bartosz/Library/Developer/Xcode/DerivedData/SampleApp-aoqqqukvbpngbebzelwfyxfsiekw/Build/Products/Debug-iphoneos/SampleApp.app.dSYM/Contents/Resources/DWARF/SampleApp.debug.dylib
```

obviously they are different. The problem is that _most likely_ Firebase ignores completely the `SampleApp.debug.dylib` file - which it isn't surprising because AFAIK this has not been a case before in earlier Xcode versions. If it is really the case, that is **a mistake** on Firebase side.

So why when using the script from the documentation the dSYMs are not uploaded to Firebase?

My guess is that there are some checks ran on the dSYM before upload, to avoid sending garbage. The script looks at the main file, sees that it's empty and skips upload.

This behavior _most likely_ needs to be updated. Just like, _most likely_ whatever does symbolication on Firebase backend also will need an update, to correctly use both files from the dSYM.

My humble opinion is that, this is not "an Apple bug". It's simply a change in how dSYMs are formatted/structured and Firebase needs to adjust to it.

The above investigation/conclusions were confirmed and acknowledged by another vendor providing crash reporting and they started working on a solution.

It just baffles me, how is it possible that absolutely no-one at Google verified if Crashlytics will work with new Xcode. Especially, that it is not like Xcode 16 came out a week ago. It's been TWO MONTHS since Xcode 16 release. And first beta that had this option was release like what? 6 months ago?

This comment marks end of my input into trying to help troubleshoot this issue. I will not waste my time on this, when the Firebase team doesn't give a flying *. I am moving crashlytics to a vendor that takes these things seriously.

**Comment by themiswang** [comment]
Hey @theoks,

First on our side as me and @rizafran have tried we cannot reproduce the issue, we really appreciate if someone could give us a test app example or steps can actually reproduce the issue as so far on our side we cannot reproduce the issue. Even with the build setting described in the issue I am still see my test app dSYM is getting generated and uploaded as expected.

And @BartoszCichecki, we really appreciate some patient as we are also trying to get solution out. The issue you mentioned is exactly the issue which resolved in https://github.com/firebase/firebase-ios-sdk/issues/13543, so I am surprising it is still not work for some other folks. If it's possible could you send your dSYM or project information from [Firebase Support](https://firebase.google.com/support/troubleshooter/contact) so we can get a further look? +1 and speaking with anger really does not help either you or the community as eventually we all trying to solve the problem.

**Comment by theoks** [comment]
His @themiswang,

This issue apparently affects a lot of different people. I counted 14 different people in this thread confirming this is indeed an issue that impacts them. 11.6.0 did not fix the issue either.

In our case this is how the console looks like:

<img width="948" alt="Screenshot 2024-12-12 at 7 40 28 AM" src="https://github.com/user-attachments/assets/137fa872-277d-4b40-a965-cad5952cdde2" />

This is an issue that has rendered a very crucial submodule of the SDK completely unusable. We are littered with unsymbolicated crashes, that we cannot debug, hurting our users' experience and our bottom line as well.

I understand the difficulty to resolve it when you cannot reproduce it yourselves, but on the other hand you need to understand that it's difficult for us to provide you with more info than "we followed your setup instructions and it doesn't work"—or in some cases it only works intermittently. The ones that know the intricacies of the SDK is the iOS Firebase team. We cannot possibly know what's causing it, and we have no tools to debug it properly, given that this feature requires an orchestration between the client and your backend to work correctly. It's also difficult to hand you over the code we are working on, due to contractual obligations. However it is evident that something changed with the latest Xcode release that affected how dSYMs are exported (as @BartoszCichecki described as well). 

I'd request again that someone from your team looks into it again, on a more complex project maybe, and try to find out what's the issue here.

**Comment by peterfriese** [comment]
Thanks, @theoks - can you share some details about the structure of your app? For example, do you use any app extensions, do you use local packages, etc.?

Does it also occur with a plain new project?

**Comment by theoks** [comment]
Hey @peterfriese thanks for getting back.

This is the list of external dependencies in our project. The only one missing from the list (because it's contained in a local package) is **Realm (version 20.0.0)**.
<img width="1234" alt="Screenshot 2024-12-12 at 8 28 42 AM" src="https://github.com/user-attachments/assets/0e9079a9-5584-444a-a729-fb598be69836" />

This is the structure of our internal packages:
<img width="235" alt="Screenshot 2024-12-12 at 8 28 56 AM" src="https://github.com/user-attachments/assets/42a5d756-18d0-48d9-a772-4ea82a2c25fa" />

We also have a notification service extension.

When we first created the project everything was working fine, until up to a month or so ago, when every dSYM upload started failing. If I can pinpoint it in time, it's around the time we started using Xcode 16.1.

We haven't tried it with a brand new project.

**Comment by nikojoel** [comment]
+1

**Comment by wyllys66** [comment]
+1

**Comment by camboYY** [comment]
+1

**Comment by benfrearson** [comment]
Just another voice seeing this with a brand new project in Xcode 16.1

1. Create a new iOS Project
2. Add Firebase 11.6
3. Set up Firebase as per instructions (Add bundle id to Firebase console, import GoogleProject-Settings.plist, add build phase + input files)
4. Enable DWARF + dSYM for all configs
5. Build app for Debug, observe "empty dSYM" message below:

```
warning: (arm64) /Users/benfrearson/Library/Developer/Xcode/DerivedData/Firebase-dsym-test-gvfyzwjozybxukgyicirqxnrukbl/Build/Products/Debug-iphonesimulator/Firebase-dsym-test.app/Firebase-dsym-test empty dSYM file detected, dSYM was created with an executable with no debug info.
```

6. Force crash and check Firebase Console - warning about missing dSYM.

**Comment by antoninmasek** [comment]
I'm also experiencing the same issue. Installed it as per instructions and am also seeing the `empty dSYM file detected, dSYM was created with an executable with no debug info` warning.

**Comment by kaizen1** [comment]
We have same issue with our app. Hard to believe the is not a priority. I'd file a ticket with Google, but I can hear the sound of a kicking can. So I will not.

**Comment by samedson** [comment]
Hey folks, sorry for the delay. We have a preview build of upload-symbols that we’d like folks to test out.

## Preview Fix
1. If you browse to the Crashlytics directory on `main`, you can download this version of [upload-symbols](https://github.com/firebase/firebase-ios-sdk/tree/b24f03b331afe0934ae78e887e28b79d3cbe288d/Crashlytics) before it’s released in the next version of Firebase.

For Swift Package Manager, you'll want to overwrite the `upload-symbols` file at `"${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/upload-symbols"`.

2. In addition, it is recommended to upload your Input Files for the Crashlytics Run Script with this additional line:

```
${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${PRODUCT_NAME}.debug.dylib
```
or use the [Crashlytics/CrashlyticsInputFiles.xcfilelist](https://github.com/firebase/firebase-ios-sdk/blob/b24f03b331afe0934ae78e887e28b79d3cbe288d/Crashlytics/CrashlyticsInputFiles.xcfilelist) with the new value in it.

Just wanted to give a little insight into what’s going on. There were two issues initially:
 - Previous issue: When `ENABLE_DEBUG_DYLIB=YES` is set, Crashlytics was not reading the new Debug Dylib file. That was fixed in [October](https://github.com/firebase/firebase-ios-sdk/pull/13760/files).
 - This issue: Xcode generates dSYMs async. We have code in `upload-symbols` to handle this for the main dSYM, but didn’t have it for the Debug Dylib dSYM. The preview version of `upload-symbols` for that fix is in the link above. We recommend the additional line in your Input Files so that Xcode knows to finish generating the Debug Dylib before calling the Crashlytics Run Script (this is why you get the empty dSYM error).

## Alternatives
If you are still running into issues after trying out the new version of upload-symbols
 - Upload symbols in the Crashlytics Console UI
 - You can revert to the old Xcode behavior by setting `ENABLE_DEBUG_DYLIB=NO`.

**Comment by antoninmasek** [comment]
Hello @samedson, thank you for the reply.

I just tried following the steps you described and can confirm that the crash logs were successfully logged into my Crashlytics console.

**Comment by benfrearson** [comment]
The fix also appears to work for me too.

Notably I still see the "empty dsym" message on a clean build on first run, but suspect this is as @samedson noted - if the dsyms are genereted async, perhaps the debugger connects before it's available. Happy so far with this as a fix though

**Comment by theoks** [comment]
@samedson thanks for the update and the fix for the previews. 

Nevertheless the issue a lot of us are facing here, has nothing to do with debug builds. Firebase doesn't upload the dSYMs in release builds. Is there any progress on this issue?

**Comment by gokhanBozkrt** [comment]
> [@samedson](https://github.com/samedson) thanks for the update and the fix for the previews.
> 
> Nevertheless the issue a lot of us are facing here, has nothing to do with debug builds. Firebase doesn't upload the dSYMs in release builds. Is there any progress on this issue?

+!

**Comment by samedson** [comment]
@theoks would you mind creating a new issue with the details of the issue for release builds?

**Comment by ldlefebvre** [comment]
I'm still seing "{Directory To My Project Debug-iphonesimulator dysym} empty dSYM file detected, dSYM was created with an executable with no debug info." with the fix with firebase 11.7 and having the extra run script file unless i change to ENABLE_DEBUG_DYLIB=NO. I also point to a different GoogleService-Info.plist in my run script based on if im in debug or release scheme and when i archive to push a version to apple, i get the warning of missing dsym files.

<img width="723" alt="Image" src="https://github.com/user-attachments/assets/ebd566d7-36cd-4d92-a571-7e531690cf68" />
<img width="737" alt="Image" src="https://github.com/user-attachments/assets/dbff33a7-62f5-420f-b5bf-e47f33205d52" />
<img width="728" alt="Image" src="https://github.com/user-attachments/assets/328b96e3-e04f-49e7-a870-f93fce2f7ac1" />
<img width="726" alt="Image" src="https://github.com/user-attachments/assets/6209a1b9-f12f-4a7d-83b5-14ccc7c28df1" />

**Comment by gokhanBozkrt** [comment]
+1

**Comment by kaizen1** [comment]
Seems like there's more interest in closing the ticket than in fixing the bug.

**Comment by lundjordan** [comment]
Hey all,

Jumping in here to echo the problem since it seems that's needed so this ticket doesn't get closed. Is it fair to say anyone who is developing for this past year's iOS via xcode 16 has crashlytics broken? Or this just affecting a subset of those people? If everyone, I would assume this is a tier 1 problem for Crashlytics and can't just close. 

100% understand I don't know the scope of who is affected but if it helps, I too can't get dysm symbols to work properly. I have tried forcing an update to 11.7+ and that seems to help get dsyms uploaded (even though I get the same failed warnings @ldlefebvre  screenshot'd above.

But the debug symbols that are on the dsyms tab in crashlytics web console don't ever get a "version" label attached to them and all my production crashes roll in without useful stack traces (actual line numbers where exceptions/errors take place) like they used to.

If I am doing something wrong or if there is a suggested fix, please let me know. Happy to debug this as it's starting to really hurt our product.

**Comment by benfrearson** [comment]
@lundjordan In the interest of data collection - I have multiple projects of various sizes in Xcode 16, and I'm largely not seeing issues after the above fix. I do have a few lingering missing dSYM firebase warnings, but these are not for my Production config, and are probably a result of the above async issue where the first run of a local Debug build won't have generated the files in time for the script to find them. (I don't know if there's any way for me to confirm this really, other than running of `dwarfdump` commands to match UUIDs against previous app builds). All this to say - in production, across multiple projects,  I'm not seeing any missing dSYMs at the moment. 

FWIW when things were broken for me, I don't remember having an issue with any builds that were run in Xcode Cloud, so I wonder if `xcrun` doesn't have the same issues that a manual Build or Archive from Xcode does 🤔

My understanding of "the issue" is that there' seems to be *at least* couple of different actual problems, other than the fact that "crashlytics is broken". I think the fix discussed here only relates to 1?
1. **Debug** builds aren't uploading dSYMs
2. **Release** builds aren't uploading dSYMS
3. Framework dSYMS sometimes are missing

**Comment by wyllys66** [comment]
I see #2. Whenever I upload a release archive to the App Store for distribution, I get a warning about missing dSYMS for all of the firebase and google package dependencies.  I don't see #1 because I don't upload debug builds.

This is NOT using XCode Cloud or Test Flight.  I do all of my builds (in XCode, not manually) and tests locally and upload for distribution when it's ready and I'm satisfied with the build.

**Comment by fred-bowker** [comment]
Hi @samedson 

Relating to 2. Release Builds aren't uploading symbols when you archive and upload to the App Store

My understanding of this is that when upgrading to XCode 16, all users of Firebase crashlytics will start seeing the error:

**Upload Symbols Failed
The archive did not include a dSYM for the FirebaseAnalytics.framework**

The Apple developer link https://developer.apple.com/forums/thread/761589?answerId=808296022#808296022, states this is by design and that the issue occurs when a 3rd party library doesn't include a corresponding dsym file for the library.

Is it your understanding that this is why we have now started seeing this warning when users have moved to XCode 16 from XCode 15?

Thanks,
Fred

**Comment by samedson** [comment]
Hey @fred-bowker - can you share this in https://github.com/firebase/firebase-ios-sdk/issues/13764. I'm going to ping my team next week to see if we can figure out why Analytics (and some others) aren't including symbols.

**Comment by fred-bowker** [comment]
@samedson done, it would be good if we could get an update, stating that this is definitely the reason the warnings are coming up

**Comment by samedson** [comment]
@fred-bowker responded in https://github.com/firebase/firebase-ios-sdk/issues/13764

@VValiente, the issue with debug builds should not impact archived / Release versions of your app. If you haven't cleaned yet, you may still have the dSYM in your archive. I would recommend following https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios for troubleshooting help.

**Comment by kaizen1** [comment]
If kicking the can were an Olympic Sport. Firebase support would dominate.
We're driving blind to bugs in the field. But the can is way down the road now! 
Congrats Google.

**Comment by wyllys66** [comment]
Coming up on 4 months now and still no fix for this??!?

**Comment by fred-bowker** [comment]
@samedson Hi, I'm not sure about your comments about following those steps. My understanding of this was that your team are looking into whether this is the case for all users that are using XCode 16. If this is the case then either something should be  changed within the firebase sdks so that the warning goes away or the firebase official documentation should be updated so that users of the library understand what the warnings relate to.

In my view the criticism of some of these comments is justified as people have been complaining about these warnings now for 4 months.

**Comment by wyllys66** [comment]
@samedson I have seen that comment and followed the thread in the Apple forums.  At this point, both sides are trying to blame the other and nothing is being done to fix it.

**Comment by karimjimo** [comment]
Hi there

Is there any ETA for this issue?

**Comment by samedson** [comment]
@fred-bowker I believe we are discussing your issue in https://github.com/firebase/firebase-ios-sdk/issues/13764. Are you having an issue with debug builds as well? 

I believe the issue with debug builds has been solved by folks following https://github.com/firebase/firebase-ios-sdk/issues/14054#issuecomment-2619406791. If that's not the case it would be awesome if folks would provide more information.

This issue is not for discussing warnings when you upload archives. If you are getting a warning uploading archives please follow this issue: https://github.com/firebase/firebase-ios-sdk/issues/13764. While the warning says "uploading symbols" it has nothing to do with Crashlytics uploading symbols. You'll find more information in the linked issue.
