### ISSUE TITLE
Codesigning failure starting with 11.14.0

### ISSUE THREAD

**Issue by sberrevoets** [firebase/firebase-ios-sdk#15052]
### Description

Starting with version 11.14.0 (and also 11.15.0), our codesigning on CI (Xcode 16.3) fails:

```
error: exportArchive "Speak-V2.app" requires a provisioning profile with the App Groups, Associated Domains, Communication Notifications, Push Notifications, and Sign in with Apple features.

error: exportArchive "SpeakNotificationExtension.appex" requires a provisioning profile with the App Groups feature.

error: exportArchive "SpeakWidgetExtension.appex" requires a provisioning profile with the App Groups feature.
```

The provisioning profiles haven't changed, and reverting Firebase to 11.13 builds the app correctly. I noticed there were quite a few dependency changes for 11.14, is it possible any of the changes there causes this issue for us?

I realize the information I'm providing here is sparse, mostly because I don't have much more info myself, but let me know what would be helpful!

### Reproducing the issue

This is specific to our setup unfortunately

### Firebase SDK Version

11.14.0+

### Xcode Version

16.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication, Analytics, Messaging

### Targeted Platforms

iOS

### Package.resolved

<details>
<summary>Relevant Package.resolved info</summary>
<br>

```json

    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk.git",
      "state" : {
        "revision" : "fdc352fabaf5916e7faa1f96ad02b1957e93e5a5",
        "version" : "11.15.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "45ce435e9406d3c674dd249a042b932bee006f60",
        "version" : "11.15.0"
      }
    }
```

</details>

**Comment by ovo-mlongeri** [comment]
Hi @sberrevoets,
I confirm that with version `11.14.0` we have started to experience exactly the same issue. I have just tested `11.15.0` with the same result, so for now we are also stuck to version `11.13.0`.

Matteo

**Comment by ncooke3** [comment]
Apologies for the trouble. What Firebase products are you using, @matteolongeri-ovolab?

**Comment by ovo-mlongeri** [comment]
Hi @ncooke3,

Currently we are using:
- **FirebaseAnalytics**
- **FirebaseAppCheck**
- **FirebaseCrashlytics**
- **FirebasePerformance**

We use SPM to add them to our project.

Matteo

**Comment by mmoser-hw** [comment]
Hello, we face the same issue. We had this specific error on previous versions when trying to integrate the OnDeviceMeasurement SDK. Our solution at the time was to fork this specific library and embark it in our project, without loading it via SPM. Now that this library is included in the 11.14 version of Firebase Analytics, the issue re-emerged in our project too. 
So it seems strongly related to the OnDeviceMeasurement SDK.

**Comment by adozenlines** [comment]
For Apple 12 it is all of the modules is the code signing missing an intermediary certificate or is being signed with an Enterprise Certificate?

**Comment by Cedrick84** [comment]
Experiencing the same from 11.14 up to latest (12) using 

- FirebaseAnalytics
- FirebaseCrashlytics

**Comment by ncooke3** [comment]
Hi everyone, as I'm understanding this, 11.14.0+ (including 12.0.0 now) has this issue for projects using Analytics? 

Is anyone able to reproduce this issue without Analytics present?

**Comment by ncooke3** [comment]
I so far have been unable to reproduce this using SwiftPM. I tried using the `analytics/` project in the Firebase Quickstart repo  (https://github.com/firebase/quickstart-ios/tree/main/analytics). I added Analytics, Messaging, and Auth via SPM and was able to successfully archive the project without running into any signing issues.

**Comment by sberrevoets** [comment]
I'm not overly familiar with Firebase's suite of frameworks, but we believe it's related to `FirebaseAnalyticsOnDeviceConversion` or `GoogleAdsOnDeviceConversion` (or both) specifically. We get the same problem when using 11.13.0 with those frameworks, and 11.14.0+ automatically includes those hence the error there too.

**Comment by mikehaydan** [comment]
hello. getting the same. Seems like Firebase SDK "forces" to use manual signing instead of automatic

**Comment by sberrevoets** [comment]
We now suspect the issue pops up in the overlap between our CI provider (Bitrise) and `GoogleAdsOnDeviceConversion`. See this possibly related issue: https://github.com/bitrise-steplib/steps-xcode-archive/issues/380

It's unclear to me if this issue is more on the Firebase side or on the Bitrise side, but since it started happening after a change on the Firebase side _and_ none of the other Firebase frameworks have this problem, I'm inclined to believe something (presumably signing) about that particular framework is different/wrong that causes the issue.

For others that are seeing this issue: can you confirm you're also using Bitrise and specifically that Bitrise step?

**Comment by iSallyAbdallah** [comment]
I believe it's Firebase issue , have same issue in Jenkins

**Comment by mmoser-hw** [comment]
We are also using Bitrise to build and deploy our app, but to be honest we haven't tried signing it without Bitrise so we can't confirm it's only breaking with Bitrise

**Comment by ovo-mlongeri** [comment]
Hi @sberrevoets, it is not related to Bitrise, since we have the same issue using GitLab

**Comment by mikehaydan** [comment]
for sure it's related to signing. 
For example, when I use "manual" upload from my machine, Xcode even doesn't prompt possibilities to use automatic signing. It happens starting from **11.14.0**, older version - works fine

**Comment by pcfba** [comment]
@sberrevoets, can you try removing and re-adding the FirebaseAnalytics SPM dependency, except this time, select FirebaseAnalyticsCore instead of FirebaseAnalytics in the "Choose Package Products for firebase-ios-sdk" popup when you add the firebase-ios-sdk package dependency? This will remove the GoogleAdsOnDeviceConversion dependency. And then retry your CI.

**Comment by sberrevoets** [comment]
We did try that (in a different way than you suggested), and it works but we actually _want_ the GoogleAdsOnDeviceConversion dependency as our marketing folks would like to use it 😅

**Comment by pcfba** [comment]
Good to know. Investigating...

**Comment by pcfba** [comment]
I'm not able to reproduce the problem in a new sample app with extensions, some added capabilities, and with FirebaseAnalytics, other Firebase dependencies, and GoogleAdsOnDeviceConversion added via SPM.

If this is a problem with the use of the CI systems combined with Firebase 11.14.0+, I won't be able to test against the various CI systems here.

There's nothing particularly special about GoogleAdsOnDeviceConversion and its dependencies: https://github.com/googleads/google-ads-on-device-conversion-ios-sdk/blob/main/Package.swift.

@sberrevoets or if anyone else has time, is it possible to create a simple new test app with GoogleAdsOnDeviceConversion (https://github.com/googleads/google-ads-on-device-conversion-ios-sdk/) added via SPM, and build/archive/sign/etc with and without your CI system?

For the others that are seeing the same error, can you paste your error so we can gather more info?

**Comment by ncooke3** [comment]
Hi everyone, if you're using Firebase 11.14 or 11.15, updating your dependencies will pick up a new patch release, GoogleAdsOnDeviceConversion **2.2.1**. We identified one discrepancy in that package's XCFramework structure that could possibly lead to the signing issue. Please try verifying if this fixes your CI workflows and let us know the result. Thanks!

**Comment by Cedrick84** [comment]
Just tried with this setup (on Bitrise) and failed with the same error as before.
```
Firebase: https://github.com/firebase/firebase-ios-sdk @ 11.15.0
GoogleAdsOnDeviceConversion: https://github.com/googleads/google-ads-on-device-conversion-ios-sdk @ 2.2.1
```

```
error: exportArchive requires a provisioning profile with the App Groups, Apple Pay, Associated Domains, and Push Notifications features.
```

**Comment by ncooke3** [comment]
Thanks @Cedrick84 for trying. Could you please provide the xcodebuild command your CI is using? Feel free to omit the target/project name. We are still have trouble reproducing this.

More generally, is anyone facing this on GitHub Actions as well?

**Comment by Cedrick84** [comment]
```
failed to export IPA:
    command failed with exit status 70 (xcodebuild "-exportArchive" "-archivePath" "/var/folders/f6/wf2hj3cj75qdwmt5rn814r_00000gn/T/xcodeArchive1082722120/Project.xcarchive" "-exportPath" "/var/folders/f6/wf2hj3cj75qdwmt5rn814r_00000gn/T/xcodeIPAExport663525697/exported" "-exportOptionsPlist" "/var/folders/f6/wf2hj3cj75qdwmt5rn814r_00000gn/T/xcodeIPAExport663525697/export_options.plist" "-allowProvisioningUpdates" "-authenticationKeyPath" "/var/folders/f6/wf2hj3cj75qdwmt5rn814r_00000gn/T/AuthKey_86JRRDRR8L_3857647050.p8" "-authenticationKeyID" "86JRRDRR8L" "-authenticationKeyIssuerID" "4a236b88-7704-4d08-9e49-90e1661e5ba9"):
      error: exportArchive "Project.app" requires a provisioning profile with the App Groups, Apple Pay, Associated Domains, and Push Notifications features.
```

**Comment by ncooke3** [comment]
We are actively looking into this, but it is difficult to debug without being able to reproduce. If anyone is able to share how to reproduce this locally, it would be very helpful. Additionally, a reproducible example on GitHub Actions could also be helpful.

**Comment by sberrevoets** [comment]
Definitely understand it's hard to debug without reproduction steps @ncooke3. I spent a little bit of time trying to set something up to reproduce but the problem is that since we suspect the issue lies in codesigning, reproducing it involves setting up a CI system, Apple Developer account with credentials, etc. Not super straightforward unfortunately...

**Comment by ncooke3** [comment]
Is anyone able to reproduce it locally with the following setup?

This script is my attempt to archive and export. I'm unable to reproduce the error with this.

1. Checkout the directory containing your Xcode project.
2. Create a `build` directory if one doesn't exist: `mkdir ./build`
3. Create a `exportOptions.plist` file: `touch ./exportOptions.plist`
4. Populate `exportOptions.plist` with the following:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>debugging</string>
	<key>teamID</key>
	<string>YOUR_TEAM_ID</string>
	<key>signingStyle</key>
	<string>automatic</string>
</dict>
</plist>
```
  - A couple notes on the plist values and keys: Possible values for `method` are `debugging` or `app-store-connect`. Possible values for `signingStyle` are `automatic` or `manual`.
  - I was able to reproduce the `-exportArchive` error with `manual` signing mode, but I'm not convinced this is what you all are running into as well, since I got the same error when my test project uses 11.13.0, a version that you are have reported works.
5. Substitute in your team ID for the string value mapping to the teamID key.
6.  Copy the below script and paste into a new `archive_and_export.sh`, then: `chmod +x archive_and_export.sh`
```bash
#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Error: Missing arguments."
    echo "Usage: $0 <PROJECT_NAME> <SCHEME>"
    exit 1
fi

PROJECT_NAME="$1"
SCHEME="$2"

BUILD_DIR="./build"
ARCHIVE_PATH="$BUILD_DIR/$SCHEME.xcarchive"
EXPORT_PATH="$BUILD_DIR/exported"
EXPORT_OPTIONS_PLIST="./exportOptions.plist"

xcodebuild archive \
  -project "$PROJECT_NAME".xcodeproj \
  -scheme "$SCHEME" \
  -configuration "Release" \
  -destination "generic/platform=iOS" \
  -archivePath "$ARCHIVE_PATH" \
  -quiet || exit 1

xcodebuild -exportArchive \
  -archivePath "$ARCHIVE_PATH" \
  -exportPath "$EXPORT_PATH" \
  -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" \
  -allowProvisioningUpdates
```
  - This script assumed you don't have an xcworkspace file. If you do, replace the `-project "$PROJECT_NAME".xcodeproj \` line with `-workspace "$PROJECT_NAME".xcworkspace \`.
7. Run: `./archive_and_export.sh YOUR_PROJECT YOUR_SCHEME_NAME`
  - In my local example, my project name is the same as my scheme. 
8. If it fails, that may mean this is reproducing the issue. Try setting the Firebase version to 11.13, and ideally the script should work.

**Comment by sberrevoets** [comment]
Hate to be the bearer of bad news, but unfortunately it succeeds for me following those steps both while using 11.13 and 11.14...

**Comment by ncooke3** [comment]
Thanks for trying, @sberrevoets! I'm unfamiliar with Bitrise, are you able to see the commands that lead to the failure? I tried to guess the contents of `exportOptions.plist`, but would be curious if you can retrieve the contents from what Bitrise is using?

**Comment by sberrevoets** [comment]
The exportOptions.plist Bitrise uses is this

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>method</key>
		<string>release-testing</string>
	</dict>
</plist>
```

But using that in your steps still succeeds locally.

My next step in trying to reproduce this is to take the archive directly from CI and invoke xcodebuild the same as it does in the export step:

```
set -o pipefail && xcodebuild "-exportArchive" "-archivePath" "/var/folders/f6/wf2hj3cj75qdwmt5rn814r_00000gn/T/xcodeArchive488210911/Speak-V2.xcarchive" "-exportPath" "/var/folders/f6/wf2hj3cj75qdwmt5rn814r_00000gn/T/xcodeIPAExport246761722/exported" "-exportOptionsPlist" "/var/folders/f6/wf2hj3cj75qdwmt5rn814r_00000gn/T/xcodeIPAExport246761722/export_options.plist" "-allowProvisioningUpdates" "-authenticationKeyPath" "__AUTH_KEY_PATH__" "-authenticationKeyID" "__AUTH_KEY_ID__" "-authenticationKeyIssuerID" "__AUTH_KEY_ISSUER_ID__"
```

This is the specific command that fails for us.

**Edit:** forgot I actually had tried that exact same command with the exact same xcarchive before and it succeeds locally...

**Comment by ncooke3** [comment]
@sberrevoets, thanks for trying. I haven't been able to reproduce locally, so I would instead like to provide you a branch with a prerelease XCFramework that you could test.

I created a branch off of Firebase 11.15.0 that uses special branches of the GoogleAppMeasurement and GoogleAppMeasurementOnDeviceConversion repos to get the latest pre-release XCFramework we are testing. Right now, my hypothesis is that it is related to the `Info.plist`s within the XCFramework, so we've added some fields that were missing. It's still unclear whether the new fields make a difference during the signing process.

If you'd like to test, you can do so by updating your Firebase dependency to the branch: `nc/debug-15052`

**Comment by sberrevoets** [comment]
No dice unfortunately.

I was also debugging more late last week, and running the script you posted on CI does work for us, but still the Bitrise-provided archive/export step does not. What's interesting though is that the specific xcodebuild invocation for exporting is effectively the same, so I'm guessing it's the archive step that's different—I'll try to dig a little deeper on that later this week.

**Comment by ncooke3** [comment]
Thanks, @sberrevoets, let me know if you find anything interesting. I did try some more changes and have created a new branch for testing: 

```
nc/debug-15052-rc1
```

**Comment by sberrevoets** [comment]
Good news and bad news: it just suddenly started working. Nothing changed on our end, but as of this morning the problem went away and we were able to archive and export a build like normal. I'm stumped by the why and would love to figure out what the issue was but I can't get it to reproduce in any way anymore.

I'll withhold final judgment until we create a new release early next week but so far it's looking good.

**Comment by ncooke3** [comment]
> Nothing changed on our end

Hi @sberrevoets, when you say "Nothing changed on our end", does that also include the SDK versions? We released `google-ads-on-device-conversion-ios-sdk 2.3.0` two days ago which Firebase 11.15.0 would pick up. Are you able to see if it picked up this version and started working?

**Comment by fatih-gursoy** [comment]
Hi @ncooke3 , we have same issue. You said that you released `google-ads-on-device-conversion-ios-sdk 2.3.0` , we updated the latest version of Firebase but it still 2.2.0. Maybe the dependency hasn't been updated yet.

**Comment by ncooke3** [comment]
> Hi [@ncooke3](https://github.com/ncooke3) , we have same issue. You said that you released `google-ads-on-device-conversion-ios-sdk 2.3.0` , we updated the latest version of Firebase but it still 2.2.0. Maybe the dependency hasn't been updated yet.

Hi @fatih-gursoy, Firebase 11.15 will pick up new minor version releases of `google-ads-on-device-conversion-ios-sdk` like `2.3.0`. I recall @sberrevoets was still using Firebase 11. If you're using the latest Firebase **12**, we've set the versioning up differently and the `google-ads-on-device-conversion-ios-sdk` dependency is fixed per Firebase version and doesn't pick up new releases.

**Comment by fatih-gursoy** [comment]
@ncooke3 Ok, yes we are using v12 but we are still getting errors while signing code, is there any progress on this issue?

**Comment by ncooke3** [comment]
@fatih-gursoy, Firebase 12.2 is releasing next week and has a fixed dependency on `google-ads-on-device-conversion-ios-sdk` 2.3.0 (which includes the latest attempt at addressing the signing bug). It's unclear to me if the issue was resolved for @sberrevoets because their project started picking up `google-ads-on-device-conversion-ios-sdk` 2.3.0 because they are using Firebase 11, or if the issue was resolved for a reason unrelated to Firebase (e.g. maybe the the issue was related to CI tooling rather than Firebase?).

**Comment by sberrevoets** [comment]
@ncooke3 Yes we updated to Firebase 11.15 (12 is the next step) and the timing does seem to align so maybe `google-ads-on-device-conversion-ios-sdk` 2.3.0 did solve the problem? Hard to say - the same change that was failing in the past (which was just a version bump in Package.swift, no other changes) suddenly started working for us so the actual change was very minimal

**Comment by ncooke3** [comment]
> maybe `google-ads-on-device-conversion-ios-sdk` 2.3.0 did solve the problem?

I would be a little surprised since you had tried my `nc/debug-15052` and `nc/debug-15052-rc1` branches which used the same plist that went into the official 2.3.0 release. However those RCs were unsigned so maybe a combination of their plist and code signature was needed.

@sberrevoets, you could try adding an explicit depending on google-ads-on-device-conversion-ios-sdk 2.2.0 and seeing if that failed. Then another test where explicitly depending on google-ads-on-device-conversion-ios-sdk 2.3.0. In any case though, I'm glad to hear it unblocked your workflow.

---

Firebase 12.2 will release next week with a strict dependency on google-ads-on-device-conversion-ios-sdk 2.3.0 so Firebase 12 customers can try with this latest attempt to resolve this. 

Thanks everyone for your patience and help debugging this issue.

**Comment by mmoser-hw** [comment]
Hello, we noticed that Firebase 12.2 and checked if the issue was resolved. Looks like it is, code signing seems to work correctly, thanks for the fix :) 

Out of curiosity, could you tell us what fixed the issue ?

Thank you for your time

**Comment by ncooke3** [comment]
Thanks, @mmoser-hw, for the update! I will close this issue now. Please don't hesitate to reach out if the issue resumes.

> Out of curiosity, could you tell us what fixed the issue ?

The suspicion was that the platform slice-level Info.plist in the XCFramework had missing keys that affected code signing. Using other Firebase XCFrameworks as an example, multiple missing key/value pairs were added to the plist in the latest update. One or some combination of them must have been necessary to unblock signing. As we weren't able to ever reproduce it, I don't know exactly which key/value pair(s) fixed it. 

```console
% tree -L 3 GoogleAdsOnDeviceConversion.xcframework 
GoogleAdsOnDeviceConversion.xcframework
├── _CodeSignature
├── Info.plist
├── ios-arm64
│   └── GoogleAdsOnDeviceConversion.framework
│       ├── GoogleAdsOnDeviceConversion
│       ├── Headers
│       ├── Info.plist ← 👀 Added key/value pairs to be consistent with other Firebase XCFrameworks
│       └── Modules
└── ios-arm64_x86_64-simulator
    └── GoogleAdsOnDeviceConversion.framework
        ├── GoogleAdsOnDeviceConversion
        ├── Headers
        ├── Info.plist ← 👀 Added key/value pairs to be consistent with other Firebase XCFrameworks
        └── Modules
```
