### ISSUE TITLE
[RemoteConfig] Apple Mach-O Linker Error (using pods)

### ISSUE THREAD

**Issue by augusto-carmo** [firebase/firebase-ios-sdk#1640]
* Xcode version: **9.4.1 (9F2000)**
  * Firebase SDK version: **4.13.0**
  * Firebase Component: **RemoteConfig**
  * Component version: **4.13.0**

---

### The problem

The project is not compiling after I have added the `Firebase/RemoteConfig` to my project (It worked when I tried to compile only the `Firebase/Core`). 

Xcode throws 10 errors:

![image](https://user-images.githubusercontent.com/18216987/43717123-e98ffaba-995c-11e8-9de7-4510945f6be4.png)

<details>
<summary>Full Log (click to expand)</summary>

```
Ld /Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Products/Debug-iphonesimulator/MyProject.app/MyProject normal x86_64
    cd /Users/my_user/Documents/SolProjects/iOSMyProject/MyProject
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk -L/Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Products/Debug-iphonesimulator -F/Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Products/Debug-iphonesimulator -F/Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Products/Debug-iphonesimulator/Alamofire -F/Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Products/Debug-iphonesimulator/AlamofireImage -F/Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Products/Debug-iphonesimulator/DZNEmptyDataSet -F/Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Products/Debug-iphonesimulator/ImageScrollView -F/Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Products/Debug-iphonesimulator/PocketSVG -F/Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Products/Debug-iphonesimulator/SQLite.swift -F/Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Products/Debug-iphonesimulator/SwiftProtobuf -F/Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Products/Debug-iphonesimulator/lottie-ios -F/Users/my_user/Documents/SolProjects/iOSMyProject/MyProject -filelist /Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Intermediates.noindex/MyProject.build/Debug-iphonesimulator/MyProject.build/Objects-normal/x86_64/MyProject.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Intermediates.noindex/MyProject.build/Debug-iphonesimulator/MyProject.build/Objects-normal/x86_64/MyProject_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Intermediates.noindex/MyProject.build/Debug-iphonesimulator/MyProject.build/Objects-normal/x86_64/MyProject.swiftmodule -framework Alamofire -framework AlamofireImage -framework DZNEmptyDataSet -framework ImageScrollView -framework Lottie -framework PocketSVG -framework SQLite -framework SwiftProtobuf -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Intermediates.noindex/MyProject.build/Debug-iphonesimulator/MyProject.build/MyProject.app-Simulated.xcent -framework FirebaseCore -framework Pods_MyProject -framework Protobuf -framework Protobuf -framework YouTubePlayer -framework FirebaseRemoteConfig -framework FirebaseABTesting -Xlinker -dependency_info -Xlinker /Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Intermediates.noindex/MyProject.build/Debug-iphonesimulator/MyProject.build/Objects-normal/x86_64/MyProject_dependency_info.dat -o /Users/my_user/Library/Developer/Xcode/DerivedData/MyProject-fdkhsolhvqanmkgeavdyagnuwpow/Build/Products/Debug-iphonesimulator/MyProject.app/MyProject

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GPBDescriptor", referenced from:
      objc-class-ref in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      objc-class-ref in FirebaseABTesting(ExperimentPayload.pbobjc_4e1beb4a76b519334457d2edc68ca6a8.o)
  "_OBJC_CLASS_$_GPBEnumDescriptor", referenced from:
      objc-class-ref in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      objc-class-ref in FirebaseABTesting(ExperimentPayload.pbobjc_4e1beb4a76b519334457d2edc68ca6a8.o)
  "_GPBGetMessageInt32Field", referenced from:
      _ABTExperimentPayload_OverflowPolicy_RawValue in FirebaseABTesting(ExperimentPayload.pbobjc_4e1beb4a76b519334457d2edc68ca6a8.o)
  "_OBJC_METACLASS_$_GPBMessage", referenced from:
      _OBJC_METACLASS_$_RCNPackageData in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      _OBJC_METACLASS_$_RCNKeyValue in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      _OBJC_METACLASS_$_RCNNamedValue in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      _OBJC_METACLASS_$_RCNConfigFetchRequest in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      _OBJC_METACLASS_$_RCNPackageTable in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      _OBJC_METACLASS_$_RCNAppNamespaceConfigTable in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      _OBJC_METACLASS_$_RCNAppConfigTable in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      ...
  "_GPBSetInt32IvarWithFieldInternal", referenced from:
      _SetABTExperimentPayload_OverflowPolicy_RawValue in FirebaseABTesting(ExperimentPayload.pbobjc_4e1beb4a76b519334457d2edc68ca6a8.o)
  "_OBJC_CLASS_$_GPBMessage", referenced from:
      _OBJC_CLASS_$_RCNPackageData in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      _OBJC_CLASS_$_RCNKeyValue in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      _OBJC_CLASS_$_RCNNamedValue in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      _OBJC_CLASS_$_RCNConfigFetchRequest in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      _OBJC_CLASS_$_RCNPackageTable in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      _OBJC_CLASS_$_RCNAppNamespaceConfigTable in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      _OBJC_CLASS_$_RCNAppConfigTable in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      ...
  "_OBJC_METACLASS_$_GPBRootObject", referenced from:
      _OBJC_METACLASS_$_RCNConfigRoot in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      _OBJC_METACLASS_$_ABTExperimentPayloadRoot in FirebaseABTesting(ExperimentPayload.pbobjc_4e1beb4a76b519334457d2edc68ca6a8.o)
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in FirebaseRemoteConfig(RCNConfigSettings_22e23cfa4b36fa0d65a3f7296e546bb7.o)
      objc-class-ref in FirebaseRemoteConfig(RCNDevice_b34010fb0ab3a3316b3c7f3a7a1f6525.o)
  "_GULLoggerRegisterVersion", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_OBJC_CLASS_$_FIRInstanceID", referenced from:
      objc-class-ref in FirebaseRemoteConfig(RCNConfigFetch_818a3e7a84a8883f210a714bb3ad1fe5.o)
  "_OBJC_CLASS_$_GPBFileDescriptor", referenced from:
      objc-class-ref in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      objc-class-ref in FirebaseABTesting(ExperimentPayload.pbobjc_4e1beb4a76b519334457d2edc68ca6a8.o)
  "_GULLoggerInitializeASL", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLoggerForceDebug", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_OBJC_CLASS_$_GPBRootObject", referenced from:
      _OBJC_CLASS_$_RCNConfigRoot in FirebaseRemoteConfig(Config.pbobjc_3cb2eac75751d3cd2757df0f7544c9e9.o)
      _OBJC_CLASS_$_ABTExperimentPayloadRoot in FirebaseABTesting(ExperimentPayload.pbobjc_4e1beb4a76b519334457d2edc68ca6a8.o)
  "_GULLogBasic", referenced from:
      _FIRLogBasic in FirebaseCore(FIRLogger.o)
  "_GULLoggerEnableSTDERR", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULIsLoggableLevel", referenced from:
      _FIRIsLoggableLevel in FirebaseCore(FIRLogger.o)
  "_GULSetLoggerLevel", referenced from:
      _FIRSetLoggerLevel in FirebaseCore(FIRLogger.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
</details>

---

<details>
<summary>
Podfile (click to expand)
</summary>

```podfile
platform :ios, '9.0'
use_frameworks!  

target 'MyProject' do
    pod 'ImageScrollView'
    pod 'DZNEmptyDataSet'
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'SQLite.swift'
    pod 'SwiftProtobuf'
    pod 'lottie-ios'
    pod 'PocketSVG'
    pod 'Firebase', '4.13.0'
    pod 'Firebase/RemoteConfig', '4.13.0'
end

target 'Protobuf' do
    pod 'SwiftProtobuf'
end
```

</details>

---

<details>
<summary>
Podfile.lock (click to expand)
</summary>

```
PODS:
  - Alamofire (4.6.0)
  - AlamofireImage (3.3.0):
    - Alamofire (~> 4.5)
  - DZNEmptyDataSet (1.8.1)
  - Firebase (4.13.0):
    - Firebase/Core (= 4.13.0)
  - Firebase/Core (4.13.0):
    - FirebaseAnalytics (= 4.2.0)
    - FirebaseCore (= 4.0.20)
  - Firebase/RemoteConfig (4.13.0):
    - Firebase/Core
    - FirebaseRemoteConfig (= 2.1.3)
  - FirebaseABTesting (1.0.0):
    - FirebaseCore (~> 4.0)
    - Protobuf (~> 3.1)
  - FirebaseAnalytics (4.2.0):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - nanopb (~> 0.3)
  - FirebaseCore (4.0.20):
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
  - FirebaseInstanceID (2.0.10):
    - FirebaseCore (~> 4.0)
  - FirebaseRemoteConfig (2.1.3):
    - FirebaseABTesting (~> 1.0)
    - FirebaseAnalytics (~> 4.1)
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - Protobuf (~> 3.5)
  - GoogleToolboxForMac/Defines (2.1.4)
  - "GoogleToolboxForMac/NSData+zlib (2.1.4)":
    - GoogleToolboxForMac/Defines (= 2.1.4)
  - ImageScrollView (1.4)
  - lottie-ios (2.1.5)
  - nanopb (0.3.8):
    - nanopb/decode (= 0.3.8)
    - nanopb/encode (= 0.3.8)
  - nanopb/decode (0.3.8)
  - nanopb/encode (0.3.8)
  - PocketSVG (2.4.0)
  - Protobuf (3.6.0)
  - SQLite.swift (0.11.5):
    - SQLite.swift/standard (= 0.11.5)
  - SQLite.swift/standard (0.11.5)
  - SwiftProtobuf (1.0.2)

DEPENDENCIES:
  - Alamofire
  - AlamofireImage
  - DZNEmptyDataSet
  - Firebase (= 4.13.0)
  - Firebase/RemoteConfig (= 4.13.0)
  - ImageScrollView
  - lottie-ios
  - PocketSVG
  - SQLite.swift
  - SwiftProtobuf

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - Alamofire
    - AlamofireImage
    - DZNEmptyDataSet
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseInstanceID
    - FirebaseRemoteConfig
    - GoogleToolboxForMac
    - ImageScrollView
    - lottie-ios
    - nanopb
    - PocketSVG
    - Protobuf
    - SQLite.swift
    - SwiftProtobuf

SPEC CHECKSUMS:
  Alamofire: f41a599bd63041760b26d393ec1069d9d7b917f4
  AlamofireImage: 2e784dc5d00f04903a52c1d169181469c805c3df
  DZNEmptyDataSet: 9525833b9e68ac21c30253e1d3d7076cc828eaa7
  Firebase: 5ec5e863d269d82d66b4bf56856726f8fb8f0fb3
  FirebaseABTesting: d07d0ee833b842d5153549e4c7e2e2cb1c23a3f9
  FirebaseAnalytics: 7ef69e76a5142f643aeb47c780e1cdce4e23632e
  FirebaseCore: 90cb1c53d69b556f112a1bf72b5fcfaad7650790
  FirebaseInstanceID: 8d20d890d65c917f9f7d9950b6e10a760ad34321
  FirebaseRemoteConfig: 3e95fb7c072308492e85fa41d59d38b3d6fd2372
  GoogleToolboxForMac: 91c824d21e85b31c2aae9bb011c5027c9b4e738f
  ImageScrollView: 887523542097173da75172774e9800ee473bdccd
  lottie-ios: 836cdbba92f62f3c6a00e37a4ce485321fe317cf
  nanopb: 5601e6bca2dbf1ed831b519092ec110f66982ca3
  PocketSVG: 8ac7b20a881ca1a3d46ba1e54ee2b0f2307c3d48
  Protobuf: 0fc0ad8bec688b2a3017a139953e01374fedbd5f
  SQLite.swift: 6e5356850bb1791459f8c16d6ee9195b28714a2e
  SwiftProtobuf: e41d205c91eac0fb46823f2561712407fefdaf4e

PODFILE CHECKSUM: c7284bed023fe73a94b4a6390eb29f15477a8101

COCOAPODS: 1.5.3
```
</details>

---

I have already tried a bunch of stuff to try to solve this problem, but nothing worked out 🙁.

Thanks in advance ;)

**Comment by paulb777** [comment]
It looks like you have a mix of Firebase 4.x and 5.x pods. 

Did you run `pod install` instead of `pod update`?

Is there any reason for locking to version `4.13.0` versus using the latest Firebase?

**Comment by paulb777** [comment]
Yeah, the pods in the 'MyProject' target work fine for me whether I pin Firebase to 4.13.0 or not.

It is likely to be related specifically to the implementation of the `Protobuf` target in the Xcode project. I'm not sure what you mean by "module". Do you mean Xcode target?  How does `Protobuf` relate to `MyProject`?

We likely need a reproducible to example to help further. Also, since this seems to be more of an iOS app structure question than a Firebase issue, stackoverflow might be a better venue to expose the question to a broader set of potential answerers.

**Comment by augusto-carmo** [comment]
Hello, @paulb777!

One of my colleagues made an attempt where he renamed the _target_ `Protobuf` and the problems seems to have been solved. So, it looks like that all of those errors were being thrown due to target names conflict(?) - _this may explain why I could not find many people having the same problem while I was looking for a solution in the Internet, it is a very specific problem_.

Thank you very much for your attention and your time \o/.

I'll close the issue as long as everything is ok now 🎉

**Comment by ristinolla** [comment]
Hi,

Although this is closed issue, have anyone seen this when installing the SDK manually (not using Cocoapods)? Or how to actually achieve @augusto-carmo's idea of renaming the `Protobuf` to something else?

I just downloaded the newest SDK `5.6.0` and the problem still persists. Using the same Xcode version (9.4.1).

Thanks for any help on where to look next!

**Comment by augusto-carmo** [comment]
Hello, @ristinolla, every now and than, when I have to switch branches and they use different pods, I am required to empty the _Derived Data_ folder, so xCode does not warn me of any errors. For your next branch switches and `pod install`, only that step might do it :)

**Comment by ristinolla** [comment]
Thanks, @augusto-carmo for the tip, I'll keep in the mind that _Derived Data_ is something to remember to clean every now and then.

**Comment by stickfaith** [comment]
I also encountered this error, it can be solved by import GoogleUtilities.framework，

**Comment by aaslamdev** [comment]
Thanks @stickfaith . Adding that framework solved the problem.
