### ISSUE TITLE
I am getting "multiple command produce gRPCCertificates.bundle" error in Firestore when archiving

### ISSUE THREAD

**Issue by mihirpmehta** [firebase/firebase-ios-sdk#2102]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.0  (10A255)
  * Firebase SDK version:  Firebase 5.13.0, FirebaseFirestore (0.15.0)
  * Firebase Component: FirebaseFirestore (0.15.0)
  * Component version: 0.15.0

#### Steps to reproduce:

install firestore through pod 

`pod 'Firebase/Firestore' ` and archive 

#### Relevant Code:

```
 platform :ios, '11.0'

target 'FireCheck' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireCheck
 
 pod 'Firebase/Firestore'

end
```
It produce following error in archiving 

Multiple commands produce '...iphoneos/gRPCCertificates.bundle':

> 
> 1) Target 'gRPC-C++-gRPCCertificates' has create directory command with output '.../iphoneos/gRPCCertificates.bundle'
> 
> 2) Target 'FirebaseFirestore-gRPCCertificates' has create directory command with output '....iphoneos/gRPCCertificates.bundle'

I have already tried clean, deleting derive data, de-integrating and reintegrating pods , nothing works I am using XCode 10.

Any help is appreciated

**It only happens when i do build and archive ... normal run/debug works**

**Comment by mihirpmehta** [comment]
The difference is between Pods-WhereRU-resources.sh 

```
if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_resource "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseFirestore/gRPCCertificates.bundle"

if [[ "$CONFIGURATION" == "Release" ]]; then
  install_resource "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseFirestore/gRPCCertificates.bundle"
```

If i build and archive with previous version of MacOS High Sierra with same XCode version same CocoaPods version these lines are not generated in **Pods-WhereRU-resources.sh** file

**Comment by paulb777** [comment]
Dupe question at https://stackoverflow.com/questions/53406947/xcode10-ios-firebase-firestore-sdk-multiple-command-produce-grpccertificates

**Comment by mihirpmehta** [comment]
Hi 

in Firestore version  0.14.0 (pod 'Firebase/Firestore', '5.12.0') Everything works fine. This problem starts in version 0.15.0 only... Also in XCode if i build using Legacy build system it works in 0.15.0 ... but if i use new build system which is default, this error comes ....

**Comment by paulb777** [comment]
Ok, it seems the issue has nothing to do with the macOS version.

I reproduced on macOS 10.13 with the Firestore quickstart and CocoaPods 1.5.3. I successfully archived with 0.14.0 and ran `pod update` installing 0.15.0 and **gRPC-Core 1.17.0-pre1** and then got the build failure.

**Comment by var-const** [comment]
@mihirpmehta Can you please post contents of your `Podfile.lock` file?

**Comment by simonbengtsson** [comment]
Here is other lockfile, if it helps. Will update this with more info if I find anything.

Mac: 10.14.1
Xcode: 10.1
Build System: New

[Podfile.txt](https://github.com/firebase/firebase-ios-sdk/files/2605299/Podfile.txt)

**Comment by paulb777** [comment]
The gRPC-C++ latest official release has a hard dependency to a gRPC-Core pre-release - https://github.com/CocoaPods/Specs/blob/master/Specs/c/8/7/gRPC-C++/0.0.4/gRPC-C++.podspec.json#L147

**Comment by var-const** [comment]
@simonbengtsson Thanks!

I see from your Podfile.lock that gRPC-C++ version 0.0.4 is used. The issue is triggered by the combination of the latest Firestore and gRPC-C++ 0.0.4. As a quick measure, if you could force CocoaPods to use gRPC-C++ 0.0.3, it should resolve the archiving issue.

**Comment by paulb777** [comment]
The gRPC team just pushed version 0.0.5 of gRPC-C++.

I did a `pod update` and now the quickstart successfully archives.

**Comment by grehce** [comment]
> ive with previous version of MacOS High Sierra with same XCode version same CocoaPods version these lines are not generated in **Pods-resources.sh** file

Where can I find the Pods-resource.sh file? I'm experiencing the same issue and in the Podlock file, I'm at <gRPC-C++ (= 0.0.6)> and its still an issue for me.

**Comment by mharrisweb** [comment]
I am getting a similar error, any ideas?

ejected-calendar/ios/gRPCCertificates.bundle: No such file or directory

My podfile is:

```
target 'rgcalendar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for rgcalendar

 pod 'Firebase/Core'
 pod 'Firebase/Firestore', '5.12.0'

end
```

**Comment by wilhuff** [comment]
@grehce If you have multiple targets, CocoaPods may generate a file named `Pods-target-resources.sh`. From the root of your project you can run `find . -name Pods\*resources.sh` to find them all. In general if you're having this kind of problem, you may benefit from deleting your `Pods` directory and `~/Library/Developer/Xcode/DerivedData` and installing again.

**Comment by wilhuff** [comment]
@mharrisweb, similar advice applies.

Additionally, is there any reason you're pinning yourself to the Firebase 5.12.0 version of Firestore?

**Comment by mharrisweb** [comment]
@wilhuff reinstalled and working thanks! Now using latest and not, 5.12.0

**Comment by grehce** [comment]
For whatever reason, this problem has popped up again. I seem to remember commenting out one of the duplicate bundles but I can't seem to find where it is referenced. I found the resources.sh files but I don't recall making the edits here. Any help would be much appreciated.

> 
Showing Recent Messages
:-1: Multiple commands produce '/Users/gracechang/Library/Developer/Xcode/DerivedData/Kintsugi_Mindful_Wellness-gnzvsjmujxysuheltofpllhobbun/Build/Intermediates.noindex/ArchiveIntermediates/Kintsugi Mindful Wellness/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/gRPCCertificates.bundle':
1) Target 'gRPC-C++-gRPCCertificates' has create directory command with output '/Users/gracechang/Library/Developer/Xcode/DerivedData/Kintsugi_Mindful_Wellness-gnzvsjmujxysuheltofpllhobbun/Build/Intermediates.noindex/ArchiveIntermediates/Kintsugi Mindful Wellness/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/gRPCCertificates.bundle'
2) Target 'gRPC-gRPCCertificates' has create directory command with output '/Users/gracechang/Library/Developer/Xcode/DerivedData/Kintsugi_Mindful_Wellness-gnzvsjmujxysuheltofpllhobbun/Build/Intermediates.noindex/ArchiveIntermediates/Kintsugi Mindful Wellness/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/gRPCCertificates.bundle'

**Comment by wilhuff** [comment]
If you're using the latest versions this shouldn't be happening because gRPC-C++ now creates a [bundle with a different name](https://github.com/grpc/grpc/blob/master/gRPC-C%2B%2B.podspec#L75) (note that in your error message it's still the old, conflicting name). Make sure you've got FirebaseFirestore 1.3.2 and gRPC-C++ 0.0.9 or later.

If you're already on those versions and reinstalling doesn't help (i.e. deleting `Pods` and `~/Library/Developer/Xcode/DerivedData` doesn't help, please open a new issue with your `Podfile.lock` and any details you have about how this may have come about.

**Comment by grehce** [comment]
The only challenge with the pod update 'Firebase/Firestore' is that it creates 20 new errors across updated files, and this is the last blocker to shipping :/

**Comment by wilhuff** [comment]
Well, I can't really help unless you share something concrete. Please do open a new issue with your details.

**Comment by grehce** [comment]
Updated Cocoapods and had to update Firebase and this blocking archiving issue comes up again. 

- Target in the root folder only points to one resources.sh file (not multiple targets) 
- I've deleted the derived data and still on archive, come up with the following `Multiple commands produce.../Build/Intermediates.noindex/ArchiveIntermediates/.../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/gRPCCertificates.bundle`

**Comment by wu-hui** [comment]
Hi grehce,

Can you please open a new issue, with more information about installed version of Firestore and gRPC, basically the output of your `pod install`? It might also help us reproducing it if you tell us your environment as well, OS version, XCode version, etc.

Thanks

**Comment by wilhuff** [comment]
I've taken your set of pods, with the exception of `pod 'googleapis', :path=> "."` which I don't have, and I'm able to archive the project. It seems likely that you have some combination of things in your project that aren't playing well together.

Please open a new new issue--this isn't related to the one fixed in gRPC-C++ 0.0.5.

**Comment by grehce** [comment]
Thanks everyone, will open a new issue. Just didn't want to create a duplicate.
