### ISSUE TITLE
Many documentation issues for FirebaseFirestore

### ISSUE THREAD

**Issue by ghowen** [firebase/firebase-ios-sdk#2111]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 5.13
  * Firebase Component: Firestore
  * Component version: 0.15.0

### [REQUIRED] Step 3: Describe the problem
Still loads of documentation warnings when compiling. They have been there for a bit (even before GRPC changed) and are still not fixed. The don't do any damage but they clutter up the warnings Buildtime column.

```
Documentation Issue Group
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/server_context.h:117:14: Parameter 'meta_key' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:29:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:29:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_stream.h:35:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_stream.h:35:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/generic/generic_stub.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/generic/generic_stub.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/support/async_stream.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/support/async_stream.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/async_stream.h:25:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/async_stream.h:25:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/server_context.h:119:14: Parameter 'meta_value' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:29:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:29:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_stream.h:35:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_stream.h:35:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/generic/generic_stub.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/generic/generic_stub.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/support/async_stream.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/support/async_stream.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/async_stream.h:25:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/async_stream.h:25:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/server_context.h:131:14: Parameter 'meta_key' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:29:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:29:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_stream.h:35:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_stream.h:35:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/generic/generic_stub.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/generic/generic_stub.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/support/async_stream.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/support/async_stream.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/async_stream.h:25:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/async_stream.h:25:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/server_context.h:133:14: Parameter 'meta_value' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:29:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:29:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_stream.h:35:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_stream.h:35:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/generic/generic_stub.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/generic/generic_stub.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/support/async_stream.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/support/async_stream.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/async_stream.h:25:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/async_stream.h:25:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/server_context.h:181:14: Parameter 'algorithm' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:29:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:29:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_stream.h:35:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_stream.h:35:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/generic/generic_stub.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/generic/generic_stub.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/support/async_stream.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/support/async_stream.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/async_stream.h:25:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/async_stream.h:25:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/server_context.h:181:14: Did you mean 'level'?
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/completion_queue.h:123:14: Parameter 'tag[out]' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/completion_queue.h:124:14: Parameter 'ok[out]' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/completion_queue.h:179:14: Parameter 'tag[out]' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/completion_queue.h:180:14: Parameter 'ok[out]' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/completion_queue.h:182:14: Parameter 'deadline[in]' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/completion_queue.h:182:14: Did you mean 'deadline'?
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/completion_queue.h:198:14: Parameter 'F[in]' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/completion_queue.h:199:14: Parameter 'tag[out]' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/completion_queue.h:200:14: Parameter 'ok[out]' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/completion_queue.h:201:14: Parameter 'deadline[in]' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/completion_queue.h:201:14: Did you mean 'deadline'?
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/completion_queue.h:373:14: Parameter 'is_frequently_polled' not found in the function declaration
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.mm:17:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/write_stream.h:28:
/Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:10: In file included from /Users/georg/Projekte/Apps/anyfinder/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_connection.h:37:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:10: In file included from /Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/completion_queue.h:22:
/Users/georg/Library/Developer/Xcode/DerivedData/anyfinder-bdockobagwffbqffgmngmljlmois/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework/Headers/impl/codegen/completion_queue.h:373:14: Did you mean 'polling_type'?

```
#### Steps to reproduce:

Compile a Swift app with Firestore (target iOS 11)

**Comment by var-const** [comment]
Thank you for the report. As far as I can see, the warnings all stem from gRPC-C++ which is one of our dependencies. I'll see if we can make a PR to fix those documentation warnings in gRPC.

In the meantime, if those warnings are annoying, you could configure your podspec to ignore all warnings produced by Firestore by adding `:inhibit_warnings => true`:
```
pod 'Firebase/Firestore', :inhibit_warnings => true
```

**Comment by ghowen** [comment]
@var-const Thanks for the hint. I reformatted the original report which makes it easier to see where the warnings are coming from.

**Comment by var-const** [comment]
This was fixed in gRPC repo: https://github.com/grpc/grpc/pull/16992. The warnings will go away once Firestore upgrades to a gRPC release that includes the fix (in a future Firestore release). I'll close the issue for now; feel free to reopen if you encounter any documentation issues not stemming from gRPC.

**Comment by WillShelley** [comment]
Having the same problem here. After recent update gRPC-C++ is causing 15 documentation issues in Xcode 10.1/Swift. Tried running :inhibit_warnings => true but warnings are still there.

**Comment by Sndrsn** [comment]
I was having the same issue. I went ahead and included the  inhibit warnings line, and ran pod update, and the warnings went away. WillShelley, did you include the comma after 'FirebaseFirestore' and run pod update afterward?

**Comment by valstripe** [comment]
For me the warnings don't go away either. Had the line perfectly copied and pastied, updated my pods, but the warnings still don't go away

**Comment by Appswage** [comment]
Agree with @valstripe above. Documentation errors continue to exist and the warnings remain even with the "inhibit_warnings" indicator.

**Comment by WillShelley** [comment]
Sndrsn I'm still having the documentation issues even after updating/cleaning the pod file. I think this may stem from deleting my derived data for that project a while ago. Is there a way to fix this?

**Comment by wilhuff** [comment]
Here's the current state of this issue:

  * We've fixed the documentation errors upstream in gRPC
  * gRPC has cut a new release containing the fix
  * We're cutting a new release referencing the fix. This release is imminent.

Unfortunately, the gRPC-C++ CocoaPod is not yet a part of the mainline gRPC release process, so we cannot depend on it with a floating version number that would have allowed this trivial fix to come in automatically. For the moment please hang tight :-).

**Comment by WillShelley** [comment]
Thanks appreciate it 👍

**Comment by yunnnyunnn** [comment]
Instead of
`pod 'Firebase/Firestore', :inhibit_warnings => true`
You can use
`pod 'FirebaseFirestore', :inhibit_warnings => true` to ignore the warnings.
Also if `Protobuf` produces warnings, add
`pod 'Protobuf', :inhibit_warnings => true`
