### ISSUE TITLE
The setData handler won't call, and the console logs [BoringSSL] nw_protocol_boringssl_get_output_frames(1301)

### ISSUE THREAD

**Issue by jwfstars** [firebase/firebase-ios-sdk#2188]
I start a new project with only Firebase init code and setData code。
The promblem only appears in iOS12(maybe in iOS11), I test in iOS10.0.2 its OK。
I followed  https://stackoverflow.com/questions/52217167/trying-to-get-data-from-the-url-and-get-console-warnings but not help.

  * Xcode version: Xcode10, iOS12.1
  * Firebase SDK version: 5.14.0
  * Firebase Component: Core ,Firestore
  * Component version: 5.1.9, 0.16.0

#### Relevant Code:
```
FIRCollectionReference *citiesRef = [self.db collectionWithPath:@"cities"];
    [[citiesRef documentWithPath:@"SF1"] setData:@{
                                                  @"name": @"San Francisco",
                                                  @"state": @"CA",
                                                  @"country": @"USA",
                                                  @"capital": @(NO),
                                                  @"population": @860000
                                                  } completion:^(NSError * _Nullable error) {
                                                      NSLog(@"%@", error);
    }];
```
#### The firestore rules
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write;
    }
  }
}
```

#### Logs
```
2018-12-14 16:30:00.717632+0800 FirebaseTest[8608:2539420]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2018-12-14 16:30:01.402838+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/InstanceID][I-IID013010] InstanceID library version 3.3.0
2018-12-14 16:30:01.408797+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Initializing. Current user:
2018-12-14 16:30:01.414517+0800 FirebaseTest[8608:2539420] 5.14.0 - [GULReachability][I-REA902004] Network status has changed. Code:3, status:Connected
2018-12-14 16:30:01.417042+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Start LevelDB: 0 changes (0 bytes):>
2018-12-14 16:30:01.425029+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Start MutationQueue: 0 changes (0 bytes):>
2018-12-14 16:30:01.427821+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2018-12-14 16:30:01.442907+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2018-12-14 16:30:01.573307+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2018-12-14 16:30:01.576932+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2018-12-14 16:30:01.580117+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2018-12-14 16:30:01.583322+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2018-12-14 16:30:01.595054+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2018-12-14 16:30:01.600334+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2018-12-14 16:30:01.604087+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2018-12-14 16:30:01.607538+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2018-12-14 16:30:01.776361+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] WriteStream (101a07948) start
2018-12-14 16:30:01.777541+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Locally write mutations: 2 changes (184 bytes):
  - Put [document_mutation: user_id= key=cities/SF1 batch_id=194] (0 bytes)
  - Put [mutation: user_id= batch_id=194] (184 bytes)>
2018-12-14 16:30:01.779501+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NotifyLocalViewChanges: 0 changes (0 bytes):>
2018-12-14 16:30:01.780869+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Firestore][I-FST000001] Creating Firestore stub.
2018-12-14 16:30:01.781229+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Analytics][I-ACS024000] Debug mode is on
2018-12-14 16:30:01.783322+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Analytics][I-ACS005000] The AdSupport Framework is not currently linked. Some features will not function properly. Learn more at http://goo.gl/9vSsPb
2018-12-14 16:30:01.784821+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Analytics][I-ACS031010] Tracking view controller. Class, ID: ViewController, 9064551556537898353
2018-12-14 16:30:01.785558+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Analytics][I-ACS031013] Screen view event not logged. App is not active.
2018-12-14 16:30:01.927862+0800 FirebaseTest[8608:2539424] 5.14.0 - [GULReachability][I-REA902003] Monitoring the network status
2018-12-14 16:30:01.928989+0800 FirebaseTest[8608:2539424] 5.14.0 - [Firebase/Firestore][I-FST000001] Using roots.pem file from Firestore pod
2018-12-14 16:30:01.929582+0800 FirebaseTest[8608:2539424] 5.14.0 - [Firebase/Firestore][I-FST000001] WriteStream (101a07948) initial request: <GCFSWriteRequest 0x281d94c80>: {
    database: "projects/fir-test-d59a0/databases/(default)"
}
2018-12-14 16:30:01.930898+0800 FirebaseTest[8608:2539424] 5.14.0 - [GULReachability][I-REA902004] Network status has changed. Code:3, status:Connected
2018-12-14 16:30:01.931391+0800 FirebaseTest[8608:2539424] 5.14.0 - [Firebase/Analytics][I-ACS023007] Analytics v.50400000 started
2018-12-14 16:30:01.931901+0800 FirebaseTest[8608:2539424] 5.14.0 - [Firebase/Analytics][I-ACS023008] To disable debug logging set the following application argument: -noFIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2018-12-14 16:30:01.932307+0800 FirebaseTest[8608:2539424] 5.14.0 - [Firebase/Analytics][I-ACS023009] Debug logging enabled
2018-12-14 16:30:01.936681+0800 FirebaseTest[8608:2539423] 5.14.0 - [GoogleUtilities/AppDelegateSwizzler][I-SWZ001008] Successfully created App Delegate Proxy automatically. To disable the proxy, set the flag GoogleUtilitiesAppDelegateProxyEnabled to NO (Boolean) in the Info.plist
2018-12-14 16:30:01.958672+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS029014] Successfully parsed a configuration. Version: 1544759803627966
2018-12-14 16:30:01.959680+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS023016] Analytics is ready to receive events
2018-12-14 16:30:01.964898+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS023080] Setting user property. Name, value: first_open_after_install (_fi), 1
2018-12-14 16:30:01.974515+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS023087] User property set. Name, value: first_open_after_install (_fi), 1
2018-12-14 16:30:02.100557+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS032003] iAd framework is not linked. Search Ad Attribution Reporter is disabled.
2018-12-14 16:30:02.102540+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS023024] No data to upload. Upload task will not be scheduled
2018-12-14 16:30:02.104851+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS033003] Scheduling user engagement timer
2018-12-14 16:30:02.105913+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS002002] Engagement timer scheduled to fire in approx. (s): 3600
2018-12-14 16:30:02.106423+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS023012] Analytics enabled
2018-12-14 16:30:02.108344+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Analytics][I-ACS023051] Logging event: origin, name, params: auto, screen_view (_vs), {
    firebase_event_origin (_o) = auto;
    firebase_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 9064551556537898353;
}
2018-12-14 16:30:02.111745+0800 FirebaseTest[8608:2539420] 5.14.0 - [Firebase/Analytics][I-ACS023073] Debug mode is enabled. Marking event as debug and real-time. Event name, parameters: screen_view (_vs), {
    firebase_debug (_dbg) = 1;
    firebase_event_origin (_o) = auto;
    firebase_screen_class (_sc) = ViewController;
    ga_realtime (_r) = 1;
    ga_screen_id (_si) = 9064551556537898353;
}
2018-12-14 16:30:02.151796+0800 FirebaseTest[8608:2539436] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:4][0x101a1e060] get output frames failed, state 8196
2018-12-14 16:30:02.152066+0800 FirebaseTest[8608:2539436] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:4][0x101a1e060] get output frames failed, state 8196
2018-12-14 16:30:02.152979+0800 FirebaseTest[8608:2539436] TIC Read Status [1:0x0]: 1:57
2018-12-14 16:30:02.153106+0800 FirebaseTest[8608:2539436] TIC Read Status [1:0x0]: 1:57
2018-12-14 16:30:02.220034+0800 FirebaseTest[8608:2539436] 5.14.0 - [Firebase/InstanceID][I-IID009000] Cannot retrieve keypair with tag com.google.iid-|K|
2018-12-14 16:30:02.259571+0800 FirebaseTest[8608:2539436] 5.14.0 - [Firebase/Analytics][I-ACS023072] Event logged. Event name, event params: screen_view (_vs), {
    firebase_debug (_dbg) = 1;
    firebase_event_origin (_o) = auto;
    firebase_screen_class (_sc) = ViewController;
    ga_realtime (_r) = 1;
    ga_screen_id (_si) = 9064551556537898353;
}
2018-12-14 16:30:02.288773+0800 FirebaseTest[8608:2539436] 5.14.0 - [Firebase/Analytics][I-ACS002002] Measurement timer scheduled to fire in approx. (s): -0.1356339454650879
2018-12-14 16:30:02.289324+0800 FirebaseTest[8608:2539436] 5.14.0 - [Firebase/Analytics][I-ACS023028] Upload task scheduled to be executed in approx. (s): -0.1356339454650879
2018-12-14 16:30:02.289669+0800 FirebaseTest[8608:2539436] 5.14.0 - [Firebase/Analytics][I-ACS002001] Measurement timer fired
2018-12-14 16:30:02.290126+0800 FirebaseTest[8608:2539436] 5.14.0 - [Firebase/Analytics][I-ACS002003] Measurement timer canceled
2018-12-14 16:30:02.290533+0800 FirebaseTest[8608:2539436] 5.14.0 - [Firebase/Analytics][I-ACS023033] Starting data upload
2018-12-14 16:30:02.293147+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS023105] Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters: screen_view (_vs), {
    firebase_debug (_dbg) = 1;
    firebase_event_origin (_o) = auto;
    firebase_screen_class (_sc) = ViewController;
    ga_realtime (_r) = 1;
    ga_screen_id (_si) = 9064551556537898353;
}
2018-12-14 16:30:02.300389+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS012018] Saving bundle. size (bytes): 401
2018-12-14 16:30:02.301398+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS023116] Bundle added to the upload queue. BundleID, timestamp (ms): 50, 1544776201152
2018-12-14 16:30:02.316590+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS023038] Uploading events. Elapsed time since last successful upload (s): 576.0471920967102
2018-12-14 16:30:02.317025+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS023039] Measurement data sent to network. Timestamp (ms), data: 1544776202316, <APMPBMeasurementBatch: 0x28319e3e0>
2018-12-14 16:30:02.321919+0800 FirebaseTest[8608:2539424] 5.14.0 - [Firebase/Analytics][I-ACS900000] Uploading data. Host: https://app-measurement.com/a
2018-12-14 16:30:02.639515+0800 FirebaseTest[8608:2539423] 5.14.0 - [Firebase/Analytics][I-ACS901006] Received SSL challenge for host. Host: https://app-measurement.com/a
2018-12-14 16:30:02.910216+0800 FirebaseTest[8608:2539424] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C2.1:4][0x101b3f260] get output frames failed, state 8196
2018-12-14 16:30:02.910540+0800 FirebaseTest[8608:2539424] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C2.1:4][0x101b3f260] get output frames failed, state 8196
2018-12-14 16:30:02.912047+0800 FirebaseTest[8608:2539424] TIC Read Status [2:0x0]: 1:57
2018-12-14 16:30:02.912148+0800 FirebaseTest[8608:2539424] TIC Read Status [2:0x0]: 1:57
2018-12-14 16:30:02.955319+0800 FirebaseTest[8608:2539422] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C3.1:4][0x101b3f110] get output frames failed, state 8196
2018-12-14 16:30:02.955550+0800 FirebaseTest[8608:2539422] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C3.1:4][0x101b3f110] get output frames failed, state 8196
2018-12-14 16:30:02.956481+0800 FirebaseTest[8608:2539422] TIC Read Status [3:0x0]: 1:57
2018-12-14 16:30:02.956590+0800 FirebaseTest[8608:2539422] TIC Read Status [3:0x0]: 1:57
2018-12-14 16:30:02.966884+0800 FirebaseTest[8608:2539422] 5.14.0 - [Firebase/Analytics][I-ACS023044] Successful upload. Got network response. Code, size: 204, -1
2018-12-14 16:30:02.975468+0800 FirebaseTest[8608:2539424] 5.14.0 - [Firebase/Analytics][I-ACS002002] Measurement timer scheduled to fire in approx. (s): -0.8227810859680176
2018-12-14 16:30:02.976074+0800 FirebaseTest[8608:2539424] 5.14.0 - [Firebase/Analytics][I-ACS023028] Upload task scheduled to be executed in approx. (s): -0.8227810859680176
2018-12-14 16:30:02.993723+0800 FirebaseTest[8608:2539424] 5.14.0 - [Firebase/Analytics][I-ACS023024] No data to upload. Upload task will not be scheduled
2018-12-14 16:30:02.994273+0800 FirebaseTest[8608:2539424] 5.14.0 - [Firebase/Analytics][I-ACS002003] Measurement timer canceled

```

**Comment by wilhuff** [comment]
Sorry for the delay in responding to this--somehow this got lost around the holidays. I'm currently working on reproducing this.

**Comment by jwfstars** [comment]
Sorry, it has been solved now. It is the problem caused by the VPN client I used. I changed a VPN client.

**Comment by wilhuff** [comment]
OK, whew. I was not able to reproduce and starting to worry there was some deeper issue :-).

**Comment by madurangae** [comment]
I'm seeing the same console output message and I'm not using a VPN service. However, everything seems to be working as expected. 

I tried running the app on the simulator and on a real device with Wifi and then on LTE connection. The log still appears.

**Comment by wilhuff** [comment]
As of iOS 11, Apple's implementation of `CFNetwork` now uses BoringSSL under the covers. This implementation is very chatty in the logs. There's been a bunch of discussion online about this ([example](https://stackoverflow.com/questions/46352735/what-is-tic-read-status-157-in-ios11-xcode-9)).

If everything is working as expected, these are safe to ignore.

**Comment by cody088** [comment]
I guess I have similar problem, how you fix it with changing VPN? I am in china now

**Comment by RamuMansani** [comment]
Hi I'm unable to get data from firebase and even auth is also not working few hours back it was working fine, not sure why its not working now, even in logs also no error messages to debug and get solve.

Getting below only.

<AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist


- [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)


[BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.2:2][0x15be31870] get output frames failed, state 8196


can some one please help me on to solve my issue, i'm stuck here

**Comment by mikelehen** [comment]
Hi @RamuMansani, this issue is closed and wasn't tracking any specific bug.  If you believe you're hitting a bug in the SDK, please open a new github issue following the issue template, including the version of the SDK you're using, and code that reproduces the issue.

It would also be helpful if you could enable logging in the SDK:
```
FirebaseConfiguration.shared.setLoggerLevel(.debug)
```

and include that in your bug report (redacting any sensitive information as required).  Thanks.

You can also reach out to Firestore support for help with troubleshooting: https://firebase.google.com/support/troubleshooter/

**Comment by RamuMansani** [comment]
ok
