### ISSUE TITLE
BoringSSL iOS 11 error

### ISSUE THREAD

**Issue by Aurazion** [firebase/firebase-ios-sdk#314]
Hi,
Many users have problem with firebase since iOS 11 with boringssl (google boringssl ios 11). 
I'm using FirebaseMessaging in my App, and here is my logs : 

```
2017-09-26 12:15:34.078197+0200 myApp[6009:786492] [DYMTLInitPlatform] platform initialization successful
2017-09-26 12:15:39.761677+0200 myApp[6009:786585] [Firebase/Analytics][I-ACS023007] Firebase Analytics v.40003000 started
2017-09-26 12:15:39.761720+0200 myApp[6009:786585] [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2017-09-26 12:15:39.827000+0200 myApp[6009:786507] [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. Add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
2017-09-26 12:15:39.832230+0200 myApp[6009:786585] [BoringSSL] Function boringssl_context_get_peer_sct_list: line 1754 received sct extension length is less than sct data length
2017-09-26 12:15:39.878970+0200 myApp[6009:786585] [BoringSSL] Function boringssl_context_get_peer_sct_list: line 1754 received sct extension length is less than sct data length
2017-09-26 12:15:40.216274+0200 myApp[6009:786188] refreshPreferences: HangTracerEnabled: 0
2017-09-26 12:15:40.216322+0200 myApp[6009:786188] refreshPreferences: HangTracerDuration: 500
2017-09-26 12:15:40.216346+0200 myApp[6009:786188] refreshPreferences: ActivationLoggingEnabled: 0 ActivationLoggingTaskedOffByDA:0
2017-09-26 12:15:40.323994+0200 myApp[6009:786485] TIC Read Status [1:0x0]: 1:57
2017-09-26 12:15:40.324454+0200 myApp[6009:786485] TIC Read Status [1:0x0]: 1:57
2017-09-26 12:15:40.429959+0200 myApp[6009:786607] TIC Read Status [4:0x0]: 1:57
2017-09-26 12:15:40.429985+0200 myApp[6009:786607] TIC Read Status [4:0x0]: 1:57
2017-09-26 12:15:40.473050+0200 myApp[6009:786507] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-09-26 12:15:40.478608+0200 myApp[6009:786507] [MC] Reading from public effective user settings.
Firebase registration token: cAkYMzkcmIA:APA91bH7U9E3z7bS-OCf9kmFADRPdjlzsVScnhd_0Nk_INsHw1-ZmvxVyS1D5WYKX5155T7YFW21sbCVuE367REsugdAjqGvKxBWph091aHdiXRzF_zTCuoUGbQ5rFTv_yaVg5yYk1GC
2017-09-26 12:15:43.606715+0200 myApp[6009:786188] [MC] Lazy loading NSBundle MobileCoreServices.framework
2017-09-26 12:15:43.606985+0200 myApp[6009:786188] [MC] Loaded MobileCoreServices.framework
APNs token retrieved: 32 bytes
```

App don't retrieve notifications sent from the Firebase console but it retrieve the Firebase registration token...

Do you have an explanation ?

Thanks

  * Xcode version: 9
  * Firebase SDK version: 4.2.0

**Comment by berlininsomniac** [comment]
Same issue here.

**Comment by rsattar** [comment]
"BoringSSL" is an output by Xcode 9 when an SSL connection is established (which FCM and IID SDKs do, as others), but is not related to whether something is working or not. 

[There is a bug](https://github.com/firebase/firebase-ios-sdk/issues/254) which has been fixed related to when the APNs token is retrieved, and that should be coming out soon. I think what you're describing is related.

**Comment by Aurazion** [comment]
Thanks @rsattar, it works for me now. Waiting for the future release.

**Comment by mehransahandi** [comment]
i have a same problem how should i solve it?

**Comment by Aurazion** [comment]
@mehransahandi Here : https://github.com/firebase/firebase-ios-sdk/issues/315#issuecomment-333454986

**Comment by mehransahandi** [comment]
@Aurazion tnx sir, but how should I use pod 'FirebaseInstanceID', '2.0.0' ?
Im new to it

**Comment by paulb777** [comment]
Fix released today in Firebase 4.3.0, FirebaseMessaging 2.0.4, and FirebaseInstanceID 2.0.4

**Comment by jlandyr** [comment]
Hello @paulb777 , I'm testing Firebase 4.3.0 with Xcode 9 and iOS 11 but I have the same problem (TIC Read Status):

2017-10-04 18:18:29.854703+0200 flatfitapp[38450:1753669] [Firebase/Analytics][I-ACS023007] Firebase Analytics v.40004000 started
2017-10-04 18:18:29.888693+0200 flatfitapp[38450:1753669] [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2017-10-04 18:18:29.963718+0200 flatfitapp[38450:1753675] [BoringSSL] Function boringssl_context_get_peer_sct_list: line 1754 received sct extension length is less than sct data length
2017-10-04 18:18:30.096274+0200 flatfitapp[38450:1753675] TIC Read Status [1:0x0]: 1:57
2017-10-04 18:18:30.096436+0200 flatfitapp[38450:1753675] TIC Read Status [1:0x0]: 1:57
2017-10-04 18:18:31.120869+0200 flatfitapp[38450:1753386] [MC] Lazy loading NSBundle MobileCoreServices.framework
2017-10-04 18:18:31.121636+0200 flatfitapp[38450:1753386] [MC] Loaded MobileCoreServices.framework
2017-10-04 18:18:31.124366+0200 flatfitapp[38450:1753386] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/Bamby/Library/Developer/CoreSimulator/Devices/E9C887D4-F3FD-4E25-BB9C-B5B32D825B95/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles

**Comment by paulb777** [comment]
@jlandyr See https://github.com/firebase/firebase-ios-sdk/issues/314#issuecomment-332339019 above

**Comment by vanitaladkat** [comment]
I have installed firebase **version 4.4.0**. still getting the logs TIC Read Status [7:0x0]: 1:57

**Comment by sathya-Baman** [comment]
I am trying to send a Remote PushNotification


Xcode  Version 9.0 (9A235)
Developement Traget : 10.0

```
pod 'Firebase', '4.3.0'
pod 'FirebaseMessaging', '2.0.4'
pod 'FirebaseInstanceID', '2.0.4.'
```


```
[Firebase/Analytics][I-ACS023007] Firebase Analytics v.40003000 started
[Firebase/Analytics][I-ACS023007] Firebase Analytics v.40003000 started
[Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
<Notice> [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
*********************************************************************************************************************
FCM token: ecrBl5Cqe-s:APA91bEgEDv7R_avMASrcldSEUmiJNVjQBRZw0V2M767r05u_1_xlEkfssaFgEPlPxB4uwmqJ4t8BHYVNDvX2FiaqsZkQRrvvPnvRHhPUvAAniuGTeYQE0Q7qrNWEmINHzk9IYsCKaqG
*********************************************************************************************************************
- [BoringSSL] Function boringssl_context_get_peer_sct_list: line 1754 received sct extension length is less than sct data length
- [MC] Lazy loading NSBundle MobileCoreServices.framework
- [MC] Loaded MobileCoreServices.framework
- [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
- refreshPreferences: HangTracerEnabled: 0
- refreshPreferences: HangTracerDuration: 500
- refreshPreferences: ActivationLoggingEnabled: 0 ActivationLoggingTaskedOffByDA:0
- TIC Read Status [1:0x0]: 1:57
- TIC Read Status [1:0x0]: 1:57
```

**Comment by whereiswhere** [comment]
I'm using Firebase 4.5.0, still got this [BoringSSL] error.

**Comment by sathya-Baman** [comment]
Hy i fixed the issue by using

```
        pod 'Firebase/Core', '4.0.4'
        pod 'Firebase/Database', '4.0.4'
        pod 'Firebase/Messaging', '4.0.4'
        pod 'FirebaseInstanceID', '2.0.0'
```

And adding this method in appDelegate

```
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Messaging.messaging().apnsToken = deviceToken
        Messaging.messaging().subscribe(toTopic: hubId)
    }

func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any]) {
        print(userInfo)
    }
    
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any],
                     fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        print(userInfo)
        let aps = userInfo["aps"] as! NSDictionary
        let message = aps["alert"]  as? String
        let msglabel = "label"
        print(aps["alert"]  as? String ?? "")
        completionHandler(UIBackgroundFetchResult.newData)
   
    }
```

It works fine for me in background and foreground

**Comment by YoungyoungX** [comment]
Same problem, please fix it!

**Comment by imstkgp** [comment]
I am facing the same issue.

**Comment by dgaedcke** [comment]
Yes....I'm Using Firebase (4.6.0) and I'm hitting this today in Xcode 9

**Comment by meaning-matters** [comment]
Does someone have a fix for this 4 months later?

Using Firebase (4.11.0)
Using FirebaseAnalytics (4.1.0)
Using FirebaseCore (4.0.18)
Using FirebaseInstanceID (2.0.10)
Using GoogleToolboxForMac (2.1.3)
Using nanopb (0.3.8)

**Comment by paulb777** [comment]
Closing due to lack of recent activity. Please open a new issue if this is occurring on Firebase 5.x.

**Comment by rrecio** [comment]
I'm on Firebase 5.7.0 (Core, Messaging, RemoteConfig) and still get those errors:

```
2018-09-09 21:20:31.283496-0300 Fuelzee Dev[39625:370743] [BoringSSL] boringssl_session_errorlog(224) [C1.1:2][0x7fd99851d330] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.283650-0300 Fuelzee Dev[39625:370743] [BoringSSL] boringssl_session_handshake_error_print(205) [C1.1:2][0x7fd99851d330] 140572539010760:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.283742-0300 Fuelzee Dev[39625:370743] [BoringSSL] boringssl_session_errorlog(224) [C1.1:2][0x7fd99851d330] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.283824-0300 Fuelzee Dev[39625:370743] [BoringSSL] boringssl_session_handshake_error_print(205) [C1.1:2][0x7fd99851d330] 140572539010760:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.583782-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_errorlog(224) [C6.1:2][0x7fd998449d00] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.584102-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_handshake_error_print(205) [C6.1:2][0x7fd998449d00] 140572540514616:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.584827-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_errorlog(224) [C6.1:2][0x7fd998449d00] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.584934-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_handshake_error_print(205) [C6.1:2][0x7fd998449d00] 140572540514616:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.590751-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_errorlog(224) [C5.1:2][0x7fd99863f950] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.591086-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_handshake_error_print(205) [C5.1:2][0x7fd99863f950] 140572540514616:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.591918-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_errorlog(224) [C5.1:2][0x7fd99863f950] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.592280-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_handshake_error_print(205) [C5.1:2][0x7fd99863f950] 140572540514616:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.595714-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_errorlog(224) [C6.1:2][0x7fd998449d00] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.596092-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_handshake_error_print(205) [C6.1:2][0x7fd998449d00] 140572540514616:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.596217-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_errorlog(224) [C6.1:2][0x7fd998449d00] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.596353-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_handshake_error_print(205) [C6.1:2][0x7fd998449d00] 140572540514616:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.601358-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_errorlog(224) [C5.1:2][0x7fd99863f950] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.601478-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_handshake_error_print(205) [C5.1:2][0x7fd99863f950] 140572540514616:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.601951-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_errorlog(224) [C5.1:2][0x7fd99863f950] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.602586-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_handshake_error_print(205) [C5.1:2][0x7fd99863f950] 140572540514616:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.715709-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_errorlog(224) [C8.1:2][0x7fd9986353d0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.715871-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_handshake_error_print(205) [C8.1:2][0x7fd9986353d0] 140572540514616:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.716055-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_errorlog(224) [C8.1:2][0x7fd9986353d0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.716349-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_handshake_error_print(205) [C8.1:2][0x7fd9986353d0] 140572540514616:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.718178-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_errorlog(224) [C8.1:2][0x7fd9986353d0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.718548-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_handshake_error_print(205) [C8.1:2][0x7fd9986353d0] 140572540514616:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.718947-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_errorlog(224) [C8.1:2][0x7fd9986353d0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.719115-0300 Fuelzee Dev[39625:370835] [BoringSSL] boringssl_session_handshake_error_print(205) [C8.1:2][0x7fd9986353d0] 140572540514616:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.701948-0300 Fuelzee Dev[39625:370733]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2018-09-09 21:20:31.777897-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_errorlog(224) [C2.1:2][0x7fd99862aa90] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.778023-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_handshake_error_print(205) [C2.1:2][0x7fd99862aa90] 140572542692696:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.778195-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_errorlog(224) [C2.1:2][0x7fd99862aa90] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.778387-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_handshake_error_print(205) [C2.1:2][0x7fd99862aa90] 140572542692696:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.780019-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_errorlog(224) [C2.1:2][0x7fd99862aa90] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.780316-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_handshake_error_print(205) [C2.1:2][0x7fd99862aa90] 140572542692696:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.780702-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_errorlog(224) [C2.1:2][0x7fd99862aa90] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:31.780812-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_handshake_error_print(205) [C2.1:2][0x7fd99862aa90] 140572542692696:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:31.829525-0300 Fuelzee Dev[39625:370835] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C6.1:2][0x7fd998449d00] get output frames failed, state 8196
2018-09-09 21:20:31.830074-0300 Fuelzee Dev[39625:370835] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C6.1:2][0x7fd998449d00] get output frames failed, state 8196
2018-09-09 21:20:31.830670-0300 Fuelzee Dev[39625:370835] TIC Read Status [6:0x0]: 1:57
2018-09-09 21:20:31.830904-0300 Fuelzee Dev[39625:370835] TIC Read Status [6:0x0]: 1:57
2018-09-09 21:20:31.803812-0300 Fuelzee Dev[39625:370733] 5.7.0 - [Firebase/Core][I-COR000008] The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to 'com.fuelzee.Fuelzee'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
2018-09-09 21:20:31.909347-0300 Fuelzee Dev[39625:370733] 5.7.0 - [Firebase/Messaging][I-FCM012002] Error in application:didFailToRegisterForRemoteNotificationsWithError: remote notifications are not supported in the simulator
2018-09-09 21:20:32.020277-0300 Fuelzee Dev[39625:370766] WF: === Starting WebFilter logging for process Fuelzee Dev
2018-09-09 21:20:32.020508-0300 Fuelzee Dev[39625:370766] WF: _userSettingsForUser : (null)
2018-09-09 21:20:32.020601-0300 Fuelzee Dev[39625:370766] WF: _WebFilterIsActive returning: NO
2018-09-09 21:20:32.166965-0300 Fuelzee Dev[39625:370760] [BoringSSL] boringssl_session_errorlog(224) [C9.1:2][0x7fd99848d120] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:32.167173-0300 Fuelzee Dev[39625:370760] [BoringSSL] boringssl_session_handshake_error_print(205) [C9.1:2][0x7fd99848d120] 140572541390664:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:32.167696-0300 Fuelzee Dev[39625:370760] [BoringSSL] boringssl_session_errorlog(224) [C9.1:2][0x7fd99848d120] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:32.167993-0300 Fuelzee Dev[39625:370760] [BoringSSL] boringssl_session_handshake_error_print(205) [C9.1:2][0x7fd99848d120] 140572541390664:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:32.170269-0300 Fuelzee Dev[39625:370760] [BoringSSL] boringssl_session_errorlog(224) [C9.1:2][0x7fd99848d120] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:32.170543-0300 Fuelzee Dev[39625:370760] [BoringSSL] boringssl_session_handshake_error_print(205) [C9.1:2][0x7fd99848d120] 140572541390664:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:32.170884-0300 Fuelzee Dev[39625:370760] [BoringSSL] boringssl_session_errorlog(224) [C9.1:2][0x7fd99848d120] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:32.171206-0300 Fuelzee Dev[39625:370760] [BoringSSL] boringssl_session_handshake_error_print(205) [C9.1:2][0x7fd99848d120] 140572541390664:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:32.642807-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_errorlog(224) [C10.1:2][0x7fd9986306b0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:32.642934-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_handshake_error_print(205) [C10.1:2][0x7fd9986306b0] 140572542116184:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:32.643128-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_errorlog(224) [C10.1:2][0x7fd9986306b0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:32.643215-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_handshake_error_print(205) [C10.1:2][0x7fd9986306b0] 140572542116184:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:32.646116-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_errorlog(224) [C10.1:2][0x7fd9986306b0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:32.646220-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_handshake_error_print(205) [C10.1:2][0x7fd9986306b0] 140572542116184:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:32.646389-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_errorlog(224) [C10.1:2][0x7fd9986306b0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:32.649000-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_handshake_error_print(205) [C10.1:2][0x7fd9986306b0] 140572542116184:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:32.665774-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_errorlog(224) [C11.1:2][0x7fd9987a3a20] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:32.665987-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_handshake_error_print(205) [C11.1:2][0x7fd9987a3a20] 140572542116184:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:32.666217-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_errorlog(224) [C11.1:2][0x7fd9987a3a20] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:32.666611-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_handshake_error_print(205) [C11.1:2][0x7fd9987a3a20] 140572542116184:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:32.668901-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_errorlog(224) [C11.1:2][0x7fd9987a3a20] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:32.668997-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_handshake_error_print(205) [C11.1:2][0x7fd9987a3a20] 140572542116184:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:32.669103-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_errorlog(224) [C11.1:2][0x7fd9987a3a20] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:32.669184-0300 Fuelzee Dev[39625:370742] [BoringSSL] boringssl_session_handshake_error_print(205) [C11.1:2][0x7fd9987a3a20] 140572542116184:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:33.224705-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_errorlog(224) [C12.1:2][0x7fd9984a3af0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:33.225021-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_handshake_error_print(205) [C12.1:2][0x7fd9984a3af0] 140572542692696:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:33.225271-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_errorlog(224) [C12.1:2][0x7fd9984a3af0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:33.225378-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_handshake_error_print(205) [C12.1:2][0x7fd9984a3af0] 140572542692696:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:33.227254-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_errorlog(224) [C12.1:2][0x7fd9984a3af0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:33.227371-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_handshake_error_print(205) [C12.1:2][0x7fd9984a3af0] 140572542692696:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-09-09 21:20:33.232122-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_errorlog(224) [C12.1:2][0x7fd9984a3af0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-09-09 21:20:33.232243-0300 Fuelzee Dev[39625:370747] [BoringSSL] boringssl_session_handshake_error_print(205) [C12.1:2][0x7fd9984a3af0] 140572542692696:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
Config fetched!
2018-09-09 21:22:33.003818-0300 Fuelzee Dev[39625:370741] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C11.1:2][0x7fd9987a3a20] get output frames failed, state 8196
2018-09-09 21:22:33.003965-0300 Fuelzee Dev[39625:370741] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C11.1:2][0x7fd9987a3a20] get output frames failed, state 8196
2018-09-09 21:22:33.004806-0300 Fuelzee Dev[39625:370741] TIC Read Status [11:0x0]: 1:57
2018-09-09 21:22:33.005818-0300 Fuelzee Dev[39625:370741] TIC Read Status [11:0x0]: 1:57
2018-09-09 21:24:31.473517-0300 Fuelzee Dev[39625:370772] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x7fd99851d330] get output frames failed, state 8196
2018-09-09 21:24:31.473929-0300 Fuelzee Dev[39625:370772] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x7fd99851d330] get output frames failed, state 8196
2018-09-09 21:24:31.474845-0300 Fuelzee Dev[39625:370772] TIC Read Status [1:0x0]: 1:57
2018-09-09 21:24:31.475415-0300 Fuelzee Dev[39625:370772] TIC Read Status [1:0x0]: 1:57
2018-09-09 21:24:31.870042-0300 Fuelzee Dev[39625:370741] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C5.1:2][0x7fd99863f950] get output frames failed, state 8196
2018-09-09 21:24:31.870367-0300 Fuelzee Dev[39625:370741] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C5.1:2][0x7fd99863f950] get output frames failed, state 8196
2018-09-09 21:24:31.871243-0300 Fuelzee Dev[39625:370741] TIC Read Status [5:0x0]: 1:57
2018-09-09 21:24:31.871719-0300 Fuelzee Dev[39625:370741] TIC Read Status [5:0x0]: 1:57
2018-09-09 21:24:33.307636-0300 Fuelzee Dev[39625:370741] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C12.1:2][0x7fd9984a3af0] get output frames failed, state 8196
2018-09-09 21:24:33.307913-0300 Fuelzee Dev[39625:370741] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C12.1:2][0x7fd9984a3af0] get output frames failed, state 8196
2018-09-09 21:24:33.308507-0300 Fuelzee Dev[39625:370741] TIC Read Status [12:0x0]: 1:57
2018-09-09 21:24:33.308682-0300 Fuelzee Dev[39625:370741] TIC Read Status [12:0x0]: 1:57
```
