### ISSUE TITLE
157240581: Can't able to create short URL.

### ISSUE THREAD

**Issue by manomuthu-optisol** [firebase/firebase-ios-sdk#5450]
While am trying to create a short URL from Long dynamic Link. All the URL, error, and warnings are returning nil in the below method.

`linkBuilder!.shorten() { url, warnings, error in
            guard let url = url, error != nil else { return }
            print("The short URL is: \(url)")
        }`

Thanks in advance.

**Comment by manomuthu-optisol** [comment]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4
  * Firebase SDK version: 6.6.1
  * Firebase Component: DynamicLinks (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.16.0
  * Installation method: `CocoaPods` (select one)

### [REQUIRED] Step 2: Describe the problem

#### Steps to reproduce:

While am trying to create a short URL from Long dynamic Link. All the URL, error, and warnings are returning nil. Whereas am getting long dynamic link

#### Relevant Code:

`guard let link = URL(string: "https://*****.com/data?loopId=1234") else { return }
        let dynamicLinksDomainURIPrefix = "https://******.page.link"
        let linkBuilder = DynamicLinkComponents(link: link, domainURIPrefix: dynamicLinksDomainURIPrefix)
        linkBuilder!.iOSParameters = DynamicLinkIOSParameters(bundleID: "com.***.****")
        linkBuilder?.iOSParameters?.appStoreID = "******"
        linkBuilder?.options?.pathLength = .short
        
        guard let longDynamicLink = linkBuilder?.url else { return }
        print("The long URL is: \(longDynamicLink)")
        
        linkBuilder!.shorten() { url, warnings, error in
            guard let url = url, error != nil else { return }
            print("The short URL is: \(url)")
        }`

**Comment by morganchen12** [comment]
Are you able to generate short links via any other means (i.e. the [rest API](https://firebase.google.com/docs/reference/dynamic-links/link-shortener))?

**Comment by manomuthu-optisol** [comment]
Ya while I have tried to generate sort link using rest API. And it's working fine.

**Comment by Ankish** [comment]
Stuck with same issue. I traced the code:

In 
+ (void)shortenURL:(NSURL *)url
           options:(FIRDynamicLinkComponentsOptions *)options
        completion:(FIRDynamicLinkShortenerCompletion)completion {


It reaches the last step

 dispatch_async(dispatch_get_main_queue(), ^{
                 completion(shortURL, warnings, error); // correct shortURL is c present 
               });

But in our target :
linkBuilder.shorten() { url, warnings, error in // all is nil
Something is wrong with completion the url turns to nil automatically

**Comment by ncooke3** [comment]
Hi @manomuthu-optisol 

When trying to recreate your issue, I realized a few things that might help:

```
guard let url = url, error != nil else { 
    return 
} 
print("The short URL is: \(url)") }
```
The code above checks if **both** `url` and `error` are non-null, which should never be possible. Having a valid non-null `url` means that you would not have an `error`. Changing `error != nil` to `error == nil` should solve the case you are checking for.

Hi @Ankish, can you please try the below code to figure out if all values print `nil` at runtime.

Perhaps try adding some print statements like these:

```
linkBuilder.shorten() { url, warnings, error in
   if let url = url {
      print("URL is \(url)")
   } else {
      print("URL is nil")
   }

   if let error = error {
      print("Error is \(error)")
   } else {
      print("Error is nil")
   }

   if let warnings = warnings {
      print("Warnings are \(warnings)")
   } else {
      print("Warnings are nil")
   }
}
```

If using the above code still results in all values being `nil`, let us know and we can move forward and get to the bottom of this issue!

**Comment by Ankish** [comment]
Yes , the url , warnings and errors all are nil.

**Comment by ncooke3** [comment]
Hi @Ankish, 

I'm having some trouble trying to reproduce the issue. Do you happen to have a reproducible example? Or perhaps provide some more context about the case where the issue is occurring? I'd be happy to investigate this further.

**Comment by Ankish** [comment]
Hi,

I updated SDK and tried again. Shorten URL seems to work now. Thanks

**Comment by OscarHedeby** [comment]
I had the same error in my code, and even after pod update and install the problem persisted. It's not a problem with firebase, it's some weirdness with Xcode. For anyone else who have this problem, this should fix it.

`linkBuilder.shorten() { url, warnings, error in
            guard let url = URL(string: (url as NSURL?)?.absoluteString ?? "") else { return }
}`

By casting the URL as a NSURL and back to a URL fixed the error.
