### ISSUE TITLE
FR: Add a retry option to upload-symbols

### ISSUE THREAD

**Issue by jostster** [firebase/firebase-ios-sdk#6991]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: 7.0.0
  * Installation method: ` Swift Package Manager`
  * Firebase Component: Crashlytics

### [REQUIRED] Step 2: Describe the problem
Starting on Monday the 16th, when uploading DSYMs, it fails with the following errors. After a few attempts, some uploads succeed. Still seems to be happening, but less frequent. Looking at the Firebase Community Slack, several other people are experiencing this issue as well.

```
[06:28:22]: ▸ Fetching upload-symbols settings...
[06:28:22]: ▸ error: Could not fetch upload-symbols settings: The request timed out.
[06:28:22]: ▸ Command PhaseScriptExecution failed with a nonzero exit code
```
Today running the commands manually (2nd option found [here](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios#upload-dsyms)) it succeeded for me, however this morning we kicked off 2 builds. One at 10:55 and another at 10:56. The 10:55 failed with the above error, while the second one succeeded. Seems to be much less frequent now, but still sporadic.

#### Steps to reproduce:

What happened? How can we make the problem occur?
Run a build and uploads dsyms, or just upload existing dsyms. Seems to be sporadic.

#### Suggestions:

Add a fallback to `upload-symbols` that will attempt a retry x number of times before a failure is triggered. This would allow CI systems to try multiple times before failing and requiring the end user to kick off multiple builds in hopes of getting one that successfully uploads.

**Comment by cvaghela** [comment]
This should be fixed now

**Comment by paulb777** [comment]
Yes, according to https://status.firebase.google.com/incident/Crashlytics/20006, this should be resolved. Thanks for the report.

**Comment by jostster** [comment]
@paulb777 would we be able to use the suggestion as a FR?

**Comment by paulb777** [comment]
@jostster Done. I updated the title and labels.

**Comment by elenadoty** [comment]
Hi @jostster ,
Upload symbols currently retries 10 times by default. Have you been running into this issue still?
