### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_GULAppEnvironmentUtil

### ISSUE THREAD

**Issue by khoogheem** [firebase/firebase-ios-sdk#8137]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 8.9
  * Installation method: CocoaPods)
  * Firebase Component: Crashlytiics

### [REQUIRED] Step 2: Describe the problem

Undefined symbol: _OBJC_CLASS_$_GULAppEnvironmentUtil

#### Steps to reproduce:

Build using 8.0.0

![Screen Shot 2021-05-23 at 12 07 41 PM](https://user-images.githubusercontent.com/957336/119269871-7e79ef00-bbbf-11eb-9beb-ccb90c970450.png)

**Comment by rizafran** [comment]
Thanks for reporting, @khoogheem. Can you share the detailed steps reproducing the issue? Also, a `pod update` may be required to ensure all recent dependencies are being pulled in. Thanks.

**Comment by khoogheem** [comment]
Pod updated project all Firebase were set to 8.0.0
Clean project
Build project

**Comment by morganchen12** [comment]
Can you share your Podfile.lock?

**Comment by morganchen12** [comment]
Also, are you building with `use_frameworks!` and _not_ using `:linkage => :static`?

**Comment by khoogheem** [comment]
Correct

**Comment by khoogheem** [comment]
this is what we add in:
```
def firebase
  # Add the pod for Firebase Crashlytics
  pod 'Firebase/Crashlytics'
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # Firebase Performance
  pod 'Firebase/Performance'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
end
```

**Comment by morganchen12** [comment]
Can you share the full build log output? It's likely this is occurring in a submodule of your app (i.e. one of your dependencies) and not the app itself.

**Comment by khoogheem** [comment]
if you want the lock file send me an email that I can sent it too.. vs posting here

**Comment by khoogheem** [comment]
Ok.. if I use:
```
   pod 'Firebase'
  pod 'Firebase/Crashlytics'
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # Firebase Performance
  pod 'Firebase/Performance'
  ```
  
Then it works... which is odd as the only thing I see different between the two locks is core and analytics are swapped
and after I remove it it works as well.. so I am not sure what is going on...

**Comment by morganchen12** [comment]
You should be able to fix this temporarily by going to your `Pods.xcodeproj` project and adding the GoogleUtilities framework to the FirebaseCrashlytics target's Link Binary with Libraries build phase.

A more permanent fix may need to come from CocoaPods or Firebase; some further investigation is required.

**Comment by andreyoshev** [comment]
Same

  pod 'Firebase/AnalyticsWithoutAdIdSupport'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'

**Comment by fmalekpour** [comment]
Had the same issue, XCode -> Product -> Clean Build Folder fixed it.

**Comment by paulb777** [comment]
Marking as needs-info for a repro case from a clean build environment

**Comment by tessSnap** [comment]
> Had the same issue, XCode -> Product -> Clean Build Folder fixed it.

Thank you, I was building an an IOS version of my Flutter App. After Running in Android Studio I stopped the run and Switched to Xcode to run the App and saw the error. This fixed it for me

**Comment by billdevoe** [comment]
Just a quick add on that I'm seeing the same problem. I updated all my gems, I went through and updated my Podfile (because I was still using the pre-iOS 14 stuff) and I'm seeing this issue.

Here's my current Podfile:

> platform :ios, '11.0'
> 
> # install! 'cocoapods',
> #          :deterministic_uuids => false
> 
> # add the Firebase pod for Google Analytics
> pod 'Firebase'
> pod 'Firebase/Crashlytics'
> pod 'Firebase/Analytics'
> pod 'Firebase/Performance'
> 
> pod 'Google-Mobile-Ads-SDK'

I added the "pod 'Firebase'" because that seemed to be a difference but there was no change. I was receiving the error before I added that.

I've cleaned and rebuilt - several times - and this error is persisting.

Not sure what else to do at this point. Thanks.

**Comment by billdevoe** [comment]
> Not sure what else to do at this point. Thanks.

Here's the Podfile.lock in case it helps:

> PODS:
>   - Firebase (8.1.0):
>     - Firebase/Core (= 8.1.0)
>   - Firebase/Core (8.1.0):
>     - Firebase/CoreOnly
>     - FirebaseAnalytics (~> 8.1.0)
>   - Firebase/CoreOnly (8.1.0):
>     - FirebaseCore (= 8.1.0)
>   - FirebaseAnalytics (8.1.0):
>     - FirebaseAnalytics/AdIdSupport (= 8.1.0)
>     - FirebaseCore (~> 8.0)
>     - FirebaseInstallations (~> 8.0)
>     - GoogleUtilities/AppDelegateSwizzler (~> 7.4)
>     - GoogleUtilities/MethodSwizzler (~> 7.4)
>     - GoogleUtilities/Network (~> 7.4)
>     - "GoogleUtilities/NSData+zlib (~> 7.4)"
>     - nanopb (~> 2.30908.0)
>   - FirebaseAnalytics/AdIdSupport (8.1.0):
>     - FirebaseAnalytics/Base (= 8.1.0)
>     - FirebaseCore (~> 8.0)
>     - FirebaseInstallations (~> 8.0)
>     - GoogleAppMeasurement (= 8.1.0)
>     - GoogleUtilities/AppDelegateSwizzler (~> 7.4)
>     - GoogleUtilities/MethodSwizzler (~> 7.4)
>     - GoogleUtilities/Network (~> 7.4)
>     - "GoogleUtilities/NSData+zlib (~> 7.4)"
>     - nanopb (~> 2.30908.0)
>   - FirebaseAnalytics/Base (8.1.0):
>     - FirebaseCore (~> 8.0)
>     - FirebaseInstallations (~> 8.0)
>     - GoogleUtilities/AppDelegateSwizzler (~> 7.4)
>     - GoogleUtilities/MethodSwizzler (~> 7.4)
>     - GoogleUtilities/Network (~> 7.4)
>     - "GoogleUtilities/NSData+zlib (~> 7.4)"
>     - nanopb (~> 2.30908.0)
>   - FirebaseCore (8.1.0):
>     - FirebaseCoreDiagnostics (~> 8.0)
>     - GoogleUtilities/Environment (~> 7.4)
>     - GoogleUtilities/Logger (~> 7.4)
>   - FirebaseCoreDiagnostics (8.1.0):
>     - GoogleDataTransport (~> 9.0)
>     - GoogleUtilities/Environment (~> 7.4)
>     - GoogleUtilities/Logger (~> 7.4)
>     - nanopb (~> 2.30908.0)
>   - FirebaseInstallations (8.1.0):
>     - FirebaseCore (~> 8.0)
>     - GoogleUtilities/Environment (~> 7.4)
>     - GoogleUtilities/UserDefaults (~> 7.4)
>     - PromisesObjC (~> 1.2)
>   - Google-Mobile-Ads-SDK (8.5.0):
>     - GoogleAppMeasurement (< 9.0, >= 7.0)
>     - GoogleUserMessagingPlatform (>= 1.1)
>   - GoogleAppMeasurement (8.1.0):
>     - GoogleAppMeasurement/AdIdSupport (= 8.1.0)
>     - GoogleUtilities/AppDelegateSwizzler (~> 7.4)
>     - GoogleUtilities/MethodSwizzler (~> 7.4)
>     - GoogleUtilities/Network (~> 7.4)
>     - "GoogleUtilities/NSData+zlib (~> 7.4)"
>     - nanopb (~> 2.30908.0)
>   - GoogleAppMeasurement/AdIdSupport (8.1.0):
>     - GoogleUtilities/AppDelegateSwizzler (~> 7.4)
>     - GoogleUtilities/MethodSwizzler (~> 7.4)
>     - GoogleUtilities/Network (~> 7.4)
>     - "GoogleUtilities/NSData+zlib (~> 7.4)"
>     - nanopb (~> 2.30908.0)
>   - GoogleDataTransport (9.0.1):
>     - GoogleUtilities/Environment (~> 7.2)
>     - nanopb (~> 2.30908.0)
>     - PromisesObjC (~> 1.2)
>   - GoogleUserMessagingPlatform (2.0.0)
>   - GoogleUtilities/AppDelegateSwizzler (7.4.1):
>     - GoogleUtilities/Environment
>     - GoogleUtilities/Logger
>     - GoogleUtilities/Network
>   - GoogleUtilities/Environment (7.4.1):
>     - PromisesObjC (~> 1.2)
>   - GoogleUtilities/Logger (7.4.1):
>     - GoogleUtilities/Environment
>   - GoogleUtilities/MethodSwizzler (7.4.1):
>     - GoogleUtilities/Logger
>   - GoogleUtilities/Network (7.4.1):
>     - GoogleUtilities/Logger
>     - "GoogleUtilities/NSData+zlib"
>     - GoogleUtilities/Reachability
>   - "GoogleUtilities/NSData+zlib (7.4.1)"
>   - GoogleUtilities/Reachability (7.4.1):
>     - GoogleUtilities/Logger
>   - GoogleUtilities/UserDefaults (7.4.1):
>     - GoogleUtilities/Logger
>   - nanopb (2.30908.0):
>     - nanopb/decode (= 2.30908.0)
>     - nanopb/encode (= 2.30908.0)
>   - nanopb/decode (2.30908.0)
>   - nanopb/encode (2.30908.0)
>   - PromisesObjC (1.2.12)
> 
> DEPENDENCIES:
>   - Firebase
>   - Google-Mobile-Ads-SDK
> 
> SPEC REPOS:
>   trunk:
>     - Firebase
>     - FirebaseAnalytics
>     - FirebaseCore
>     - FirebaseCoreDiagnostics
>     - FirebaseInstallations
>     - Google-Mobile-Ads-SDK
>     - GoogleAppMeasurement
>     - GoogleDataTransport
>     - GoogleUserMessagingPlatform
>     - GoogleUtilities
>     - nanopb
>     - PromisesObjC
> 
> SPEC CHECKSUMS:
>   Firebase: b5956acddaaa53a6c292bec00649fadd18367344
>   FirebaseAnalytics: e812eaae316ba8914b1ef06bef18f11efc1f56c6
>   FirebaseCore: 389c4ce9a7cce4a7e25eb22326b4bee0050557b2
>   FirebaseCoreDiagnostics: 3e249cee3de5c5f9cfd6cc2a19997231286fec11
>   FirebaseInstallations: 7f31798a8198c354eadcb87176d2090b62edc187
>   Google-Mobile-Ads-SDK: 6f5c41bf73db1656e5b203ba9c31e3d0899a128d
>   GoogleAppMeasurement: 9ff7b9e23cced93a5a41736c09bdeb5b5b7fb111
>   GoogleDataTransport: 04c3e9a480bbcaa2ec3f5d27f1cdeb6a92f20c8d
>   GoogleUserMessagingPlatform: ab890ce5f6620f293a21b6bdd82e416a2c73aeca
>   GoogleUtilities: f8a43108b38a68eebe8b3540e1f4f2d28843ce20
>   nanopb: a0ba3315591a9ae0a16a309ee504766e90db0c96
>   PromisesObjC: 3113f7f76903778cf4a0586bd1ab89329a0b7b97
> 
> PODFILE CHECKSUM: 04b61b1dfa045b1367ca868c5bb7465e91960528
> 
> COCOAPODS: 1.10.1
>

**Comment by VadimZhuk0v** [comment]
Who use flutter
Don't add strings like
`pod 'Firebase/Analytics'`
to your podfile
Add firebase_analytics to pubspec instead

**Comment by andreyoshev** [comment]
@morganchen12 It works, but the solution is _temporary_.

**Comment by morganchen12** [comment]
For a more permanent workaround, you can add the dependency with the missing symbols directly to your target in your Podfile.

```
pod 'GoogleUtilities'
```

**Comment by paulb777** [comment]
If someone can share a reproducible example of this issue, I'll see if I can find the root cause.

**Comment by billdevoe** [comment]
> For a more permanent workaround, you can add the dependency with the missing symbols directly to your target in your Podfile.
> 
> ```
> pod 'GoogleUtilities'
> ```

I added this but still have the crashlytics error (even after a clean and fresh build). If I remove Crashlytics, things compile properly. I did try the temporary fix you mentioned earlier about adding GoogleUtilities to the Link Binary with Libraries, but still saw the same error.

Overall, at this point I'm just excluding it.

**Comment by morganchen12** [comment]
@paulb777 similar linker error in https://github.com/firebase/FirebaseUI-iOS/pull/969.

**Comment by paulb777** [comment]
Thanks @morganchen12. I'll take a look in the next day or two

**Comment by paulb777** [comment]
The FirebaseUI issue turns out to be a test infrastructure issue specific to FirebaseUI. See the firebase/FirebaseUI-iOS#969 for details.

So we're still looking for a reproducible example.

**Comment by mentalGrowthNick** [comment]
Was able to remove the issue by updating my pod file from this:
```
pod 'Firebase/Core'
pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'
```

To this:
```
pod 'Firebase'
pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'
pod 'Firebase/Performance'
```

`Firebase/Performancev` installed GoogleUtilities, which might be the key. 

After running pod install, I cleaned my build folder, then deleted derived data for the app.
After waiting for index to finish &. then building the project, the issue went away for me.

**Comment by billdevoe** [comment]
Thanks for the note @mentalGrowthNick.

I do have Performance in my Podfile but I still get this issue even after doing all of the steps you mentioned. When I did the pod update I noticed that many of the pods I have updated to 8.2.0, but even with the new changes and everything, this problem persists. 

As of today, I'm just not including Crashlytics at all and it's building. I would like to get it added but can't seem to get it working at the moment.

**Comment by morganchen12** [comment]
@billdevoe can you share your project?

**Comment by billdevoe** [comment]
Hi @morganchen12 - I don't have anything simple that I could share at this point (this is a workspace/project for a published game). I will try to see if I can replicate the issue with a project that I could share.

**Comment by billdevoe** [comment]
So I just created a new project, added the Pods (shown below) and then tried to build the workspace - same error.

This is about as basic as it gets.

Podfile:

> # Uncomment the next line to define a global platform for your project
> 
> platform :ios, '12.1'
> 
> # install! 'cocoapods',
> #          :deterministic_uuids => false
> 
> # add the Firebase pod for Google Analytics
> pod 'Firebase'
> # pod 'GoogleUtilities'
> pod 'Firebase/Crashlytics'
> pod 'Firebase/Analytics'
> pod 'Firebase/Performance'
> 
> pod 'Google-Mobile-Ads-SDK'
> 
> target 'Firebase Test App' do
>   # Comment the next line if you don't want to use dynamic frameworks
>   use_frameworks!
> 
>   # Pods for Firebase Test App
> 
> end
> 

Podfile.lock:

> PODS:
>   - Firebase (8.2.0):
>     - Firebase/Core (= 8.2.0)
>   - Firebase/Analytics (8.2.0):
>     - Firebase/Core
>   - Firebase/Core (8.2.0):
>     - Firebase/CoreOnly
>     - FirebaseAnalytics (~> 8.2.0)
>   - Firebase/CoreOnly (8.2.0):
>     - FirebaseCore (= 8.2.0)
>   - Firebase/Crashlytics (8.2.0):
>     - Firebase/CoreOnly
>     - FirebaseCrashlytics (~> 8.2.0)
>   - Firebase/Performance (8.2.0):
>     - Firebase/CoreOnly
>     - FirebasePerformance (~> 8.2.0)
>   - FirebaseABTesting (8.2.0):
>     - FirebaseCore (~> 8.0)
>   - FirebaseAnalytics (8.2.0):
>     - FirebaseAnalytics/AdIdSupport (= 8.2.0)
>     - FirebaseCore (~> 8.0)
>     - FirebaseInstallations (~> 8.0)
>     - GoogleUtilities/AppDelegateSwizzler (~> 7.4)
>     - GoogleUtilities/MethodSwizzler (~> 7.4)
>     - GoogleUtilities/Network (~> 7.4)
>     - "GoogleUtilities/NSData+zlib (~> 7.4)"
>     - nanopb (~> 2.30908.0)
>   - FirebaseAnalytics/AdIdSupport (8.2.0):
>     - FirebaseCore (~> 8.0)
>     - FirebaseInstallations (~> 8.0)
>     - GoogleAppMeasurement (= 8.2.0)
>     - GoogleUtilities/AppDelegateSwizzler (~> 7.4)
>     - GoogleUtilities/MethodSwizzler (~> 7.4)
>     - GoogleUtilities/Network (~> 7.4)
>     - "GoogleUtilities/NSData+zlib (~> 7.4)"
>     - nanopb (~> 2.30908.0)
>   - FirebaseCore (8.2.0):
>     - FirebaseCoreDiagnostics (~> 8.0)
>     - GoogleUtilities/Environment (~> 7.4)
>     - GoogleUtilities/Logger (~> 7.4)
>   - FirebaseCoreDiagnostics (8.2.0):
>     - GoogleDataTransport (~> 9.0)
>     - GoogleUtilities/Environment (~> 7.4)
>     - GoogleUtilities/Logger (~> 7.4)
>     - nanopb (~> 2.30908.0)
>   - FirebaseCrashlytics (8.2.0):
>     - FirebaseCore (~> 8.0)
>     - FirebaseInstallations (~> 8.0)
>     - GoogleDataTransport (~> 9.0)
>     - nanopb (~> 2.30908.0)
>     - PromisesObjC (~> 1.2)
>   - FirebaseInstallations (8.2.0):
>     - FirebaseCore (~> 8.0)
>     - GoogleUtilities/Environment (~> 7.4)
>     - GoogleUtilities/UserDefaults (~> 7.4)
>     - PromisesObjC (~> 1.2)
>   - FirebasePerformance (8.2.0):
>     - FirebaseCore (~> 8.0)
>     - FirebaseInstallations (~> 8.0)
>     - FirebaseRemoteConfig (~> 8.0)
>     - GoogleDataTransport (~> 9.0)
>     - GoogleUtilities/Environment (~> 7.4)
>     - GoogleUtilities/ISASwizzler (~> 7.4)
>     - GoogleUtilities/MethodSwizzler (~> 7.4)
>     - Protobuf (~> 3.15)
>   - FirebaseRemoteConfig (8.2.0):
>     - FirebaseABTesting (~> 8.0)
>     - FirebaseCore (~> 8.0)
>     - FirebaseInstallations (~> 8.0)
>     - GoogleUtilities/Environment (~> 7.4)
>     - "GoogleUtilities/NSData+zlib (~> 7.4)"
>   - Google-Mobile-Ads-SDK (8.7.0):
>     - GoogleAppMeasurement (< 9.0, >= 7.0)
>     - GoogleUserMessagingPlatform (>= 1.1)
>   - GoogleAppMeasurement (8.2.0):
>     - GoogleAppMeasurement/AdIdSupport (= 8.2.0)
>     - GoogleUtilities/AppDelegateSwizzler (~> 7.4)
>     - GoogleUtilities/MethodSwizzler (~> 7.4)
>     - GoogleUtilities/Network (~> 7.4)
>     - "GoogleUtilities/NSData+zlib (~> 7.4)"
>     - nanopb (~> 2.30908.0)
>   - GoogleAppMeasurement/AdIdSupport (8.2.0):
>     - GoogleUtilities/AppDelegateSwizzler (~> 7.4)
>     - GoogleUtilities/MethodSwizzler (~> 7.4)
>     - GoogleUtilities/Network (~> 7.4)
>     - "GoogleUtilities/NSData+zlib (~> 7.4)"
>     - nanopb (~> 2.30908.0)
>   - GoogleDataTransport (9.0.1):
>     - GoogleUtilities/Environment (~> 7.2)
>     - nanopb (~> 2.30908.0)
>     - PromisesObjC (~> 1.2)
>   - GoogleUserMessagingPlatform (2.0.0)
>   - GoogleUtilities/AppDelegateSwizzler (7.4.3):
>     - GoogleUtilities/Environment
>     - GoogleUtilities/Logger
>     - GoogleUtilities/Network
>   - GoogleUtilities/Environment (7.4.3):
>     - PromisesObjC (~> 1.2)
>   - GoogleUtilities/ISASwizzler (7.4.3)
>   - GoogleUtilities/Logger (7.4.3):
>     - GoogleUtilities/Environment
>   - GoogleUtilities/MethodSwizzler (7.4.3):
>     - GoogleUtilities/Logger
>   - GoogleUtilities/Network (7.4.3):
>     - GoogleUtilities/Logger
>     - "GoogleUtilities/NSData+zlib"
>     - GoogleUtilities/Reachability
>   - "GoogleUtilities/NSData+zlib (7.4.3)"
>   - GoogleUtilities/Reachability (7.4.3):
>     - GoogleUtilities/Logger
>   - GoogleUtilities/UserDefaults (7.4.3):
>     - GoogleUtilities/Logger
>   - nanopb (2.30908.0):
>     - nanopb/decode (= 2.30908.0)
>     - nanopb/encode (= 2.30908.0)
>   - nanopb/decode (2.30908.0)
>   - nanopb/encode (2.30908.0)
>   - PromisesObjC (1.2.12)
>   - Protobuf (3.17.0)
> 
> DEPENDENCIES:
>   - Firebase
>   - Firebase/Analytics
>   - Firebase/Crashlytics
>   - Firebase/Performance
>   - Google-Mobile-Ads-SDK
> 
> SPEC REPOS:
>   trunk:
>     - Firebase
>     - FirebaseABTesting
>     - FirebaseAnalytics
>     - FirebaseCore
>     - FirebaseCoreDiagnostics
>     - FirebaseCrashlytics
>     - FirebaseInstallations
>     - FirebasePerformance
>     - FirebaseRemoteConfig
>     - Google-Mobile-Ads-SDK
>     - GoogleAppMeasurement
>     - GoogleDataTransport
>     - GoogleUserMessagingPlatform
>     - GoogleUtilities
>     - nanopb
>     - PromisesObjC
>     - Protobuf
> 
> SPEC CHECKSUMS:
>   Firebase: 12c568897b807321964e89d2b263ef4c6cff3db6
>   FirebaseABTesting: 5f37131c5eceea579c471c915f7a0f8cad484d1f
>   FirebaseAnalytics: 7a744b1e7dc50125cb37714c6bdaea167e412082
>   FirebaseCore: 3a83f24c3de69ec9f9a426e2598125ea51f3a2ce
>   FirebaseCoreDiagnostics: 61384f54989065b15c36b5922b65112e86811d3c
>   FirebaseCrashlytics: 935dbdb043a286ca92a22d15e5780802403ea0ea
>   FirebaseInstallations: 9394ea09e242bf0816e95ac30e56a9214cc86ced
>   FirebasePerformance: fe501d202ae945c4a457fc49e9ad9785b51ba6f8
>   FirebaseRemoteConfig: 6695557b3dac704527c952502e799586941d399e
>   Google-Mobile-Ads-SDK: e242f463fdb8564ac3f11847a30215a0e042c934
>   GoogleAppMeasurement: b52eafc9dff542d580700e708216568bd2fbf168
>   GoogleDataTransport: 04c3e9a480bbcaa2ec3f5d27f1cdeb6a92f20c8d
>   GoogleUserMessagingPlatform: ab890ce5f6620f293a21b6bdd82e416a2c73aeca
>   GoogleUtilities: 45dbb24a7f351d69d0a601482b39ad6c32e30dab
>   nanopb: a0ba3315591a9ae0a16a309ee504766e90db0c96
>   PromisesObjC: 3113f7f76903778cf4a0586bd1ab89329a0b7b97
>   Protobuf: 7327d4444215b5f18e560a97f879ff5503c4581c
> 
> PODFILE CHECKSUM: dd633a8ad26610feb18e1908fb3d320393a2fdb3
> 
> COCOAPODS: 1.10.1
> 

I'm wondering at this point if it's something about Objective-C or the target (iOS 12.1) or something else. I did have to do a LOT of updates to get gems working properly, but if I put the Crashlytics pod into the Podfile, I get the error.

**Comment by morganchen12** [comment]
@billdevoe I tried reproducing this build failure with a very similar Podfile but was unable to do so (see the attached sample project). I'm using Xcode 12.3, though that shouldn't be a factor in this issue.

[ReproExample.zip](https://github.com/firebase/firebase-ios-sdk/files/6718570/ReproExample.zip)

**Comment by billdevoe** [comment]
Well, @morganchen12 - looks like it's a configuration problem with my laptop. This is what I get when I build your project:
<img width="1260" alt="Screen Shot 2021-06-25 at 5 04 19 PM" src="https://user-images.githubusercontent.com/27469645/123492732-92a67700-d5d7-11eb-9def-5a1fc132be1c.png">

**Comment by billdevoe** [comment]
Hi @morganchen12 - I built the example project you posted and it works (when I correctly remember to change the build target to the iOS version). So it's not completely FUBAR on my machine, just with most of the basic things I'm doing. I'll keep poking around to see what differences exist between the two things.

This is the project I made that doesn't build properly for me.

[Firebase Test App.zip](https://github.com/firebase/firebase-ios-sdk/files/6719227/Firebase.Test.App.zip)

**Comment by paulb777** [comment]
Thanks for providing the example. The issue is clear now and fixed in #8308. The Crashlytics podspec was not defining one of its dependencies.

We do not typically see this issue because it is only exposed by an unusual Podfile.  Putting `use_frameworks!` inside a target causes CocoaPods to generate both frameworks and library build targets and that exposes the build issue.  There generally is not a reason to want to build all dependencies twice, so typically `use_frameworks!` is placed at the top of the Podfile.

**Comment by billdevoe** [comment]
Thanks @paulb777 - I used someone's example of a Podfile to create mine. I guess I didn't realize it was in the target. BUT - moving it out of the target section of the Podfile DOES fix the issue.

Happy I was able to help you identify a bug and fix it. :D 

Thanks for all the help, everyone. Very happy that things are working now. Much appreciated.

**Comment by abhideep** [comment]
So is the solution to move  

`use_frameworks!`

out of the loop?

`target 'Runner' do`

**Comment by bzdybowicz** [comment]
Hi guys, I have the FirebaseCrashlytics version 8.3.0, but I am still having the issue and I still don't see GoogleUtilities in frameworks list of FirebaseCrashlytics. What's up with that @paulb777

**Comment by kumabook** [comment]
`GoogleUtilities/Environment` dependency doesn't exist in podspec of cocoapods repo.

https://github.com/CocoaPods/Specs/blob/master/Specs/e/7/d/FirebaseCrashlytics/8.3.0/FirebaseCrashlytics.podspec.json#L42

Is this as intended?
I think build errors still occurs.

**Comment by paulb777** [comment]
Hmm, it looks like the fix missed 8.3.0. Sorry about that. 

It is staged for 8.4.0 - https://github.com/firebase/SpecsStaging/blob/master/FirebaseCrashlytics/8.4.0/FirebaseCrashlytics.podspec.json

**Comment by bzdybowicz** [comment]
When will it be deployed to public specs ?

**Comment by paulb777** [comment]
The 8.4.0 CocoaPods versions published today.

**Comment by paulb777** [comment]
I just noticed this issue is still in our top ten search traffic.

If you're still seeing this with releases after 8.4.0, please open another issue.
