### ISSUE TITLE
FirebaseFirestore missing some abseil object symbols

### ISSUE THREAD

**Issue by businessengine** [firebase/firebase-ios-sdk#898]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.2
  * Firebase SDK version: 4.10.0
  * Firebase Component: Firestore (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 0.10.2

### [REQUIRED] Step 3: Describe the problem
We included our private cocoapods, (working fine without Firebase libraries), however we got the following issue:
![image](https://user-images.githubusercontent.com/578995/37213246-0862df46-23e4-11e8-9c31-069ad43c9286.png)
Logs
```
Undefined symbols for architecture x86_64:
  "absl::base_internal::ThrowStdOutOfRange(char const*)", referenced from:
      absl::strings_internal::SplitIterator<absl::strings_internal::Splitter<absl::ByChar, absl::SkipEmpty> >::operator++() in FirebaseFirestore(resource_path_f1610fc30d8e6ee80923bc51b0b31dbf.o)
  "absl::string_view::find(absl::string_view, unsigned long) const", referenced from:
      firebase::firestore::model::ResourcePath::FromString(absl::string_view) in FirebaseFirestore(resource_path_f1610fc30d8e6ee80923bc51b0b31dbf.o)
  "absl::ByChar::Find(absl::string_view, unsigned long) const", referenced from:
      absl::strings_internal::SplitIterator<absl::strings_internal::Splitter<absl::ByChar, absl::SkipEmpty> >::operator++() in FirebaseFirestore(resource_path_f1610fc30d8e6ee80923bc51b0b31dbf.o)
  "absl::StrReplaceAll(absl::string_view, std::initializer_list<std::__1::pair<absl::string_view, absl::string_view> >)", referenced from:
      firebase::firestore::model::FieldPath::CanonicalString() const in FirebaseFirestore(field_path_745c64ad7b641183c86289111d67ec5b.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any ideas, guys? Thanks.

**Comment by wilhuff** [comment]
Looking specifically for `absl::StrReplaceAll` shows that this symbol is indeed undefined:

```
nm Pods/FirebaseFirestore/Frameworks/FirebaseFirestore.framework/FirebaseFirestore | c++filt | grep StrReplaceAll
                 U absl::StrReplaceAll(absl::string_view, std::initializer_list<std::__1::pair<absl::string_view, absl::string_view> >)
```

However, I'm able to use Firestore in a sample app without issue.

Can you send the full linker command-line from the logs?

Meanwhile, I'll look into why the build is producing a binary that doesn't include a definition for these functions.

**Comment by businessengine** [comment]
Thanks @wilhuff. Perhaps -all_load flag led to the issue, as when I removed -all_load flag from the podspec, it now works. It seems the problem is the FirebaseFirestore.podspec, where some .m/.cpp may not be included.

**Comment by wilhuff** [comment]
This was fixed with cl/188613750 in the internal build. The next release will contain all required symbol definitions.

Note to anyone who comes across this problem between now and then you can work around this by building the Firestore SDK from source. Add these two lines to your `Podfile` to do it:

```
pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'release-4.10.1'
pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'release-4.10.1'
```

**Comment by vishalcnz** [comment]
@wilhuff  I tried add those lines into my pod files and this is what happen when i tried to install pos 

```
Analyzing dependencies
Pre-downloading: `FirebaseCore` from `https://github.com/firebase/firebase-ios-sdk.git`, branch `release-4.10.1`
[!] Failed to download 'FirebaseCore'.
```

**Comment by wilhuff** [comment]
Here's a complete `Podfile` I have that I just verified works:

```
target 'firestore-from-source' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', branch: 'release-4.10.1'
  pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', branch: 'release-4.10.1'
end
```
Can you upload your complete Podfile?

**Comment by wilhuff** [comment]
Doh, @paulb777 is quicker on the draw! :-)

**Comment by vishalcnz** [comment]
@wilhuff Thanks for your quick reply. I tried this command but still i am facing same errors. Please find attached my pod file.

I also tried this with empty project with the following pod file:

```
target 'TestVishal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', branch: 'release-4.10.1'
  pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', branch: 'release-4.10.1'

end
```

And I got the following errors:

```
Analyzing dependencies
Pre-downloading: `FirebaseCore` from `https://github.com/firebase/firebase-ios-sdk.git`, branch `release-4.10.1`
Pre-downloading: `FirebaseFirestore` from `https://github.com/firebase/firebase-ios-sdk.git`, branch `release-4.10.1`
[!] CocoaPods could not find compatible versions for pod "FirebaseAnalytics":
  In Podfile:
    Firebase/Auth was resolved to 3.2.1, which depends on
      FirebaseAuth (= 3.0.2) was resolved to 3.0.2, which depends on
        FirebaseAnalytics (~> 3.2)

    FirebaseFirestore (from `https://github.com/firebase/firebase-ios-sdk.git`, branch `release-4.10.1`) was resolved to 0.10.3, which depends on
      FirebaseAnalytics (~> 4.0)

CocoaPods could not find compatible versions for pod "FirebaseCore":
  In Podfile:
    Firebase/Auth was resolved to 3.9.0, which depends on
      Firebase/Core (= 3.9.0) was resolved to 3.9.0, which depends on
        FirebaseCore (= 3.4.4)

    FirebaseCore (from `https://github.com/firebase/firebase-ios-sdk.git`, branch `release-4.10.1`)

    FirebaseFirestore (from `https://github.com/firebase/firebase-ios-sdk.git`, branch `release-4.10.1`) was resolved to 0.10.3, which depends on
      FirebaseCore (~> 4.0)

[!] Automatically assigning platform `ios` with version `11.2` on target `TestVishal` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```
[Podfile.txt](https://github.com/firebase/firebase-ios-sdk/files/1808910/Podfile.txt)

**Comment by wilhuff** [comment]
Your Cocoapods repo appears to be massively out of date. Try a `pod repo update` and then try again.

**Comment by vishalcnz** [comment]
Thanks again!

It looks like i was using very old Cocoapods repo so first i did this 

```
sudo gem install cocoapods
```
and then 
```
pod repo update
```
works fine for me Thanks @wilhuff

**Comment by paulb777** [comment]
Fixed in Firebase 4.11.0 FirebaseFirestore 0.10.4

**Comment by paulb777** [comment]
Seems to be a known problem with documented workarounds - https://github.com/GoogleCloudPlatform/ios-docs-samples/issues/30 and https://github.com/GoogleCloudPlatform/ios-docs-samples/blob/master/speech/Swift/Speech-gRPC-Streaming/BUILDFIXES

**Comment by paulb777** [comment]
Tracked at https://github.com/grpc/grpc/issues/7406

**Comment by vishalcnz** [comment]
@paulb777  Thanks for reply 

I am facing problem. When ever i try to install pod and try to run project it gives me error  like

```
duplicate symbol _FirebaseCoreVersionString
duplicate symbol _FirebaseFirestoreVersionString

```

I am trying to install this pods 
```
 pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', branch: 'release-4.10.1'
    pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', branch: 'release-4.10.1'

```

**Comment by vishalcnz** [comment]
Hello now i am trying this one 

```
pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '4.11.0'
pod 'FirebaseAuth', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '4.11.0'
pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '4.11.0'
```
I tried 
```
sudo gem install cocoapods
```
and then 
```
pod repo update
```
But still facing same problem

**Comment by vishalcnz** [comment]
It's works fine if i comment ``` FirebaseCoreVersionString``` in  ``` FIRVersion.h```  like this 

```
#import <Foundation/Foundation.h>

/** The version of the Firebase SDK. */
FOUNDATION_EXPORT const unsigned char *const FirebaseVersionString;

/** The version of the FirebaseCore Component. */
//FOUNDATION_EXPORT const unsigned char *const FirebaseCoreVersionString;
```

**Comment by paulb777** [comment]
@vishalcnz That error sounds strange. Do you have code that redefines the FOUNDATION_EXPORT macro?  What are the object files that the duplicate symbols come from?

**Comment by vishalcnz** [comment]
@paulb777 

It's come from this two files 

```
FirVersion.h
FirFirestoreVersion.h
```

**Comment by jtressle** [comment]
FYI, I opened a new issue for SDK 5.0.  This issue is still present.

https://github.com/firebase/firebase-ios-sdk/issues/1266

I tried using the above pod lines, but had the same issue.
