### ISSUE TITLE
SDK failed to compile, Undefined symbol: _OBJC_CLASS_$_FIRHeartbeatController, Xcode 13.3.1

### ISSUE THREAD

**Issue by InfinityCode777** [firebase/firebase-ios-sdk#9822]
### Environment

  * Xcode version: `13.3.1`
  * Firebase SDK version: `9.0.0`
  * Installation method: `Carthage`
  * Firebase Component: 
    * `FirebaseAnalyticsBinary`
    * `FirebasePerformanceBinary`
    * `FirebaseCrashlyticsBinary`
  * Target platform(s): `iOS`

### Problem

I was trying to update Firebase from `8.6.0 -> 9.0.0` using command 

```
$ carthage update --platform iOS --use-xcframeworks --no-use-binaries --cache-builds
```

Then I saw the following compilation error in Xcode log

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRHeartbeatController", referenced from:
      objc-class-ref in FirebaseCore(FIRHeartbeatLogger.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I checked  the complied `FirebaseCore` using `nm` and it's the confirmed that `_OBJC_CLASS_$_FIRHeartbeatController` is undefined

```
$ jingwang@jings-f8book-pro FirebaseCore.xcframework % nm ./ios-arm64/FirebaseCore.framework/FirebaseCore | grep _OBJC_CLASS_$_FIRHeartbeatController
```
<img width="790" alt="image" src="https://user-images.githubusercontent.com/8001169/169353538-f25d2bf5-5ec9-4bea-b279-98c4224cf31b.png">

#### Steps to reproduce:
It is very easy to reproduce this error and here is the [sample project](https://github.com/InfinityCode777/FirebaseSample). Also, I searched the repo `[firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk)` but I could not find that controller.

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/8001169/169372357-de88957a-1efc-4e56-8843-586252c47a4b.png">

#### Workaround
Then I rolled back to earlier version `8.9.1` and `8.9.0`, the compilation error was gone and the project complied and ran.

**Comment by ncooke3** [comment]
Hi @InfinityCode777,

Thanks for the report and sorry for the trouble! In Firebase 9, we refactored things and there is a new core framework called `FirebaseCoreInternal`. When running your `carthage update` command, you should see a `FirebaseCoreInternal.xcframework` in the `Carthage/Build/` directory.

Can you confirm that you have copied `FirebaseCoreInternal.xcframework` into your project?

**Comment by InfinityCode777** [comment]
Hi, @ncooke3 

Thanks for getting me back. Yes, I did see it, so should I include both `FirebaseCore` and `FirebaseCoreInternal` in my project? Thanks

<img width="533" alt="image" src="https://user-images.githubusercontent.com/8001169/169843717-49cabddb-01c6-43a1-9bdc-370d4a18ff23.png">

**Comment by ncooke3** [comment]
Yes, _both_ should be included in your project. This should resolve the build error.

**Comment by ivanornes** [comment]
I'm also getting this error in a project using cocoapods.

**Comment by ncooke3** [comment]
Hi @ivanornes, are you able to share a small project that reproduces the behavior you're seeing on CocoaPods?

**Comment by ivanornes** [comment]
Hi @ncooke3, I tried but couldn't reproduce in a small project. In the other one is still failing to find the FIRHeartbeatController even if it's in the project and even in the 9.1.0 version.

**Comment by ncooke3** [comment]
Does your `Podfile` include `use_frameworks!` or `use_frameworks! :linkage => :static`? If not, Firebase 9 requires that it does

**Comment by ivanornes** [comment]
Hi @ncooke3 , yes I'm using `use_frameworks! :linkage => :static`

I also tried 

`    pod 'Firebase/Core'`
`    pod 'Firebase/Crashlytics'`
`    pod 'Firebase/Analytics'`
`    pod 'Firebase/RemoteConfig'`

and 

`    pod 'FirebaseCore'`
`    pod 'FirebaseCrashlytics'`
`    pod 'FirebaseAnalytics'`
`    pod 'FirebaseRemoteConfig'`

And I'm getting the same issue with both approaches.

I'm also inheriting the search_paths for the extensions

`    target 'my_app' do`
`      inherit! :search_paths`
`    end`

**Comment by ivanornes** [comment]
Hi @ncooke3,

I just fixed the issue by removing the `FirebaseCore` `-framework` from an extensions framework search paths. 

Hope this helps!

**Comment by ncooke3** [comment]
Thanks @ivanornes for updating. Curious, are you using Firebase in your extension?

**Comment by ivanornes** [comment]
No problem @ncooke3. 
No, it was there for some reason

**Comment by ncooke3** [comment]
Thanks @ivanornes 👍 

@InfinityCode777, I'm going to close this as the solution for Carthage was to include the `FirebaseCoreInternal.xcframework`. I'm happy to re-open if there are further issues. Thanks!

**Comment by InfinityCode777** [comment]
> Thanks @ivanornes 👍
> 
> @InfinityCode777, I'm going to close this as the solution for Carthage was to include the `FirebaseCoreInternal.xcframework`. I'm happy to re-open if there are further issues. Thanks!

Hi, @ncooke3

The project compiles and runs after I included `FirebaseCoreInternal.xcframework` in the project. Thanks for the hope and I am sorry for such a late reply. 

Jing
